import { StyleSheet } from 'react-native';

import {
  mobileChromeTheme,
  mobileFeedbackTheme,
  mobileLayoutTheme,
  mobileOverlayTheme,
  mobilePalette as palette,
  mobileRadii,
  mobileSpacing,
  mobileTypeScale,
} from './theme';

export const mobileStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  container: {
    minHeight: '100%',
    paddingHorizontal: mobileSpacing['4xl'],
    paddingTop: mobileSpacing['3xl'],
    paddingBottom: mobileSpacing['6xl'],
    gap: mobileSpacing['4xl'],
  },
  bootSplash: {
    flex: 1,
    justifyContent: 'center',
    gap: mobileSpacing['3xl'],
    paddingHorizontal: mobileSpacing['4xl'],
    paddingVertical: mobileSpacing['5xl'],
  },
  bootCard: {
    gap: mobileSpacing.lg,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: mobileSpacing['4xl'],
    ...mobileChromeTheme.cardShadow,
  },
  bootSpinnerBadge: {
    alignSelf: 'flex-start',
    borderRadius: mobileRadii.full,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.accent,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.md,
    ...mobileChromeTheme.cardShadowSm,
  },
  bootSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.lg,
  },
  bootSummaryCard: {
    flex: 1,
    minWidth: 140,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  bootSummaryLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
  },
  bootSummaryValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    fontWeight: '800',
  },
  bootTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleSm,
    fontWeight: '800',
  },
  bootSubtitle: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  hero: {
    position: 'relative',
    minHeight: mobileLayoutTheme.heroMinHeight,
    gap: mobileSpacing.lg,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    overflow: 'hidden',
    padding: mobileLayoutTheme.cardPaddingLg,
    ...mobileChromeTheme.cardShadow,
  },
  heroCompact: {
    minHeight: 0,
    gap: mobileSpacing.md,
    padding: mobileSpacing['3xl'],
  },
  heroOrbWarm: {
    position: 'absolute',
    top: -28,
    right: -12,
    width: 120,
    height: 120,
    borderRadius: 999,
    backgroundColor: mobileOverlayTheme.warmTint,
  },
  heroOrbCool: {
    position: 'absolute',
    bottom: -34,
    right: 30,
    width: 92,
    height: 92,
    borderRadius: 999,
    backgroundColor: mobileOverlayTheme.coolTint,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: mobileSpacing.lg,
  },
  kicker: {
    alignSelf: 'flex-start',
    borderRadius: mobileRadii.full,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.accent,
    color: '#241605',
    fontSize: mobileTypeScale.fontSize.labelSm,
    fontWeight: '800',
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    overflow: 'hidden',
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.sm,
    textTransform: 'uppercase',
  },
  title: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.hero + 4,
    fontWeight: '800',
    lineHeight: mobileTypeScale.lineHeight.hero,
  },
  titleCompact: {
    fontSize: mobileTypeScale.fontSize.titleBase,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
  },
  subtitle: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
  },
  subtitleCompact: {
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  endpoint: {
    alignSelf: 'flex-start',
    borderRadius: mobileRadii.full,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: mobileSpacing.xs,
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.lg,
  },
  heroMetaCard: {
    flex: 1,
    minWidth: 136,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  heroMetaLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '700',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: 'uppercase',
  },
  heroMetaValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    fontWeight: '800',
  },
  heroFeedbackCard: {
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  heroCompactNotice: {
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  heroFeedbackDanger: {
    backgroundColor: mobileFeedbackTheme.danger.backgroundColor,
    borderColor: mobileFeedbackTheme.danger.borderColor,
  },
  heroFeedbackLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '700',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: 'uppercase',
  },
  heroFeedbackValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
    fontWeight: '600',
  },
  successText: {
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: mobileFeedbackTheme.success.borderColor,
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
    color: mobileFeedbackTheme.success.accentColor,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  errorText: {
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: mobileFeedbackTheme.danger.borderColor,
    backgroundColor: mobileFeedbackTheme.danger.backgroundColor,
    color: mobileFeedbackTheme.danger.accentColor,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  appStack: {
    gap: mobileSpacing['3xl'],
  },
  field: {
    gap: mobileSpacing.sm,
  },
  fieldLabel: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelSm,
    fontWeight: '600',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: 'uppercase',
  },
  input: {
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.input,
    color: palette.text,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.bodyLg,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
  },
  badge: {
    minHeight: mobileLayoutTheme.badgeHeight,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: mobileRadii.full,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.xs,
    ...mobileChromeTheme.cardShadowSm,
  },
  badgeSuccess: {
    borderColor: mobileFeedbackTheme.success.borderColor,
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
  },
  badgeWarning: {
    borderColor: mobileFeedbackTheme.warning.borderColor,
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  badgeMuted: {
    backgroundColor: palette.input,
  },
  badgeText: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '700',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: 'uppercase',
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
    alignItems: 'stretch',
  },
  balanceLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.caps,
  },
  balanceValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.metric,
    fontWeight: '800',
  },
  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: mobileSpacing.md,
  },
  loaderText: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
  },
  gachaMetaCard: {
    gap: mobileSpacing.sm,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.xl,
    ...mobileChromeTheme.cardShadowSm,
  },
  gachaMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: mobileSpacing.lg,
  },
  gachaMetaLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.label,
  },
  gachaMetaValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.body,
    fontWeight: '700',
  },
  gachaHint: {
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    color: palette.textMuted,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.labelSm,
    lineHeight: mobileTypeScale.lineHeight.label,
  },
  routeSwitcher: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
  },
  routeSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.lg,
  },
  routeSummaryCard: {
    flex: 1,
    minWidth: 130,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  routeSummaryLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
  },
  routeSummaryValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: '700',
  },
  entryFeatureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.lg,
  },
  entryFeatureCard: {
    flex: 1,
    minWidth: 150,
    gap: mobileSpacing.sm,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    padding: mobileSpacing.xl,
    ...mobileChromeTheme.cardShadowSm,
  },
  entryFeatureCardWarm: {
    backgroundColor: '#ffe58b',
  },
  entryFeatureCardInfo: {
    backgroundColor: '#dfe1ff',
  },
  entryFeatureCardPanel: {
    backgroundColor: palette.panelMuted,
  },
  entryFeatureTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    fontWeight: '800',
  },
  entryFeatureBody: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
});
