import type { RewardMission } from "@reward/shared-types/gamification";

import type { MobileFairnessLocale } from "./fairness";

const mobileCopy = {
  en: {
    appHero: {
      kicker: "Reward System Native",
      title: "Production session lifecycle for mobile.",
      subtitle:
        "Secure storage, cold-start restore, backend-backed logout, session self-service, and native game routes.",
      authSubtitle:
        "Secure storage, cold-start restore, backend-backed logout, session self-service, and native password-recovery/email-verification flows.",
      endpointLabel: "API",
    },
    restoringSession: {
      title: "Restoring secure session...",
      subtitle:
        "Checking the saved token with the backend before showing the app.",
    },
    auth: {
      email: "Email",
      emailPlaceholder: "user@example.com",
      password: "Password",
      birthDate: "Birth date",
      birthDatePlaceholder: "YYYY-MM-DD",
      loginTitle: "Sign in",
      registerTitle: "Create account",
      loginSubtitle:
        "Uses the backend session lifecycle: create, persist, restore, revoke.",
      tabs: {
        login: "Login",
        register: "Register",
      },
      submit: {
        busy: "Submitting...",
        login: "Sign in",
        register: "Create account",
      },
      forgotPasswordLink: "Forgot password?",
      verifyEmailLink: "Open verification link",
      backToApp: "Back to app",
      backToSignIn: "Back to sign in",
      forgotPassword: {
        title: "Reset password",
        subtitle:
          "Request a recovery link, then open it in the app or paste it below.",
        submit: "Send recovery link",
        submitting: "Sending...",
        resetLinkReady: "I already have a reset link",
      },
      resetPassword: {
        title: "Choose a new password",
        subtitle: "Paste the recovery link or just the token from the email.",
        tokenLabel: "Recovery link or token",
        tokenPlaceholder: "reward-mobile://reset-password?token=...",
        passwordLabel: "New password",
        submit: "Reset password",
        submitting: "Updating...",
        requestAnotherLink: "Request another link",
      },
      verifyEmail: {
        title: "Verify email",
        subtitle:
          "Open the verification message on this device or paste the verification link.",
        tokenLabel: "Verification link or token",
        tokenPlaceholder: "reward-mobile://verify-email?token=...",
        submit: "Verify email",
        submitting: "Verifying...",
        resend: "Send another verification email",
        resending: "Sending verification email...",
      },
      legal: {
        title: "Current legal documents",
        subtitle:
          "Review and accept every active document before creating the account.",
        loading: "Loading current documents...",
        empty: "No active legal documents are configured right now.",
        versionLabel: (version: string) => `Version ${version}`,
        checkboxLabel: (slug: string, version: string) =>
          `I accept ${slug} version ${version}.`,
        required: "Accept every current document before continuing.",
      },
    },
    legalGate: {
      title: "Accept updated legal documents",
      subtitle:
        "A new version is effective. Accept the pending documents before returning to the app.",
      loading: "Loading current documents...",
      empty: "No current documents were returned.",
      versionLabel: (version: string) => `Version ${version}`,
      acceptedBadge: "Already accepted",
      checkboxLabel: (slug: string, version: string) =>
        `Accept ${slug} version ${version}.`,
      submit: "Accept and continue",
      submitting: "Recording acceptance...",
      refresh: "Refresh documents",
      required: "Accept every pending document before continuing.",
      success: "Legal documents accepted. Returning to the app.",
    },
    verificationCallout: {
      title: "Finish email verification",
      subtitle:
        "Gameplay routes stay read-only until the account email is verified.",
      send: "Send verification email",
      sending: "Sending verification...",
      open: "Open verification",
    },
    signedIn: {
      title: (email: string) => `Signed in as ${email}`,
      subtitle: (platform: string, role: string) =>
        `Platform: ${platform} · Role: ${role}`,
      unknownUser: "Unknown user",
      unknownRole: "unknown",
      emailVerified: "Email verified",
      emailNotVerified: "Email not verified",
      sessionActive: "Session active",
      sessionLoading: "Session loading",
      balance: (value: string) => `Balance ${value}`,
      refreshBalance: "Refresh balance",
      refreshSessions: "Refresh sessions",
      refreshing: "Refreshing...",
      signOut: "Sign out",
      signingOut: "Signing out...",
    },
    wallet: {
      title: "Wallet",
      subtitle:
        "B luck and vouchers come from the shared `/wallet` contract; store purchases stay native.",
      currentBalance: "Current balance",
      refresh: "Refresh wallet",
      refreshing: "Refreshing...",
      refreshEconomy: "Refresh gifting",
      refreshingEconomy: "Refreshing gifting...",
      economyLoading: "Loading economy...",
      assetsTitle: "Asset balances",
      available: "Available",
      locked: "Locked",
      giftTitle: "B luck gifting",
      giftSubtitle:
        "Gifting only uses earned B luck. Voucher balances never expose a send flow.",
      giftEnergy: "Gift energy",
      receiverUserId: "Receiver user ID",
      receiverUserIdPlaceholder: "e.g. 1024",
      giftAmount: "Gift amount",
      giftAmountPlaceholder: "e.g. 10",
      sendGift: "Send gift",
      sendingGift: "Sending...",
      giftHistory: "Recent gifts",
      historyEmpty: "No gifts yet.",
      giftTransferLabel: (senderUserId: number, receiverUserId: number) =>
        `#${senderUserId} -> #${receiverUserId}`,
      giftEnergyCost: (energyCost: number) => `Energy cost ${energyCost}`,
      ledgerTitle: "Economy ledger",
      ledgerEmpty: "No economy entries yet.",
      ledgerLabels: {
        earned: "Earned",
        spend: "Spend",
        giftSent: "Gift sent",
        giftReceived: "Gift received",
        purchase: "Purchase",
        refundRollback: "Refund reversal",
      },
      purchaseTitle: "Voucher store",
      purchaseSubtitle:
        "Uses native App Store / Play checkout. Successful verification only delivers IAP vouchers.",
      giftPackTitle: "Gift pack store",
      giftPackSubtitle:
        "Buy a gift pack and deliver it directly to a recipient. It never lands in the buyer's transferable balance.",
      giftPackRecipientUserId: "Gift recipient user ID",
      giftPackRecipientPlaceholder: "e.g. 2048",
      giftPackEmpty: "No active gift packs are configured for this store.",
      giftPackRewardLabel: "Gift delivery",
      giftPackTitleFallback: "Gift pack",
      buyGiftPack: "Buy for user",
      buyingGiftPack: "Purchasing...",
      productsLoading: "Loading store products...",
      productsEmpty: "No active voucher products are configured for this store.",
      productsUnavailable:
        "Store connection is not ready. Open a development or internal-testing build and sign in to the sandbox store first.",
      storeReady: "Store connected",
      storeUnavailable: "Store unavailable",
      syncPending: "Sync pending purchases",
      syncingPending: "Syncing pending purchases...",
      refreshProducts: "Refresh store products",
      buying: "Purchasing...",
      buy: "Buy",
      amountLabel: "Delivery",
      priceFallback: "Price unavailable",
      productTitleFallback: "Voucher pack",
      assetLabels: {
        B_LUCK: "B luck",
        IAP_VOUCHER: "Voucher",
      },
    },
    rewardCenter: {
      title: "Reward center",
      subtitle:
        "Same `/rewards/center` and `/rewards/claim` endpoints as the web app.",
      summary: {
        bonusBalance: "B luck",
        checkInStreak: "Check-in streak",
        readyToClaim: "Ready to claim",
      },
      refresh: "Refresh rewards",
      refreshing: "Refreshing...",
      todayCheckInGranted: "Today's check-in granted",
      loading: "Loading reward missions...",
      empty: "No reward missions are configured yet.",
      statusLabels: {
        disabled: "Disabled",
        in_progress: "In progress",
        ready: "Ready",
        claimed: "Claimed",
      } satisfies Record<RewardMission["status"], string>,
      legacyMissionCopy: {
        daily_checkin: {
          title: "Daily check-in",
          description:
            "Sign in each day to keep the streak active and receive the daily auto bonus.",
        },
        profile_security: {
          title: "Security setup",
          description:
            "Verify email and phone to unlock finance tools and earn a profile setup bonus.",
        },
        first_draw: {
          title: "First draw",
          description:
            "Complete your first draw to start the engagement ladder.",
        },
        draw_streak_daily: {
          title: "Draw sprint",
          description:
            "Finish 3 draws in one day to unlock the daily sprint payout.",
        },
        top_up_starter: {
          title: "First deposit bonus",
          description:
            "Complete your first credited deposit to receive an automatic starter bonus.",
        },
      } satisfies Record<string, { title: string; description: string }>,
      autoAwardedBadge: "Auto",
      rewardAmount: "B luck",
      progress: (current: number, target: number) =>
        `Progress ${current}/${target}`,
      claimedAt: (value: string) => `Claimed ${value}`,
      resetsAt: (value: string) => `Resets ${value}`,
      claimWhenReady: "Claim when progress is full.",
      autoAwardedNote: "Granted automatically when completed.",
      claim: "Claim reward",
      claiming: "Claiming...",
    },
    sessionSecurity: {
      title: "Session security",
      subtitle:
        "List active sessions, revoke a single session, or sign out everywhere.",
      currentSessionId: (value: string) => `Current session ID: ${value}`,
      expiresSummary: (value: string) => `Expires: ${value}`,
      refresh: "Refresh list",
      refreshing: "Refreshing...",
      resetPassword: "Reset password",
      signOutEverywhere: "Sign out everywhere",
      loading: "Loading active sessions...",
      empty: "No active sessions found.",
      currentDevice: "Current device",
      activeSession: "Active session",
      currentBadge: "Current",
      id: (value: string) => `ID: ${value}`,
      ip: (value: string) => `IP: ${value}`,
      unavailable: "Unavailable",
      userAgent: (value: string) => `User-Agent: ${value}`,
      createdAt: (value: string) => `Created: ${value}`,
      lastSeenAt: (value: string) => `Last seen: ${value}`,
      expiresAt: (value: string) => `Expires: ${value}`,
      signOutDevice: "Sign out this device",
      revokeSession: "Revoke session",
      kyc: {
        title: "KYC verification",
        subtitle:
          "Track tier status here, then jump into the hosted flow on this device for document upload or resubmission.",
        loading: "Loading KYC profile...",
        refresh: "Refresh KYC",
        refreshing: "Refreshing...",
        open: "Open verification page",
        currentTier: "Current tier",
        requestedTier: "Requested tier",
        status: "Review status",
        submissionVersion: (value: number) => `Submission v${value}`,
        documents: (value: number) => `${value} document(s) on file`,
        noSubmission:
          "No KYC submission has been started yet. Open the verification page to upload documents.",
        submittedAt: (value: string) => `Submitted: ${value}`,
        reviewedAt: (value: string) => `Reviewed: ${value}`,
        rejectionReason: (value: string) => `Review note: ${value}`,
        riskFlags: (value: string) => `Risk flags: ${value}`,
        hostedHandoff:
          "Document capture stays in the hosted verification flow so you can resubmit from the same account without leaving the product path.",
        tier0: "Tier 0 demo",
        tier1: "Tier 1 small-stake",
        tier2: "Tier 2 withdraw + multiplayer",
      },
    },
  },
  "zh-CN": {
    appHero: {
      kicker: "Reward System Native",
      title: "移动端生产级会话生命周期。",
      subtitle:
        "统一覆盖安全存储、冷启动恢复、后端驱动登出、会话自助管理和原生玩法路由。",
      authSubtitle:
        "统一覆盖安全存储、冷启动恢复、后端驱动登出、会话自助管理，以及原生找回密码和邮箱验证流程。",
      endpointLabel: "接口",
    },
    restoringSession: {
      title: "正在恢复安全会话...",
      subtitle: "先用已保存 token 向后端确认会话，再决定是否展示应用内容。",
    },
    auth: {
      email: "邮箱",
      emailPlaceholder: "user@example.com",
      password: "密码",
      birthDate: "出生日期",
      birthDatePlaceholder: "YYYY-MM-DD",
      loginTitle: "登录",
      registerTitle: "创建账户",
      loginSubtitle: "走后端真实会话生命周期：创建、持久化、恢复、撤销。",
      tabs: {
        login: "登录",
        register: "注册",
      },
      submit: {
        busy: "提交中...",
        login: "登录",
        register: "创建账户",
      },
      forgotPasswordLink: "忘记密码？",
      verifyEmailLink: "打开验证链接",
      backToApp: "返回应用",
      backToSignIn: "返回登录",
      forgotPassword: {
        title: "重置密码",
        subtitle: "先申请找回链接，然后在应用内打开，或者直接粘贴到下面。",
        submit: "发送找回链接",
        submitting: "发送中...",
        resetLinkReady: "我已经有重置链接了",
      },
      resetPassword: {
        title: "设置新密码",
        subtitle: "把找回链接整体贴进来，或者只贴邮件里的 token。",
        tokenLabel: "找回链接或 Token",
        tokenPlaceholder: "reward-mobile://reset-password?token=...",
        passwordLabel: "新密码",
        submit: "重置密码",
        submitting: "更新中...",
        requestAnotherLink: "重新申请链接",
      },
      verifyEmail: {
        title: "验证邮箱",
        subtitle: "直接在这台设备上打开验证邮件，或者把验证链接粘贴到这里。",
        tokenLabel: "验证链接或 Token",
        tokenPlaceholder: "reward-mobile://verify-email?token=...",
        submit: "验证邮箱",
        submitting: "验证中...",
        resend: "重新发送验证邮件",
        resending: "验证邮件发送中...",
      },
      legal: {
        title: "当前生效条款",
        subtitle: "创建账户前，请先阅读并接受所有当前生效文档。",
        loading: "正在加载当前文档...",
        empty: "当前还没有配置生效中的法律文档。",
        versionLabel: (version: string) => `版本 ${version}`,
        checkboxLabel: (slug: string, version: string) =>
          `我接受 ${slug} 第 ${version} 版。`,
        required: "继续前请先接受所有当前文档。",
      },
    },
    legalGate: {
      title: "接受更新后的条款",
      subtitle: "已有新版本文档生效。先接受待签文档，再继续返回应用。",
      loading: "正在加载当前文档...",
      empty: "当前没有返回可签署文档。",
      versionLabel: (version: string) => `版本 ${version}`,
      acceptedBadge: "已接受",
      checkboxLabel: (slug: string, version: string) =>
        `接受 ${slug} 第 ${version} 版。`,
      submit: "接受并继续",
      submitting: "正在记录签署...",
      refresh: "刷新文档",
      required: "继续前请先接受所有待签文档。",
      success: "条款已接受，正在返回应用。",
    },
    verificationCallout: {
      title: "完成邮箱验证",
      subtitle: "邮箱未验证前，玩法路由保持只读，不允许进入真实交互。",
      send: "发送验证邮件",
      sending: "发送验证中...",
      open: "打开验证页",
    },
    signedIn: {
      title: (email: string) => `当前登录：${email}`,
      subtitle: (platform: string, role: string) =>
        `平台：${platform} · 角色：${role}`,
      unknownUser: "未知用户",
      unknownRole: "未知",
      emailVerified: "邮箱已验证",
      emailNotVerified: "邮箱未验证",
      sessionActive: "会话有效",
      sessionLoading: "会话加载中",
      balance: (value: string) => `余额 ${value}`,
      refreshBalance: "刷新余额",
      refreshSessions: "刷新会话",
      refreshing: "刷新中...",
      signOut: "退出登录",
      signingOut: "退出中...",
    },
    wallet: {
      title: "钱包",
      subtitle:
        "B luck 和点券直接复用共享 `/wallet` 合同，购买始终走原生商店。",
      currentBalance: "当前余额",
      refresh: "刷新钱包",
      refreshing: "刷新中...",
      refreshEconomy: "刷新送礼",
      refreshingEconomy: "刷新送礼中...",
      economyLoading: "正在加载经济数据...",
      assetsTitle: "资产余额",
      available: "可用",
      locked: "锁定",
      giftTitle: "B luck 送礼",
      giftSubtitle: "送礼只允许使用 earned B luck，点券余额不提供赠送入口。",
      giftEnergy: "送礼能量",
      receiverUserId: "接收用户 ID",
      receiverUserIdPlaceholder: "例如 1024",
      giftAmount: "赠送金额",
      giftAmountPlaceholder: "例如 10",
      sendGift: "发送礼物",
      sendingGift: "赠送中...",
      giftHistory: "最近送礼",
      historyEmpty: "还没有送礼记录。",
      giftTransferLabel: (senderUserId: number, receiverUserId: number) =>
        `#${senderUserId} -> #${receiverUserId}`,
      giftEnergyCost: (energyCost: number) => `能量消耗 ${energyCost}`,
      ledgerTitle: "经济账本",
      ledgerEmpty: "还没有经济流水。",
      ledgerLabels: {
        earned: "获得",
        spend: "消耗",
        giftSent: "赠送",
        giftReceived: "收礼",
        purchase: "购买",
        refundRollback: "退款回滚",
      },
      purchaseTitle: "点券商店",
      purchaseSubtitle:
        "走 App Store / Play 原生购买，验证成功后只发 IAP 点券。",
      giftPackTitle: "礼物包商店",
      giftPackSubtitle:
        "购买后直接送达接收人，不会先进入购买者自己的可流通余额。",
      giftPackRecipientUserId: "礼物接收用户 ID",
      giftPackRecipientPlaceholder: "例如 2048",
      giftPackEmpty: "当前商店还没有启用的礼物包商品。",
      giftPackRewardLabel: "送达内容",
      giftPackTitleFallback: "礼物包",
      buyGiftPack: "为该用户购买",
      buyingGiftPack: "购买中...",
      productsLoading: "正在加载商店商品...",
      productsEmpty: "当前商店还没有启用的点券商品。",
      productsUnavailable:
        "商店连接还没就绪。请使用开发构建或内测包，并先登录对应沙盒商店账号。",
      storeReady: "商店已连接",
      storeUnavailable: "商店不可用",
      syncPending: "同步待处理订单",
      syncingPending: "正在同步待处理订单...",
      refreshProducts: "刷新商店商品",
      buying: "购买中...",
      buy: "购买",
      amountLabel: "到账",
      priceFallback: "价格暂不可用",
      productTitleFallback: "点券礼包",
      assetLabels: {
        B_LUCK: "B luck",
        IAP_VOUCHER: "点券",
      },
    },
    rewardCenter: {
      title: "奖励中心",
      subtitle:
        "直接复用与 Web 相同的 `/rewards/center` 和 `/rewards/claim` 接口。",
      summary: {
        bonusBalance: "B luck",
        checkInStreak: "签到连击",
        readyToClaim: "可领取",
      },
      refresh: "刷新奖励",
      refreshing: "刷新中...",
      todayCheckInGranted: "今日签到奖励已发放",
      loading: "正在加载奖励任务...",
      empty: "当前还没有配置奖励任务。",
      statusLabels: {
        disabled: "已停用",
        in_progress: "进行中",
        ready: "可领取",
        claimed: "已领取",
      } satisfies Record<RewardMission["status"], string>,
      legacyMissionCopy: {
        daily_checkin: {
          title: "每日签到",
          description: "每天签到以保持连续天数，并自动获得当日奖励。",
        },
        profile_security: {
          title: "安全设置",
          description: "完成邮箱和手机号验证，解锁资金工具并领取资料安全奖励。",
        },
        first_draw: {
          title: "首次抽奖",
          description: "完成第一次抽奖，启动你的活跃成长阶梯。",
        },
        draw_streak_daily: {
          title: "当日连抽",
          description: "单日完成 3 次抽奖，解锁每日冲刺奖励。",
        },
        top_up_starter: {
          title: "首充奖励",
          description: "完成第一笔到账充值后，系统会自动发放首充奖励。",
        },
      } satisfies Record<string, { title: string; description: string }>,
      autoAwardedBadge: "自动",
      rewardAmount: "B luck",
      progress: (current: number, target: number) =>
        `进度 ${current}/${target}`,
      claimedAt: (value: string) => `领取时间 ${value}`,
      resetsAt: (value: string) => `重置时间 ${value}`,
      claimWhenReady: "进度满后即可领取。",
      autoAwardedNote: "任务完成后自动发放。",
      claim: "领取奖励",
      claiming: "领取中...",
    },
    sessionSecurity: {
      title: "会话安全",
      subtitle: "查看活跃会话、撤销单个设备，或一键退出全部设备。",
      currentSessionId: (value: string) => `当前会话 ID：${value}`,
      expiresSummary: (value: string) => `过期时间：${value}`,
      refresh: "刷新列表",
      refreshing: "刷新中...",
      resetPassword: "重置密码",
      signOutEverywhere: "全部退出",
      loading: "正在加载活跃会话...",
      empty: "当前没有活跃会话。",
      currentDevice: "当前设备",
      activeSession: "活跃会话",
      currentBadge: "当前",
      id: (value: string) => `ID：${value}`,
      ip: (value: string) => `IP：${value}`,
      unavailable: "不可用",
      userAgent: (value: string) => `设备指纹：${value}`,
      createdAt: (value: string) => `创建时间：${value}`,
      lastSeenAt: (value: string) => `最后活跃：${value}`,
      expiresAt: (value: string) => `过期时间：${value}`,
      signOutDevice: "退出当前设备",
      revokeSession: "撤销会话",
      kyc: {
        title: "KYC 实名认证",
        subtitle:
          "先在这里查看等级和审核状态，再在本机打开托管验证页完成材料上传或补件。",
        loading: "正在加载 KYC 档案...",
        refresh: "刷新 KYC",
        refreshing: "刷新中...",
        open: "打开验证页",
        currentTier: "当前等级",
        requestedTier: "申请等级",
        status: "审核状态",
        submissionVersion: (value: number) => `提交版本 v${value}`,
        documents: (value: number) => `已提交 ${value} 份材料`,
        noSubmission:
          "还没有开始 KYC 申请。打开验证页即可上传身份材料。",
        submittedAt: (value: string) => `提交时间：${value}`,
        reviewedAt: (value: string) => `审核时间：${value}`,
        rejectionReason: (value: string) => `审核备注：${value}`,
        riskFlags: (value: string) => `风险标记：${value}`,
        hostedHandoff:
          "证件采集继续走托管验证流程，这样你可以在同一账号路径里直接补件或重提。",
        tier0: "Tier 0 试玩",
        tier1: "Tier 1 小额玩法",
        tier2: "Tier 2 提现 + 多人",
      },
    },
  },
} as const;

export function getMobileAppCopy(locale: MobileFairnessLocale) {
  return mobileCopy[locale];
}

export type MobileAppCopy = ReturnType<typeof getMobileAppCopy>;
export type MobileAuthCopy = MobileAppCopy["auth"];
export type MobileVerificationCalloutCopy =
  MobileAppCopy["verificationCallout"];
export type MobileSignedInCopy = MobileAppCopy["signedIn"];
export type MobileWalletCopy = MobileAppCopy["wallet"];
export type MobileRewardCenterCopy = MobileAppCopy["rewardCenter"];
export type MobileSessionSecurityCopy = MobileAppCopy["sessionSecurity"];
export type MobileKycCopy = MobileSessionSecurityCopy["kyc"];
