import { StyleSheet } from 'react-native';

import {
  mobileFeedbackTheme,
  mobilePalette as palette,
  mobileRadii,
  mobileSpacing,
  mobileTypeScale,
} from './theme';

export const mobileStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  container: {
    minHeight: '100%',
    paddingHorizontal: mobileSpacing['4xl'],
    paddingVertical: mobileSpacing['6xl'],
    gap: mobileSpacing['3xl'],
  },
  bootSplash: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: mobileSpacing.lg,
    paddingHorizontal: mobileSpacing['5xl'],
  },
  bootTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleSm,
    fontWeight: '700',
  },
  bootSubtitle: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    textAlign: 'center',
  },
  hero: {
    gap: mobileSpacing.md,
  },
  kicker: {
    color: palette.accent,
    fontSize: mobileTypeScale.fontSize.labelSm,
    fontWeight: '700',
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    textTransform: 'uppercase',
  },
  title: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.hero,
    fontWeight: '800',
    lineHeight: mobileTypeScale.lineHeight.hero,
  },
  subtitle: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
  },
  endpoint: {
    color: palette.accentMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
  },
  successText: {
    borderRadius: mobileRadii.lg,
    borderWidth: 1,
    borderColor: mobileFeedbackTheme.success.borderColor,
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
    color: mobileFeedbackTheme.success.accentColor,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  errorText: {
    borderRadius: mobileRadii.lg,
    borderWidth: 1,
    borderColor: mobileFeedbackTheme.danger.borderColor,
    backgroundColor: mobileFeedbackTheme.danger.backgroundColor,
    color: mobileFeedbackTheme.danger.accentColor,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
  },
  appStack: {
    gap: mobileSpacing['3xl'],
  },
  field: {
    gap: mobileSpacing.sm,
  },
  fieldLabel: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelSm,
    fontWeight: '600',
  },
  input: {
    borderRadius: mobileRadii.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.input,
    color: palette.text,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.bodyLg,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
  },
  badge: {
    borderRadius: mobileRadii.full,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: mobileSpacing['2xs'],
  },
  badgeSuccess: {
    borderColor: mobileFeedbackTheme.success.borderColor,
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
  },
  badgeWarning: {
    borderColor: mobileFeedbackTheme.warning.borderColor,
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  badgeMuted: {
    backgroundColor: palette.input,
  },
  badgeText: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: '600',
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
  },
  balanceLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.caps,
  },
  balanceValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.metric,
    fontWeight: '800',
  },
  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: mobileSpacing.md,
  },
  loaderText: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
  },
  gachaMetaCard: {
    gap: mobileSpacing.sm,
    borderRadius: mobileRadii.xl,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.xl,
  },
  gachaMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: mobileSpacing.lg,
  },
  gachaMetaLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.label,
  },
  gachaMetaValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.body,
    fontWeight: '700',
  },
  gachaHint: {
    borderRadius: mobileRadii.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    color: palette.textMuted,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    fontSize: mobileTypeScale.fontSize.labelSm,
    lineHeight: mobileTypeScale.lineHeight.label,
  },
  routeSwitcher: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.md,
  },
  routeSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mobileSpacing.lg,
  },
  routeSummaryCard: {
    flex: 1,
    minWidth: 130,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: mobileSpacing.lg,
  },
  routeSummaryLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    textTransform: 'uppercase',
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
  },
  routeSummaryValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: '700',
  },
});
