import type { MobileFairnessLocale } from './fairness';

export type MobileRouteKey =
  | 'home'
  | 'account'
  | 'wallet'
  | 'rewards'
  | 'community'
  | 'security'
  | 'notifications'
  | 'gacha'
  | 'quickEight'
  | 'predictionMarket'
  | 'holdem'
  | 'blackjack'
  | 'fairness';

export type HomeMenuRouteKey = Exclude<MobileRouteKey, 'home'>;

type RouteCardKey = HomeMenuRouteKey;
type RouteHeroKey = HomeMenuRouteKey;
type RouteScreenKey =
  | 'gacha'
  | 'quickEight'
  | 'predictionMarket'
  | 'holdem'
  | 'blackjack';

export const homeMenuRouteOrder = [
  'account',
  'wallet',
  'rewards',
  'community',
  'security',
  'gacha',
  'quickEight',
  'predictionMarket',
  'holdem',
  'blackjack',
  'fairness',
] as const satisfies readonly HomeMenuRouteKey[];

const routeCopy = {
  en: {
    labels: {
      home: 'Home',
      account: 'Account',
      wallet: 'Wallet',
      rewards: 'Rewards',
      community: 'Community',
      security: 'Security',
      notifications: 'Notifications',
      gacha: 'Slot',
      quickEight: 'Quick Eight',
      predictionMarket: 'Markets',
      holdem: "Hold'em",
      blackjack: 'Blackjack',
      fairness: 'Fairness',
    } satisfies Record<MobileRouteKey, string>,
    homeSectionTitle: 'Route menu',
    homeSectionSubtitle:
      'Home is now a menu list. Account, wallet, rewards, security, prediction markets, and each game open on their own dedicated screens.',
    currentRouteTitle: (label: string) => `Route: ${label}`,
    currentRouteSubtitle:
      'This route owns its own workflow instead of rendering back into the home dashboard.',
    currentRouteHint:
      'Home is only a launcher now. Account, wallet, rewards, security, and every game stay on their own screens.',
    cards: {
      account: {
        title: 'Account',
        body:
          'Email status, current device session, balance refresh, and sign-out controls live on a dedicated account page.',
        open: 'Open account',
      },
      wallet: {
        title: 'Wallet',
        body:
          'Keep the current balance on a dedicated wallet page instead of mixing it into the route launcher.',
        open: 'Open wallet',
      },
      rewards: {
        title: 'Rewards',
        body:
          'Daily missions, bonus balance, and claim actions now sit on their own rewards page.',
        open: 'Open rewards',
      },
      community: {
        title: 'Community',
        body:
          'Browse visible threads, open a discussion, and reply from a dedicated mobile community route.',
        open: 'Open community',
      },
      security: {
        title: 'Security',
        body:
          'Password reset, active session review, and device revocation are split into a dedicated security page.',
        open: 'Open security',
      },
      notifications: {
        title: 'Notifications',
        body:
          'KYC reviews, withdrawal progress, and settled market updates now land in a dedicated inbox route.',
        open: 'Open notifications',
      },
      gacha: {
        title: 'Slot machine',
        body:
          'Three-reel presentation, pity progress, and committed draw settlement now live on a standalone route.',
        open: 'Open slot machine',
      },
      quickEight: {
        title: 'Quick Eight',
        body:
          'Pick 8 numbers, confirm the stake, and watch the draw reveal in sequence on its own screen.',
        open: 'Open Quick Eight',
      },
      predictionMarket: {
        title: 'Prediction market',
        body:
          'Browse open and settled markets, inspect pooled outcomes, place positions, and review your holdings on a dedicated route.',
        open: 'Open markets',
      },
      holdem: {
        title: "Texas Hold'em",
        body:
          'Create or join multiplayer casual or cash tables, choose the seat count, and play each street on its own mobile route.',
        open: "Open Hold'em",
      },
      blackjack: {
        title: 'Blackjack',
        body:
          'Player-vs-dealer blackjack with hit, stand, double, split, and shared fairness controls.',
        open: 'Open Blackjack',
      },
      fairness: {
        title: 'Fairness verifier',
        body:
          'Reveal a closed epoch and prove locally that SHA-256(seed) matches the published commit hash.',
        open: 'Open fairness verifier',
      },
    } satisfies Record<RouteCardKey, { title: string; body: string; open: string }>,
    heroes: {
      account: {
        kicker: 'Account',
        title: 'Dedicated account route for session and identity controls.',
        subtitle:
          'Mobile keeps account status, session refresh, and sign-out actions on their own screen instead of in the route launcher.',
      },
      wallet: {
        kicker: 'Wallet',
        title: 'Dedicated wallet route for balance visibility.',
        subtitle:
          'Mobile gives the wallet its own screen so balance review stays separate from navigation and gameplay.',
      },
      rewards: {
        kicker: 'Rewards',
        title: 'Dedicated rewards route for missions and bonus balance.',
        subtitle:
          'Mobile keeps check-ins, mission progress, and reward claims on a standalone rewards screen.',
      },
      community: {
        kicker: 'Community',
        title: 'Dedicated route for public discussion and replies.',
        subtitle:
          'Mobile keeps visible threads, posting, and moderation-aware reply flow on a standalone community screen.',
      },
      security: {
        kicker: 'Security',
        title: 'Dedicated security route for device and password controls.',
        subtitle:
          'Mobile keeps active-session review, password reset, and revoke flows on a dedicated security screen.',
      },
      notifications: {
        kicker: 'Notifications',
        title: 'Dedicated inbox route for account and market alerts.',
        subtitle:
          'Mobile keeps KYC reviews, withdrawal progress, and settled prediction market updates in one read-tracked feed.',
      },
      gacha: {
        kicker: 'Slot',
        title: 'Dedicated slot route for the draw engine.',
        subtitle:
          'Mobile keeps the three-reel presentation and committed draw settlement on a standalone screen aligned with the web slot route.',
      },
      quickEight: {
        kicker: 'Quick Eight',
        title: 'Dedicated route for number-pick play.',
        subtitle:
          'Mobile keeps Quick Eight off the dashboard and runs the same `/quick-eight` flow as web on its own screen.',
      },
      predictionMarket: {
        kicker: 'Markets',
        title: 'Dedicated route for prediction market flow.',
        subtitle:
          'Mobile keeps open, locked, and settled markets on a standalone screen where you can browse pools, place positions, and review outcomes.',
      },
      holdem: {
        kicker: "Hold'em",
        title: 'Dedicated route for multiplayer casual and cash-table hands.',
        subtitle:
          'Mobile keeps the lobby, table mode, seat count, buy-in, and street-by-street table actions on a standalone route that polls the same backend table state as web.',
      },
      blackjack: {
        kicker: 'Blackjack',
        title: 'Dedicated route for player-vs-dealer hands.',
        subtitle:
          'Mobile runs blackjack on its own route, using the same backend fairness, wallet settlement, and split flow as web.',
      },
      fairness: {
        kicker: 'Fairness',
        title: 'Dedicated route for commit-reveal verification.',
        subtitle:
          'Mobile keeps fairness validation off the home dashboard and lets you reveal a closed epoch on its own screen.',
      },
    } satisfies Record<RouteHeroKey, { kicker: string; title: string; subtitle: string }>,
    screens: {
      gacha: {
        routeTitle: 'Slot machine route',
        routeSubtitle:
          'Dedicated mobile screen for the draw flow, aligned with the web slot-machine route.',
        summaryBalance: 'Balance',
        summarySecondary: 'Live pool',
        summarySecondaryLoading: 'Loading',
        summarySecondaryValue: (featuredCount: number) => `${featuredCount} featured`,
        sectionTitle: 'Slot machine',
        sectionSubtitle:
          'Uses the same `/draw/overview`, `/draw`, and `/draw/play` flow as the web slot route.',
        metaCostPerPull: 'Cost per pull',
        metaPity: 'Pity',
        metaFairness: 'Fairness',
        pityBoostActive: 'Boost active',
        pityDisabled: 'Disabled',
        pityPullsToBoost: (draws: number) => `${draws} spins to boost`,
        slotRevealTitle: 'Slot reveal',
        slotToneSpinningBatch: (count: number) => `Spinning ${count} times...`,
        slotToneSpinningSingle: 'Spinning the reels...',
        slotToneWin: 'Winning line locked.',
        slotToneBlocked: 'Result blocked by inventory or payout control.',
        slotToneSettled: 'Finale settled. Review the spin summary below.',
        slotToneReady: 'Ready for the first spin.',
        slotHintAnimating: 'The mobile reel locks left to right, matching the web rhythm.',
        slotHintSettled:
          'Center line settles on the highlighted outcome after the spin finishes.',
        pullOnce: 'Spin once',
        pullMany: (count: number) => `Spin ${count}`,
        pulling: 'Spinning...',
        refreshBanner: 'Refresh slot board',
        disabledBySystem: 'Draws are currently disabled by system config.',
        multiLocked: (max: number) =>
          `Multi-spin is locked because \`draw_system.max_draw_per_request\` is currently ${max}.`,
        loadingBanner: 'Loading the live slot machine...',
        loadingPlay: (count: number) =>
          count > 1
            ? `Calling POST /draw/play (${count})...`
            : 'Calling POST /draw...',
        noActivePrizes: 'No active prizes are configured yet.',
        latestSinglePull: 'Latest single spin',
        latestBatchPull: (count: number) => `Latest ${count}-spin`,
        highlight: 'Highlight',
        noFeaturedReward: 'No featured reward',
        noPullYet: 'No spin yet. Use the controls above to reveal the first result.',
      },
      quickEight: {
        routeTitle: 'Quick Eight route',
        routeSubtitle: 'Dedicated mobile screen for number-pick gameplay.',
        summaryBalance: 'Balance',
        summarySelection: 'Selection',
        routeHint: (pickCount: number, boardSize: number, drawCount: number) =>
          `Pick exactly ${pickCount} numbers from 1 to ${boardSize}. The backend draws ${drawCount} numbers and settles immediately.`,
        sectionTitle: 'Quick Eight',
        sectionSubtitle: 'Same `/quick-eight` endpoint and payout table as the web app.',
        selectionTitle: 'Your numbers',
        selectionLocked: 'Selection locked',
        selectionLeft: (remaining: number) => `${remaining} left`,
        noSelection: 'No numbers selected yet.',
        clear: 'Clear',
        stakeAmount: 'Stake amount',
        stakeRange: (min: string, max: string) => `Min ${min} / Max ${max}`,
        play: 'Play Quick Eight',
        drawing: 'Drawing...',
        loadingRequest: 'Calling POST /quick-eight...',
        latestRound: 'Latest round',
        payout: 'Payout',
        drawnNumbers: (visible: number, total: number) => `Drawn numbers ${visible}/${total}`,
        matchedNumbers: 'Matched numbers',
        noMatches: 'No matches this round.',
        noRoundYet: 'No round yet. Pick numbers, set a stake, and start the draw.',
      },
      predictionMarket: {
        routeTitle: 'Prediction market route',
        routeSubtitle:
          'Dedicated mobile screen for browsing markets, placing positions, and reviewing holdings.',
        summaryBalance: 'Balance',
        summaryActiveMarket: 'Active market',
        summaryHoldings: 'My positions',
        summaryLoading: 'Loading',
        summaryEmpty: 'None',
        sectionTitle: 'Prediction markets',
        sectionSubtitle:
          'Uses the same `GET /markets`, `GET /markets/history`, `GET /markets/:marketId`, and `POST /markets/:marketId/positions` flow as the backend user API.',
        refreshMarkets: 'Refresh markets',
        refreshingMarkets: 'Refreshing...',
        marketListTitle: 'Markets',
        marketDetailTitle: 'Market detail',
        myHoldingsTitle: 'My prediction markets',
        myHoldingsSubtitle:
          'Grouped market history shows open exposure, settled payouts, and refunds without opening each market one by one.',
        exposureOnlyTitle: 'Exposure only',
        exposureOnlyDescription:
          'The current pari-mutuel release shows stake exposure, net-of-vig settled payouts, and refunds. It does not calculate live PnL while markets are still open.',
        refreshHistory: 'Refresh history',
        loadingHistory: 'Loading history...',
        noMarkets: 'No prediction markets are configured yet.',
        noMarketSelected:
          'Select a market above to inspect pools, timing, and bet controls.',
        noDescription: 'No market description provided.',
        marketStatus: 'Market status',
        positionStatus: 'Position status',
        settlementStatus: 'Settlement',
        totalPool: 'Total pool',
        openPositions: 'Open positions',
        yourPositions: 'Your positions',
        yourExposure: 'Your exposure',
        winningOutcome: 'Winning outcome',
        mechanism: 'Mechanism',
        opensAt: 'Opens',
        locksAt: 'Locks',
        resolvesAt: 'Resolves',
        resolvedAt: 'Resolved',
        lastUpdated: 'Updated',
        selectOutcome: 'Select outcome',
        selectedOutcome: 'Selected outcome',
        chooseOutcome: 'Choose an outcome first.',
        stakeAmount: 'Stake amount',
        stakeHint:
          'Enter a positive amount. Payout is pari-mutuel, net of vig, and finalizes only after market resolution.',
        placeBet: 'Place position',
        placingBet: 'Placing...',
        marketClosed: 'This market is not accepting new positions.',
        outcomePool: (stake: string, count: number, share: string) =>
          `${stake} pooled · ${count} positions · ${share}`,
        winningPool: (stake: string) => `${stake} winning pool`,
        positionPlacedAt: 'Placed',
        positionSettledAt: 'Settled',
        potentialPayout: 'Payout',
        noPositions: 'No positions on this market yet.',
        noHoldings: 'You have not opened any prediction market positions yet.',
        noFilteredHoldings: 'No grouped history matches this filter yet.',
        noOutcomePools: 'No pool activity yet.',
        marketCountLabel: 'Markets',
        positionCountLabel: 'Positions',
        totalStake: 'Total stake',
        openExposure: 'Open exposure',
        settledPayout: 'Settled payout',
        refundedAmount: 'Refunded amount',
        lastActivity: 'Last activity',
        roundKey: 'Round',
        focusMarket: 'Focus market',
        previousPage: 'Previous page',
        nextPage: 'Next page',
        portfolioPageValue: (page: number) => `Page ${page}`,
        portfolioFilterLabels: {
          all: 'All',
          open: 'Open',
          resolved: 'Resolved',
          refunded: 'Refunded',
        },
        portfolioStatusLabels: {
          open: 'Open',
          resolved: 'Resolved',
          refunded: 'Refunded',
        },
        marketStatusLabels: {
          draft: 'Draft',
          open: 'Open',
          locked: 'Locked',
          resolved: 'Resolved',
          cancelled: 'Cancelled',
        },
        positionStatusLabels: {
          open: 'Open',
          won: 'Won',
          lost: 'Lost',
          sold: 'Sold',
          refunded: 'Refunded',
        },
        settlementPending: 'Pending resolution',
        settlementResolved: 'Resolved',
        settlementCancelled: 'Cancelled',
        winningOutcomePending: 'Pending',
        mechanismPariMutuel: 'Pari-mutuel',
        outcomeWinner: 'Winner',
      },
      holdem: {
        routeTitle: "Texas Hold'em route",
        routeSubtitle:
          'Dedicated mobile screen for multiplayer casual and cash-table play, seat-count selection, and per-street actions.',
        summaryBalance: 'Balance',
        summaryStatus: 'Table status',
        summaryLoading: 'Loading',
        sectionTitle: "Texas Hold'em",
        sectionSubtitle:
          'Same `GET /holdem/tables`, `POST /holdem/tables`, join, leave, start, and action endpoints as web.',
        tableMode: 'Table mode',
        tableName: 'Table name',
        seatCount: 'Seats',
        buyInAmount: 'Buy-in amount',
        tournamentStartingStack: 'Starting stack',
        tournamentPayoutPlaces: 'Payout places',
        buyInRange: (min: string, max: string) => `Min ${min} / Max ${max}`,
        casualTableHint:
          'Casual tables use bonus balance, do not charge rake, and do not require KYC.',
        cashTableHint: 'Cash tables use withdrawable balance and the live rake policy.',
        tournamentTableHint:
          'Tournament tables freeze buy-ins into a pooled prize pool, seat every entry with the same starting stack, and only settle prizes after elimination order is final.',
        tournamentPayoutPlacesHint:
          'Final payout slots are capped to the actual registration count, up to three places.',
        createTable: 'Create table',
        creatingTable: 'Opening...',
        joinTable: 'Join table',
        joiningTable: 'Buying in...',
        leaveTable: 'Leave table',
        leavingTable: 'Cashing out...',
        sitOutTable: 'Sit out',
        sittingOutTable: 'Sitting out...',
        sitInTable: 'Sit back in',
        sittingInTable: 'Returning...',
        startHand: 'Start hand',
        startingHand: 'Shuffling...',
        refreshTable: 'Refresh table',
        refreshingTable: 'Refreshing...',
        noTables: 'No tables are open yet.',
        noSelection: 'Choose a table from the lobby to view the current hand.',
        board: 'Board',
        actionClock: 'Action clock',
        currentBet: 'Current bet',
        toCall: 'To call',
        minRaiseTo: 'Min raise to',
        actionAmount: 'Action amount',
        blinds: 'Blinds',
        tableType: 'Table type',
        cashTable: 'Cash',
        casualTable: 'Casual',
        tournamentTable: 'Tournament',
        rakePolicy: 'Rake',
        rakeCap: 'cap',
        rakeNone: 'No rake',
        rakeNoFlopNoDrop: 'No flop, no drop',
        fairness: 'Fairness',
        timeBank: 'Time bank',
        stack: 'Stack',
        streetCommitted: 'Street',
        totalCommitted: 'Total',
        mainPot: 'Main pot',
        sidePot: 'Side pot',
        winners: 'Winners',
        hand: 'Hand',
        tableChat: 'Table chat',
        tableChatEmpty: 'No table chat yet. Seat in and break the silence.',
        tableChatPlaceholder: 'Type a table message',
        tableChatSend: 'Send',
        tableChatSending: 'Sending...',
        tableChatReactions: 'Reactions',
        tableChatSeatOnly: 'Only seated players can chat or send table reactions.',
        recentHands: 'Recent hands',
        noRecentHands: 'No settled hands yet.',
        viewReplay: 'Open replay',
        hideReplay: 'Hide replay',
        replayLoading: 'Loading hand replay...',
        replayFailed: 'Failed to load this hand replay.',
        replayDetailTitle: "Hold'em replay detail",
        replayDetailSubtitle:
          'Full hand replay, event timeline, and dispute metadata for the selected settled hand.',
        replayBackToTable: 'Back to table',
        copyDisputePayload: 'Copy dispute payload',
        exportHandEvidence: 'Export signed evidence bundle',
        replayArtifactCopied: 'Dispute payload copied.',
        replayArtifactExported: 'Signed evidence bundle exported.',
        replayArtifactFailed: 'Evidence bundle action failed.',
        replayBundleSummary: 'Signed bundle summary',
        replayBundleExportedAt: 'Exported',
        replayBundleKeyId: 'Key id',
        replayBundleDigest: 'Payload digest',
        replaySummary: 'Replay summary',
        replayTimeline: 'Event timeline',
        replayParticipants: 'Participants',
        replayStake: 'Stake',
        replayPayout: 'Payout',
        replayRake: 'Rake',
        replayStartedAt: 'Started',
        replaySettledAt: 'Settled',
        replayDispute: 'Dispute detail',
        replayRoundId: 'Round id',
        replayReferenceId: 'Reference id',
        replayEventCount: 'Events',
        replaySupportHint:
          'Use the round id, reference id, and fairness commit for audit or dispute review.',
        stagePreflop: 'Preflop',
        stageFlop: 'Flop',
        stageTurn: 'Turn',
        stageRiver: 'River',
        stageShowdown: 'Showdown',
        eventHandStarted: 'Hand started',
        eventCardsDealt: 'Hole cards dealt',
        eventSmallBlindPosted: 'Small blind posted',
        eventBigBlindPosted: 'Big blind posted',
        eventTurnStarted: 'Turn started',
        eventTurnTimedOut: 'Turn timed out',
        eventPlayerActed: 'Player acted',
        eventBoardRevealed: 'Board revealed',
        eventFairnessRevealed: 'Fairness revealed',
        eventShowdownResolved: 'Showdown resolved',
        eventHandWonByFold: 'Won by fold',
        eventHandSettled: 'Hand settled',
        openSeat: 'Open seat',
        you: 'You',
        dealer: 'Dealer',
        smallBlind: 'SB',
        bigBlind: 'BB',
        turn: 'Turn',
        fold: 'Fold',
        check: 'Check',
        call: 'Call',
        bet: 'Bet',
        raise: 'Raise',
        allIn: 'All-in',
        amountHint:
          'Bet and raise amounts use the total chips you want committed on this street.',
        waitingStatus: 'Waiting',
        sittingOutStatus: 'Sitting out',
        activeStatus: 'Active',
        realtimeConnecting: 'Connecting live table feed...',
        realtimeLive: 'Live table feed active.',
        realtimeReconnecting: 'Reconnecting live table feed...',
        realtimeResyncing: 'Reconnected. Syncing authoritative table state...',
      },
      blackjack: {
        routeTitle: 'Blackjack route',
        routeSubtitle:
          'Blackjack with an AI dealer seated at the same table, still settled by the shared wallet, fairness, and prize-pool backend.',
        summaryBalance: 'Balance',
        summaryFairnessEpoch: 'Fairness epoch',
        summaryLoading: 'Loading',
        sectionTitle: 'Blackjack',
        sectionSubtitle:
          'Same `GET /blackjack`, `POST /blackjack/start`, and `POST /blackjack/:id/action` endpoints as web.',
        metaStakeRange: 'Stake range',
        metaNaturalPayout: 'Natural payout',
        metaDealer: 'Dealer',
        metaDouble: 'Double',
        metaSplitAces: 'Split aces',
        metaHitSplitAces: 'Hit split aces',
        metaResplit: 'Re-split',
        metaMaxSplitHands: 'Max split hands',
        metaTenValueSplit: '10-value split',
        dealerHitsSoft17: 'Hit soft 17',
        dealerStandAll17: 'Stand on all 17s',
        doubleEnabled: 'Enabled',
        doubleDisabled: 'Disabled',
        stakeAmount: 'Stake amount',
        stakeHint: (min: string, max: string) =>
          `Enter a stake between ${min} and ${max}, then open one active hand at a time.`,
        startHand: 'Start hand',
        dealing: 'Dealing...',
        refreshHand: 'Refresh hand',
        refreshingHand: 'Refreshing...',
        noActiveHand: 'No active hand. The next start request will deal a fresh round.',
        tableTitle: 'Same-table seating',
        tableId: 'Table',
        seat: 'Seat',
        aiDealer: 'AI dealer',
        you: 'You',
        dealerHand: 'Dealer',
        playerHand: 'Player',
        visible: 'Visible',
        total: 'Total',
        settling: 'Settling...',
        hit: 'Hit',
        stand: 'Stand',
        double: 'Double',
        split: 'Split',
        hand: 'Hand',
        currentBet: 'Bet',
        activeHand: 'Active',
        waitingHand: 'Waiting',
        stoodHand: 'Standing',
        bustHand: 'Bust',
        winHand: 'Win',
        loseHand: 'Lose',
        pushHand: 'Push',
        recentHands: 'Recent hands',
        noRecentHands: 'No completed blackjack hands yet.',
        loadingState: 'Refreshing blackjack state...',
      },
    } satisfies Record<RouteScreenKey, Record<string, unknown>>,
  },
  'zh-CN': {
    labels: {
      home: '首页',
      account: '账户',
      wallet: '钱包',
      rewards: '奖励',
      community: '社区',
      security: '安全',
      notifications: '通知',
      gacha: '老虎机',
      quickEight: '快八',
      predictionMarket: '预测盘',
      holdem: '德州',
      blackjack: '二十一点',
      fairness: '公平性',
    } satisfies Record<MobileRouteKey, string>,
    homeSectionTitle: '页面入口',
    homeSectionSubtitle:
      '首页现在只做菜单列表，账户、钱包、奖励、安全、预测盘和各个玩法都会跳到各自独立页面。',
    currentRouteTitle: (label: string) => `当前路由：${label}`,
    currentRouteSubtitle: '当前能力在自己的独立页面里运行，不再塞回首页仪表盘。',
    currentRouteHint:
      '首页现在只是入口页，账户、钱包、奖励、安全，以及各个玩法都走各自页面。',
    cards: {
      account: {
        title: '账户',
        body:
          '邮箱状态、当前设备会话、余额刷新和退出登录动作都放到独立账户页。',
        open: '打开账户页',
      },
      wallet: {
        title: '钱包',
        body:
          '当前余额单独放到钱包页里，不再和首页入口混在一起。',
        open: '打开钱包页',
      },
      rewards: {
        title: '奖励',
        body:
          '每日任务、奖励余额和领奖动作都拆到独立奖励页。',
        open: '打开奖励页',
      },
      community: {
        title: '社区',
        body:
          '浏览可见主题、发起讨论，并在独立移动端社区页里完成公开回复。',
        open: '打开社区页',
      },
      security: {
        title: '安全',
        body:
          '重置密码、查看活跃会话和撤销设备会话都拆到独立安全页。',
        open: '打开安全页',
      },
      notifications: {
        title: '通知中心',
        body:
          'KYC 审核、提现进度和预测市场结算统一进入专门的通知收件箱。',
        open: '打开通知中心',
      },
      gacha: {
        title: '老虎机',
        body:
          '三轴演出、保底进度和真实抽奖结算都拆到独立路由里，不再放在首页。',
        open: '打开老虎机页面',
      },
      quickEight: {
        title: '快八',
        body:
          '选号、下注和逐步揭晓开奖号码全部放到独立页面中完成。',
        open: '打开快八页',
      },
      predictionMarket: {
        title: '预测盘',
        body:
          '浏览可下注和已结算的市场，查看各结果奖池、下注并统一回看自己的持仓状态。',
        open: '打开预测盘',
      },
      holdem: {
        title: '德州扑克',
        body:
          '创建或加入多人娱乐局或现金桌，选择人数后入桌，并按 preflop / flop / turn / river 依次推进。',
        open: '打开德州牌桌',
      },
      blackjack: {
        title: '二十一点',
        body:
          '支持分牌的经典庄闲二十一点，与共享 fairness 控制、钱包结算一起放到独立页面。',
        open: '打开二十一点页',
      },
      fairness: {
        title: '公平性验证器',
        body:
          'Reveal 已结束的 epoch，并在本地证明 `SHA-256(seed)` 与已公布的 commit 哈希一致。',
        open: '打开公平性验证页',
      },
    } satisfies Record<RouteCardKey, { title: string; body: string; open: string }>,
    heroes: {
      account: {
        kicker: '账户',
        title: '会话与身份操作的独立账户路由。',
        subtitle:
          '移动端把账户状态、会话刷新和退出登录动作拆到独立页面，不再放在入口页里。',
      },
      wallet: {
        kicker: '钱包',
        title: '余额查看的独立钱包路由。',
        subtitle:
          '移动端给钱包单独一页，让余额查看和导航入口、玩法页面彻底分开。',
      },
      rewards: {
        kicker: '奖励',
        title: '任务与奖励余额的独立奖励路由。',
        subtitle:
          '移动端把签到、任务进度和领奖动作集中到单独奖励页中。',
      },
      community: {
        kicker: '社区',
        title: '公开讨论与回帖的独立社区路由。',
        subtitle:
          '移动端把可见主题、发帖动作和带审核策略的回复流程集中到独立社区页面。',
      },
      security: {
        kicker: '安全',
        title: '设备与密码操作的独立安全路由。',
        subtitle:
          '移动端把活跃会话审查、密码重置和会话撤销都放到专门的安全页里。',
      },
      notifications: {
        kicker: '通知',
        title: '账户与市场提醒的独立通知路由。',
        subtitle:
          '移动端把 KYC、提现和预测市场结算提醒集中到一个可读、可清空的通知页里。',
      },
      gacha: {
        kicker: '老虎机',
        title: '抽奖引擎的独立老虎机路由。',
        subtitle:
          '移动端把三轴停轴演出和真实抽奖结算拆到单独页面里，与 Web 的 slot 路由保持一致。',
      },
      quickEight: {
        kicker: '快八',
        title: '独立的选号玩法路由。',
        subtitle:
          '移动端把快八从首页拆开，独立跑同一套 `/quick-eight` 流程和即时结算。',
      },
      predictionMarket: {
        kicker: '预测盘',
        title: '独立的预测市场路由。',
        subtitle:
          '移动端把开放中、封盘中和已结算的市场集中到一个独立页面里，支持浏览奖池、下注和查看持仓结果。',
      },
      holdem: {
        kicker: '德州',
        title: '独立的多人娱乐局与现金桌路由。',
        subtitle:
          '移动端把牌桌大厅、桌型、人数、买入和每条街的行动都放到独立页面里，继续轮询和 Web 相同的后端桌局状态。',
      },
      blackjack: {
        kicker: '二十一点',
        title: '独立的庄闲牌局路由。',
        subtitle:
          '移动端把二十一点单独放到一个页面里，继续复用与 Web 相同的 fairness、钱包结算和分牌流程。',
      },
      fairness: {
        kicker: '公平性',
        title: '独立的 commit-reveal 验证路由。',
        subtitle:
          '移动端把公平性验证从首页拆开，单独放到一个页面里，专门用来 reveal 已结束的 epoch 并做本地校验。',
      },
    } satisfies Record<RouteHeroKey, { kicker: string; title: string; subtitle: string }>,
    screens: {
      gacha: {
        routeTitle: '老虎机路由',
        routeSubtitle: '抽奖流程拆成独立移动端页面，并和 Web 的老虎机路由保持对齐。',
        summaryBalance: '余额',
        summarySecondary: '当前奖池',
        summarySecondaryLoading: '加载中',
        summarySecondaryValue: (featuredCount: number) => `${featuredCount} 个主推奖项`,
        sectionTitle: '老虎机',
        sectionSubtitle:
          '直接复用 Web 同一套 `/draw/overview`、`/draw` 与 `/draw/play` 流程。',
        metaCostPerPull: '单抽消耗',
        metaPity: '保底',
        metaFairness: '公平性',
        pityBoostActive: '概率加成中',
        pityDisabled: '未启用',
        pityPullsToBoost: (draws: number) => `还差 ${draws} 抽触发加成`,
        slotRevealTitle: '停轴揭晓',
        slotToneSpinningBatch: (count: number) => `正在旋转 ${count} 次...`,
        slotToneSpinningSingle: '转轴旋转中...',
        slotToneWin: '中奖线已锁定。',
        slotToneBlocked: '结果被库存或赔付控制拦截。',
        slotToneSettled: '本轮已结算，可查看下方旋转结果摘要。',
        slotToneReady: '准备好开始第一次旋转。',
        slotHintAnimating: '移动端沿用 Web 一样的从左到右锁轴节奏。',
        slotHintSettled: '转轴结束后，中线会停在本轮高亮结果上。',
        pullOnce: '旋转一次',
        pullMany: (count: number) => `旋转 ${count} 次`,
        pulling: '旋转中...',
        refreshBanner: '刷新老虎机',
        disabledBySystem: '系统配置当前已关闭抽奖。',
        multiLocked: (max: number) =>
          `当前 \`draw_system.max_draw_per_request\` 为 ${max}，所以多次旋转仍被锁定。`,
        loadingBanner: '正在加载当前老虎机...',
        loadingPlay: (count: number) =>
          count > 1
            ? `正在调用 POST /draw/play（${count} 抽）...`
            : '正在调用 POST /draw...',
        noActivePrizes: '当前还没有配置主推奖项。',
        latestSinglePull: '最近一次旋转',
        latestBatchPull: (count: number) => `最近 ${count} 次旋转`,
        highlight: '高亮奖励',
        noFeaturedReward: '没有主推奖励',
        noPullYet: '还没有开始旋转，使用上方控件揭晓第一轮结果。',
      },
      quickEight: {
        routeTitle: '快八路由',
        routeSubtitle: '选号玩法拆成独立移动端页面。',
        summaryBalance: '余额',
        summarySelection: '选号进度',
        routeHint: (pickCount: number, boardSize: number, drawCount: number) =>
          `请从 1 到 ${boardSize} 中选满 ${pickCount} 个号码。后端会立即开出 ${drawCount} 个号码并结算。`,
        sectionTitle: '快八',
        sectionSubtitle: '直接复用 Web 同一套 `/quick-eight` 接口与赔率表。',
        selectionTitle: '你的号码',
        selectionLocked: '号码已选满',
        selectionLeft: (remaining: number) => `还差 ${remaining} 个`,
        noSelection: '还没有选择任何号码。',
        clear: '清空',
        stakeAmount: '下注金额',
        stakeRange: (min: string, max: string) => `最小 ${min} / 最大 ${max}`,
        play: '开始快八',
        drawing: '开奖中...',
        loadingRequest: '正在调用 POST /quick-eight...',
        latestRound: '最近一期',
        payout: '派奖',
        drawnNumbers: (visible: number, total: number) => `开奖号码 ${visible}/${total}`,
        matchedNumbers: '命中号码',
        noMatches: '本轮没有命中号码。',
        noRoundYet: '当前还没有开奖记录。先选号码、设金额，再开始开奖。',
      },
      predictionMarket: {
        routeTitle: '预测盘路由',
        routeSubtitle: '市场浏览、下注和持仓拆成独立移动端页面。',
        summaryBalance: '余额',
        summaryActiveMarket: '当前市场',
        summaryHoldings: '我的持仓',
        summaryLoading: '加载中',
        summaryEmpty: '暂无',
        sectionTitle: '预测盘',
        sectionSubtitle:
          '直接复用同一套 `GET /markets`、`GET /markets/history`、`GET /markets/:marketId` 和 `POST /markets/:marketId/positions` 用户接口。',
        refreshMarkets: '刷新市场',
        refreshingMarkets: '刷新中...',
        marketListTitle: '市场列表',
        marketDetailTitle: '市场详情',
        myHoldingsTitle: '我的预测市场',
        myHoldingsSubtitle:
          '按市场分组展示你的未结算敞口、已结算派奖和退款，不用逐个打开市场查看。',
        exposureOnlyTitle: '仅展示敞口与历史',
        exposureOnlyDescription:
          '当前 pari-mutuel 版本只展示 stake 敞口、扣除抽水后的已结算 payout 和退款，不计算市场仍在开放时的实时盈亏。',
        refreshHistory: '刷新历史',
        loadingHistory: '加载历史中...',
        noMarkets: '当前还没有配置预测盘市场。',
        noMarketSelected: '先从上方选择一个市场，再查看奖池、时间和下注控件。',
        noDescription: '当前市场还没有补充说明。',
        marketStatus: '市场状态',
        positionStatus: '持仓状态',
        settlementStatus: '结算状态',
        totalPool: '总奖池',
        openPositions: '进行中持仓',
        yourPositions: '你的持仓',
        yourExposure: '你的敞口',
        winningOutcome: '胜出结果',
        mechanism: '机制',
        opensAt: '开盘时间',
        locksAt: '封盘时间',
        resolvesAt: '预计结算',
        resolvedAt: '实际结算',
        lastUpdated: '最近更新',
        selectOutcome: '选择结果',
        selectedOutcome: '当前选择',
        chooseOutcome: '请先选择一个下注结果。',
        stakeAmount: '下注金额',
        stakeHint: '输入大于 0 的金额。预测盘采用奖池分配并先扣抽水，最终派奖要等市场结算后才能确定。',
        placeBet: '下注',
        placingBet: '下注中...',
        marketClosed: '当前市场已停止接收新下注。',
        outcomePool: (stake: string, count: number, share: string) =>
          `奖池 ${stake} · ${count} 笔持仓 · 占比 ${share}`,
        winningPool: (stake: string) => `胜出奖池 ${stake}`,
        positionPlacedAt: '建仓时间',
        positionSettledAt: '结算时间',
        potentialPayout: '派奖',
        noPositions: '你在这个市场里还没有持仓。',
        noHoldings: '你还没有任何预测盘持仓。',
        noFilteredHoldings: '当前筛选条件下还没有对应的分组历史。',
        noOutcomePools: '当前还没有任何奖池流入。',
        marketCountLabel: '市场数',
        positionCountLabel: '仓位数',
        totalStake: '总下注',
        openExposure: '未结算敞口',
        settledPayout: '已结算派奖',
        refundedAmount: '退款金额',
        lastActivity: '最近活动',
        roundKey: '轮次',
        focusMarket: '定位市场',
        previousPage: '上一页',
        nextPage: '下一页',
        portfolioPageValue: (page: number) => `第 ${page} 页`,
        portfolioFilterLabels: {
          all: '全部',
          open: '未结算',
          resolved: '已结算',
          refunded: '已退款',
        },
        portfolioStatusLabels: {
          open: '未结算',
          resolved: '已结算',
          refunded: '已退款',
        },
        marketStatusLabels: {
          draft: '草稿',
          open: '开放中',
          locked: '已封盘',
          resolved: '已结算',
          cancelled: '已取消',
        },
        positionStatusLabels: {
          open: '进行中',
          won: '已中奖',
          lost: '未命中',
          sold: '已卖出',
          refunded: '已退款',
        },
        settlementPending: '待结算',
        settlementResolved: '已结算',
        settlementCancelled: '已取消',
        winningOutcomePending: '待公布',
        mechanismPariMutuel: '奖池分配',
        outcomeWinner: '胜出',
      },
      holdem: {
        routeTitle: '德州路由',
        routeSubtitle: '多人娱乐局与现金桌玩法拆成独立移动端页面。',
        summaryBalance: '余额',
        summaryStatus: '桌面状态',
        summaryLoading: '加载中',
        sectionTitle: '德州扑克',
        sectionSubtitle:
          '直接复用 Web 同一套 `GET /holdem/tables`、创建、入座、离桌、开局和行动接口。',
        tableMode: '桌型模式',
        tableName: '桌名',
        seatCount: '人数',
        buyInAmount: '买入金额',
        tournamentStartingStack: '起始筹码',
        tournamentPayoutPlaces: '派奖名次',
        buyInRange: (min: string, max: string) => `最小 ${min} / 最大 ${max}`,
        casualTableHint: '娱乐局使用奖励余额买入，不抽水，且不要求 KYC。',
        cashTableHint: '现金桌使用可提现余额买入，并应用实时抽水策略。',
        tournamentTableHint:
          '锦标赛会把买入汇总进奖池，所有参赛者统一起始筹码，直到淘汰名次确定后才统一派奖。',
        tournamentPayoutPlacesHint:
          '最终派奖名次数会按实际报名人数收口，最多只发到前三名。',
        createTable: '创建牌桌',
        creatingTable: '正在开桌...',
        joinTable: '加入牌桌',
        joiningTable: '正在买入...',
        leaveTable: '离桌',
        leavingTable: '正在退桌...',
        sitOutTable: '暂离一手',
        sittingOutTable: '正在暂离...',
        sitInTable: '回到桌上',
        sittingInTable: '正在恢复入局...',
        startHand: '开始发牌',
        startingHand: '正在洗牌...',
        refreshTable: '刷新牌桌',
        refreshingTable: '刷新中...',
        noTables: '当前还没有开放的牌桌。',
        noSelection: '先从大厅选择一张牌桌，再查看当前牌局。',
        board: '公共牌',
        actionClock: '行动时限',
        currentBet: '当前下注',
        toCall: '跟注到',
        minRaiseTo: '最小加到',
        actionAmount: '行动金额',
        blinds: '盲注',
        tableType: '桌型',
        cashTable: '现金桌',
        casualTable: '娱乐局',
        tournamentTable: '锦标赛',
        rakePolicy: '抽水',
        rakeCap: '封顶',
        rakeNone: '不抽水',
        rakeNoFlopNoDrop: '未发翻牌不抽水',
        fairness: '公平性',
        timeBank: '时间银行',
        stack: '筹码',
        streetCommitted: '本街',
        totalCommitted: '总投入',
        mainPot: '主池',
        sidePot: '边池',
        winners: '赢家',
        hand: '手牌',
        tableChat: '桌内聊天',
        tableChatEmpty: '桌上还没人发消息。先入座再打破沉默。',
        tableChatPlaceholder: '输入桌内消息',
        tableChatSend: '发送',
        tableChatSending: '发送中...',
        tableChatReactions: '快捷表情',
        tableChatSeatOnly: '只有已入座玩家可以发送桌内聊天和表情。',
        recentHands: '最近牌局',
        noRecentHands: '还没有已结算牌局。',
        viewReplay: '打开回放',
        hideReplay: '收起回放',
        replayLoading: '正在加载牌局回放...',
        replayFailed: '加载这手牌回放失败。',
        replayDetailTitle: '德州回放详情',
        replayDetailSubtitle: '查看完整牌局回放、事件时间线，以及争议排查所需的元数据。',
        replayBackToTable: '返回牌桌',
        copyDisputePayload: '复制争议载荷',
        exportHandEvidence: '导出签名证据包',
        replayArtifactCopied: '争议载荷已复制。',
        replayArtifactExported: '签名证据包已导出。',
        replayArtifactFailed: '证据包操作失败。',
        replayBundleSummary: '签名证据摘要',
        replayBundleExportedAt: '导出时间',
        replayBundleKeyId: '签名键标识',
        replayBundleDigest: '载荷摘要',
        replaySummary: '回放摘要',
        replayTimeline: '事件时间线',
        replayParticipants: '参与者',
        replayStake: '投入',
        replayPayout: '结算',
        replayRake: '抽水',
        replayStartedAt: '开始时间',
        replaySettledAt: '结算时间',
        replayDispute: '争议详情',
        replayRoundId: '回合编号',
        replayReferenceId: '牌局记录号',
        replayEventCount: '事件数',
        replaySupportHint: '审计或争议排查时，请使用回合编号、记录号和公平性提交值。',
        stagePreflop: '翻牌前',
        stageFlop: '翻牌',
        stageTurn: '转牌',
        stageRiver: '河牌',
        stageShowdown: '摊牌',
        eventHandStarted: '牌局开始',
        eventCardsDealt: '发出底牌',
        eventSmallBlindPosted: '小盲已下',
        eventBigBlindPosted: '大盲已下',
        eventTurnStarted: '轮到行动',
        eventTurnTimedOut: '行动超时',
        eventPlayerActed: '玩家行动',
        eventBoardRevealed: '翻开公共牌',
        eventFairnessRevealed: '公开公平性种子',
        eventShowdownResolved: '摊牌结算',
        eventHandWonByFold: '弃牌获胜',
        eventHandSettled: '牌局完成结算',
        openSeat: '空位',
        you: '你',
        dealer: '庄位',
        smallBlind: '小盲',
        bigBlind: '大盲',
        turn: '行动中',
        fold: '弃牌',
        check: '过牌',
        call: '跟注',
        bet: '下注',
        raise: '加注',
        allIn: '全下',
        amountHint: '下注和加注输入的是本街你希望累计投入的总额，而不是增量。',
        waitingStatus: '等待中',
        sittingOutStatus: '暂离',
        activeStatus: '进行中',
        realtimeConnecting: '正在连接牌桌实时通道...',
        realtimeLive: '牌桌实时通道已连接。',
        realtimeReconnecting: '牌桌实时通道重连中...',
        realtimeResyncing: '已重新连接，正在同步权威桌面状态...',
      },
      blackjack: {
        routeTitle: '二十一点路由',
        routeSubtitle: '二十一点现在把 AI 智能荷官接到同一张桌上，底层仍然复用共享钱包、公平性和奖池后端。',
        summaryBalance: '余额',
        summaryFairnessEpoch: '公平性 Epoch',
        summaryLoading: '加载中',
        sectionTitle: '二十一点',
        sectionSubtitle:
          '直接复用 Web 同一套 `GET /blackjack`、`POST /blackjack/start` 与 `POST /blackjack/:id/action` 接口。',
        metaStakeRange: '下注范围',
        metaNaturalPayout: '天生二十一点赔付',
        metaDealer: '庄家规则',
        metaDouble: '加倍',
        metaSplitAces: '拆 A',
        metaHitSplitAces: '拆 A 后要牌',
        metaResplit: '重复分牌',
        metaMaxSplitHands: '最大分牌手数',
        metaTenValueSplit: '10-value 等价分牌',
        dealerHitsSoft17: '软 17 要牌',
        dealerStandAll17: '所有 17 点停牌',
        doubleEnabled: '已启用',
        doubleDisabled: '未启用',
        stakeAmount: '下注金额',
        stakeHint: (min: string, max: string) =>
          `请输入 ${min} 到 ${max} 之间的下注金额，然后每次只开一手牌。`,
        startHand: '开始发牌',
        dealing: '发牌中...',
        refreshHand: '刷新牌局',
        refreshingHand: '刷新中...',
        noActiveHand: '当前没有进行中的牌局，下一次开始会发出新的一手牌。',
        tableTitle: '同桌席位',
        tableId: '桌号',
        seat: '座位',
        aiDealer: 'AI 智能荷官',
        you: '你',
        dealerHand: '庄家',
        playerHand: '玩家',
        visible: '可见点数',
        total: '总点数',
        settling: '结算中...',
        hit: '要牌',
        stand: '停牌',
        double: '加倍',
        split: '分牌',
        hand: '手牌',
        currentBet: '当前下注',
        activeHand: '当前手',
        waitingHand: '待处理',
        stoodHand: '已停牌',
        bustHand: '爆牌',
        winHand: '获胜',
        loseHand: '输牌',
        pushHand: '平局',
        recentHands: '最近牌局',
        noRecentHands: '当前还没有已结算的二十一点牌局。',
        loadingState: '正在刷新二十一点状态...',
      },
    } satisfies Record<RouteScreenKey, Record<string, unknown>>,
  },
} as const;

export type MobileRouteCopy = (typeof routeCopy)[keyof typeof routeCopy];
export type MobileRouteLabels = MobileRouteCopy['labels'];
export type MobileRouteCards = MobileRouteCopy['cards'];
export type MobileRouteHeroes = MobileRouteCopy['heroes'];
export type MobileRouteScreens = MobileRouteCopy['screens'];

export function getMobileRouteCopy(locale: MobileFairnessLocale) {
  return routeCopy[locale];
}
