import type { MobileFairnessLocale } from './fairness';

export type MobileRouteKey =
  | 'home'
  | 'account'
  | 'wallet'
  | 'rewards'
  | 'community'
  | 'security'
  | 'notifications'
  | 'gacha'
  | 'quickEight'
  | 'predictionMarket'
  | 'holdem'
  | 'blackjack'
  | 'fairness';

export type HomeMenuRouteKey = Exclude<MobileRouteKey, 'home'>;

type RouteCardKey = HomeMenuRouteKey;
type RouteHeroKey = HomeMenuRouteKey;
type RouteScreenKey =
  | 'gacha'
  | 'quickEight'
  | 'predictionMarket'
  | 'holdem'
  | 'blackjack';

export const homeMenuRouteOrder = [
  'account',
  'wallet',
  'rewards',
  'community',
  'notifications',
  'security',
  'gacha',
  'quickEight',
  'predictionMarket',
  'holdem',
  'blackjack',
  'fairness',
] as const satisfies readonly HomeMenuRouteKey[];

const routeCopy = {
  en: {
    labels: {
      home: 'Home',
      account: 'Profile',
      wallet: 'Wallet',
      rewards: 'Rewards',
      community: 'Community',
      security: 'Security',
      notifications: 'Notifications',
      gacha: 'Slot',
      quickEight: 'Quick Eight',
      predictionMarket: 'Markets',
      holdem: "Hold'em",
      blackjack: 'Blackjack',
      fairness: 'Fairness',
    } satisfies Record<MobileRouteKey, string>,
    homeTickerLabel: 'Latest',
    homeFeaturedLabel: 'Featured mode',
    homeMoreTitle: 'More routes',
    homeMoreSubtitle:
      'Wallet, rewards, community, security, notifications, and fairness stay on their own dedicated screens.',
    homeSectionTitle: 'Quick entry',
    homeSectionSubtitle:
      'Open the fastest play routes first, then jump into the rest of the app below.',
    currentRouteTitle: (label: string) => `Route: ${label}`,
    currentRouteSubtitle:
      'This route owns its own workflow instead of rendering back into the home dashboard.',
    currentRouteHint:
      'Home is only a launcher now. Account, wallet, rewards, security, and every game stay on their own screens.',
    cards: {
      account: {
        title: 'Profile',
        body:
          'Verification, wallet links, session refresh, and sign-out controls live on a dedicated player profile page.',
        open: 'Open profile',
      },
      wallet: {
        title: 'Wallet',
        body:
          'Keep balances, gifting, store inventory, and payout operations on a dedicated wallet route.',
        open: 'Open wallet',
      },
      rewards: {
        title: 'Rewards',
        body:
          'Streaks, live missions, and claimable bonus rewards now live on a dedicated rewards board.',
        open: 'Open rewards',
      },
      community: {
        title: 'Community',
        body:
          'Browse visible threads, open a discussion, and reply from a dedicated mobile community route.',
        open: 'Open community',
      },
      security: {
        title: 'Security',
        body:
          'Password reset, active session review, and device revocation are split into a dedicated security page.',
        open: 'Open security',
      },
      notifications: {
        title: 'Notifications',
        body:
          'KYC reviews, withdrawal progress, and settled market updates now land in a dedicated inbox route.',
        open: 'Open notifications',
      },
      gacha: {
        title: 'Slot machine',
        body:
          'Three-reel presentation, pity progress, and committed draw settlement now live on a standalone route.',
        open: 'Open slot machine',
      },
      quickEight: {
        title: 'Quick Eight',
        body:
          'Build an eight-number ticket, set the stake, and watch the draw reveal one ball at a time.',
        open: 'Open Quick Eight',
      },
      predictionMarket: {
        title: 'Prediction market',
        body:
          'Browse open and settled markets, inspect pooled outcomes, place positions, and review your holdings on a dedicated route.',
        open: 'Open markets',
      },
      holdem: {
        title: "Texas Hold'em",
        body:
          'Create or join multiplayer casual or cash tables, choose the seat count, and play each street on its own mobile route.',
        open: "Open Hold'em",
      },
      blackjack: {
        title: 'Blackjack',
        body:
          'Player-vs-dealer blackjack with hit, stand, double, split, and shared fairness controls.',
        open: 'Open Blackjack',
      },
      fairness: {
        title: 'Fairness verifier',
        body:
          'Reveal a closed epoch and prove locally that SHA-256(seed) matches the published commit hash.',
        open: 'Open fairness verifier',
      },
    } satisfies Record<RouteCardKey, { title: string; body: string; open: string }>,
    heroes: {
      account: {
        kicker: 'Profile',
        title: 'Dedicated profile route for session, identity, and wallet entry points.',
        subtitle:
          'Mobile keeps profile readiness, wallet links, session refresh, and sign-out actions on their own screen instead of in the route launcher.',
      },
      wallet: {
        kicker: 'Wallet',
        title: 'Dedicated wallet route for treasury and payout operations.',
        subtitle:
          'Mobile gives wallet balances, store inventory, gifting, and cashier actions their own route so treasury work stays separate from gameplay.',
      },
      rewards: {
        kicker: 'Rewards',
        title: 'Rewards now live on their own mission board.',
        subtitle:
          'Track streaks, pinned missions, and claimable bonus drops on a dedicated rewards screen.',
      },
      community: {
        kicker: 'Community',
        title: 'Dedicated route for public discussion and replies.',
        subtitle:
          'Mobile keeps visible threads, posting, and moderation-aware reply flow on a standalone community screen.',
      },
      security: {
        kicker: 'Security',
        title: 'Dedicated security route for device and password controls.',
        subtitle:
          'Mobile keeps active-session review, password reset, and revoke flows on a dedicated security screen.',
      },
      notifications: {
        kicker: 'Notifications',
        title: 'Dedicated inbox route for account and market alerts.',
        subtitle:
          'Mobile keeps KYC reviews, withdrawal progress, and settled prediction market updates in one read-tracked feed.',
      },
      gacha: {
        kicker: 'Gacha',
        title: 'Dedicated reward-capsule route for live pulls.',
        subtitle:
          'Mobile keeps the capsule stage, featured drops, and provably fair draw settlement on a standalone screen.',
      },
      quickEight: {
        kicker: 'Quick Eight',
        title: 'Quick Eight lives on its own draw board.',
        subtitle:
          'Build the ticket, lock the stake, and follow each reveal on a dedicated mobile play screen.',
      },
      predictionMarket: {
        kicker: 'Markets',
        title: 'Dedicated route for prediction market flow.',
        subtitle:
          'Mobile keeps open, locked, and settled markets on a standalone screen where you can browse pools, place positions, and review outcomes.',
      },
      holdem: {
        kicker: "Hold'em",
        title: 'Dedicated route for multiplayer casual and cash-table hands.',
        subtitle:
          'Mobile keeps the lobby, table mode, seat count, buy-in, and street-by-street table actions on a standalone route that polls the same backend table state as web.',
      },
      blackjack: {
        kicker: 'Blackjack',
        title: 'Dedicated route for player-vs-dealer hands.',
        subtitle:
          'Mobile runs blackjack on its own route, using the same backend fairness, wallet settlement, and split flow as web.',
      },
      fairness: {
        kicker: 'Fairness',
        title: 'Dedicated route for commit-reveal verification.',
        subtitle:
          'Mobile keeps fairness validation off the home dashboard and lets you reveal a closed epoch on its own screen.',
      },
    } satisfies Record<RouteHeroKey, { kicker: string; title: string; subtitle: string }>,
    screens: {
      gacha: {
        routeTitle: 'Prize capsule',
        routeSubtitle:
          'Open live reward capsules, review featured drops, and keep each pull on its own route.',
        summaryBalance: 'Balance',
        summarySecondary: 'Featured drops',
        summarySecondaryLoading: 'Loading',
        summarySecondaryValue: (featuredCount: number) => `${featuredCount} live`,
        sectionTitle: 'Draw stage',
        sectionSubtitle:
          'Pick a play mode, fire a pull, and review the latest settled results without leaving this screen.',
        metaCostPerPull: 'Cost per pull',
        metaPity: 'Pity',
        metaFairness: 'Fairness',
        epochLabel: 'Epoch',
        costPillLabel: '1 Draw =',
        rewardLabel: 'Reward',
        stockLabel: 'Stock',
        winCountSummary: (count: number) => `${count} wins`,
        pityBoostActive: 'Boost active',
        pityDisabled: 'Disabled',
        pityPullsToBoost: (draws: number) => `${draws} pulls to boost`,
        slotRevealTitle: 'Prize capsule',
        slotToneSpinningBatch: (count: number) => `Drawing ${count} times...`,
        slotToneSpinningSingle: 'Drawing the capsule...',
        slotToneWin: 'Winning capsule locked.',
        slotToneBlocked: 'Result blocked by inventory or payout control.',
        slotToneSettled: 'Finale settled. Review the latest reveal below.',
        slotToneReady: 'Ready for the first pull.',
        slotLandingBannerLabel: 'Featured jackpot',
        slotLandingMarquee: 'Mega spin',
        slotLandingTitle: 'Lucky slots',
        slotLandingBody:
          'A dedicated three-reel cabinet for fast capsule pulls, batch runs, and live rarity tracking.',
        slotLandingFeaturedLabel: 'Live drops',
        slotLandingBatchLabel: 'Batch',
        slotLandingModeLabel: 'Mode',
        slotHintAnimating: 'The stage locks each reel as the live draw settles.',
        slotHintSettled:
          'The center line settles on the highlighted outcome after the draw finishes.',
        pullOnce: 'Draw now',
        pullMany: (count: number) => `Draw ${count}`,
        pulling: 'Drawing...',
        refreshBanner: 'Refresh drops',
        disabledBySystem: 'Draws are currently disabled by system config.',
        multiLocked: (max: number) =>
          `Multi-draw is locked because \`draw_system.max_draw_per_request\` is currently ${max}.`,
        loadingBanner: 'Loading the live capsule stage...',
        loadingPlay: (count: number) =>
          count > 1 ? `Settling ${count} pulls...` : 'Settling your pull...',
        noActivePrizes: 'No featured drops are live yet.',
        latestSinglePull: 'Latest pull',
        latestBatchPull: (count: number) => `Latest ${count} pulls`,
        highlight: 'Top hit',
        revealKicker: 'Prize reveal',
        revealOutcomeLabel: 'Outcome',
        revealWinTitle: (rarity: string) => `${rarity} pull!`,
        revealProtectedTitle: 'Settlement protected',
        revealMissTitle: 'No featured hit',
        revealWinBody: (name: string) =>
          `${name} landed as the top hit from the latest settled capsule run.`,
        revealProtectedBody:
          'The candidate reward was blocked by stock or payout controls, so this pull settled safely without releasing that item.',
        revealMissBody:
          'This pull settled without a featured reward, but the pity track and fairness record still advanced.',
        revealSettledCount: (count: number) =>
          count > 1 ? `${count} capsules settled` : '1 capsule settled',
        revealVerifyAction: 'Verify fairness',
        revealReplaySingle: 'Draw again',
        revealReplayMany: (count: number) => `Draw ${count} more`,
        bigWinTitle: 'Mega win!',
        bigWinBody: (name: string) =>
          `${name} pushed this capsule run into a premium payout moment.`,
        bigWinRewardLabel: 'You won',
        bigWinPrimaryAction: 'View wallet',
        bigWinSecondaryAction: 'Spin again',
        bigWinDismissAction: 'Close',
        noFeaturedReward: 'No featured reward',
        noPullYet: 'No pulls yet. Hit Draw now to reveal the first capsule.',
      },
      quickEight: {
        routeTitle: 'Quick Eight',
        routeSubtitle:
          'Build an eight-number ticket, lock the stake, and watch the draw settle in sequence.',
        summaryBalance: 'Balance',
        summarySelection: 'Selection',
        routeHint: (pickCount: number, boardSize: number, drawCount: number) =>
          `Pick exactly ${pickCount} numbers from 1 to ${boardSize}. Once the ticket is full, the draw reveals ${drawCount} numbers and settles instantly.`,
        sectionTitle: 'Ticket board',
        sectionSubtitle:
          'Lock your eight picks, review the payout ladder, and keep the latest reveal in view.',
        selectionTitle: 'Your numbers',
        selectionLocked: 'Selection locked',
        selectionLeft: (remaining: number) => `${remaining} left`,
        noSelection: 'No numbers selected yet.',
        numberBoardTitle: 'Number board',
        payoutTableTitle: 'Payout ladder',
        payoutRuleLabel: (hits: number) => `${hits} hits`,
        statusLabel: 'Round status',
        multiplierLabel: 'Multiplier',
        hitCountLabel: 'Hits',
        clear: 'Clear',
        stakeAmount: 'Stake amount',
        stakeRange: (min: string, max: string) => `Min ${min} / Max ${max}`,
        play: 'Play Quick Eight',
        drawing: 'Drawing...',
        loadingRequest: 'Settling your Quick Eight ticket...',
        latestRound: 'Latest round',
        payout: 'Payout',
        drawnNumbers: (visible: number, total: number) => `Drawn numbers ${visible}/${total}`,
        matchedNumbers: 'Matched numbers',
        noMatches: 'No matches this round.',
        noRoundYet: 'No round yet. Fill the ticket, set the stake, and start the draw.',
        howToPlayTitle: 'How to play',
        howToPlaySubtitle:
          'A quick guide to filling the ticket, reading the ladder, and verifying each result.',
        howToPlayStepOneTitle: 'Build your ticket',
        howToPlayStepOneBody:
          'Pick exactly eight unique numbers from the 1 to 80 board. Once the eighth slot is filled, the ticket locks in.',
        howToPlayStepTwoTitle: 'Set stake and launch',
        howToPlayStepTwoBody:
          'Choose any stake within the allowed range, then start the round to reveal all 20 draw numbers in sequence.',
        howToPlayStepThreeTitle: 'Read hits and payout',
        howToPlayStepThreeBody:
          'Your payout uses the hit ladder below. Four hits start paying, and eight hits lands the top multiplier.',
        howToPlayMaxWin: 'Max win',
        howToPlayBoard: 'Board',
        howToPlayDraws: 'Numbers drawn',
        howToPlayFairnessTitle: 'Provably fair draw',
        howToPlayFairnessBody:
          'Each Quick Eight round carries a commit-reveal fairness record so the draw order and result stay verifiable after settlement.',
      },
      predictionMarket: {
        routeTitle: 'Predictions',
        routeSubtitle:
          'Browse live boards, back an outcome, and track how each market settles.',
        summaryBalance: 'Balance',
        summaryActiveMarket: 'Featured market',
        summaryHoldings: 'Tickets',
        summaryLoading: 'Loading',
        summaryEmpty: 'None',
        sectionTitle: 'Live boards',
        sectionSubtitle:
          'Featured markets, outcome pools, and stake controls stay on one mobile screen.',
        refreshMarkets: 'Refresh markets',
        refreshingMarkets: 'Refreshing...',
        marketListTitle: 'Featured markets',
        marketDetailTitle: 'Market board',
        myHoldingsTitle: 'Your prediction tickets',
        myHoldingsSubtitle:
          'Grouped by market so open exposure, settled payouts, and refunds stay easy to review.',
        exposureOnlyTitle: 'Exposure only',
        exposureOnlyDescription:
          'The current pari-mutuel release shows stake exposure, net-of-vig settled payouts, and refunds. It does not calculate live PnL while markets are still open.',
        refreshHistory: 'Refresh history',
        loadingHistory: 'Loading history...',
        noMarkets: 'No prediction markets are configured yet.',
        noMarketSelected:
          'Select a market above to inspect pools, timing, and bet controls.',
        noDescription: 'No market description provided.',
        marketStatus: 'Market status',
        positionStatus: 'Position status',
        settlementStatus: 'Settlement',
        totalPool: 'Total pool',
        openPositions: 'Open positions',
        yourPositions: 'Your positions',
        yourExposure: 'Your exposure',
        winningOutcome: 'Winning outcome',
        mechanism: 'Mechanism',
        opensAt: 'Opens',
        locksAt: 'Locks',
        resolvesAt: 'Resolves',
        resolvedAt: 'Resolved',
        lastUpdated: 'Updated',
        selectOutcome: 'Select outcome',
        selectedOutcome: 'Selected outcome',
        chooseOutcome: 'Choose an outcome first.',
        stakeAmount: 'Stake amount',
        stakeHint:
          'Enter a positive amount. Payout is pari-mutuel, net of vig, and finalizes only after market resolution.',
        placeBet: 'Predict now',
        placingBet: 'Placing...',
        marketClosed: 'This market is not accepting new positions.',
        outcomePool: (stake: string, count: number, share: string) =>
          `${stake} pooled · ${count} positions · ${share}`,
        winningPool: (stake: string) => `${stake} winning pool`,
        positionPlacedAt: 'Placed',
        positionSettledAt: 'Settled',
        potentialPayout: 'Payout',
        noPositions: 'No positions on this market yet.',
        noHoldings: 'You have not opened any prediction market positions yet.',
        noFilteredHoldings: 'No grouped history matches this filter yet.',
        noOutcomePools: 'No pool activity yet.',
        marketCountLabel: 'Markets',
        positionCountLabel: 'Positions',
        totalStake: 'Total stake',
        openExposure: 'Open exposure',
        settledPayout: 'Settled payout',
        refundedAmount: 'Refunded amount',
        lastActivity: 'Last activity',
        roundKey: 'Round',
        focusMarket: 'Open market',
        previousPage: 'Previous page',
        nextPage: 'Next page',
        portfolioPageValue: (page: number) => `Page ${page}`,
        portfolioFilterLabels: {
          all: 'All',
          open: 'Open',
          resolved: 'Resolved',
          refunded: 'Refunded',
        },
        portfolioStatusLabels: {
          open: 'Open',
          resolved: 'Resolved',
          refunded: 'Refunded',
        },
        marketStatusLabels: {
          draft: 'Draft',
          open: 'Open',
          locked: 'Locked',
          resolved: 'Resolved',
          cancelled: 'Cancelled',
        },
        positionStatusLabels: {
          open: 'Open',
          won: 'Won',
          lost: 'Lost',
          sold: 'Sold',
          refunded: 'Refunded',
        },
        settlementPending: 'Pending resolution',
        settlementResolved: 'Resolved',
        settlementCancelled: 'Cancelled',
        winningOutcomePending: 'Pending',
        mechanismPariMutuel: 'Pari-mutuel',
        outcomeWinner: 'Winner',
      },
      holdem: {
        routeTitle: "Hold'em table",
        routeSubtitle:
          'Move from the lobby into live hands, table chat, and replay review without leaving this mobile screen.',
        summaryBalance: 'Balance',
        summaryStatus: 'Table status',
        summaryLoading: 'Loading',
        sectionTitle: "Table stage",
        sectionSubtitle:
          'Open a table, follow the live board, and act street by street with fairness status and replay history in view.',
        tableMode: 'Table mode',
        tableName: 'Table name',
        seatCount: 'Seats',
        buyInAmount: 'Buy-in amount',
        tournamentStartingStack: 'Starting stack',
        tournamentPayoutPlaces: 'Payout places',
        buyInRange: (min: string, max: string) => `Min ${min} / Max ${max}`,
        effectiveBuyInPreview: (amount: string) => `Effective buy-in ${amount}`,
        casualTableHint:
          'Casual tables use bonus balance, do not charge rake, and do not require KYC.',
        cashTableHint: 'Cash tables use withdrawable balance and the live rake policy.',
        tournamentTableHint:
          'Tournament tables freeze buy-ins into a pooled prize pool, seat every entry with the same starting stack, and only settle prizes after elimination order is final.',
        tournamentPayoutPlacesHint:
          'Final payout slots are capped to the actual registration count, up to three places.',
        createTable: 'Create table',
        creatingTable: 'Opening...',
        joinTable: 'Join table',
        joiningTable: 'Buying in...',
        leaveTable: 'Leave table',
        leavingTable: 'Cashing out...',
        sitOutTable: 'Sit out',
        sittingOutTable: 'Sitting out...',
        sitInTable: 'Sit back in',
        sittingInTable: 'Returning...',
        startHand: 'Start hand',
        startingHand: 'Shuffling...',
        refreshTable: 'Refresh table',
        refreshingTable: 'Refreshing...',
        noTables: 'No tables are open yet.',
        noSelection: 'Choose a table from the lobby to view the current hand.',
        board: 'Board',
        actionClock: 'Action clock',
        currentBet: 'Current bet',
        toCall: 'To call',
        minRaiseTo: 'Min raise to',
        actionAmount: 'Action amount',
        blinds: 'Blinds',
        tableType: 'Table type',
        cashTable: 'Cash',
        casualTable: 'Casual',
        tournamentTable: 'Tournament',
        rakePolicy: 'Rake',
        rakeCap: 'cap',
        rakeNone: 'No rake',
        rakeNoFlopNoDrop: 'No flop, no drop',
        fairness: 'Fairness',
        timeBank: 'Time bank',
        stack: 'Stack',
        streetCommitted: 'Street',
        totalCommitted: 'Total',
        mainPot: 'Main pot',
        sidePot: 'Side pot',
        winners: 'Winners',
        hand: 'Hand',
        tableChat: 'Table chat',
        tableChatEmpty: 'No table chat yet. Seat in and break the silence.',
        tableChatPlaceholder: 'Type a table message',
        tableChatSend: 'Send',
        tableChatSending: 'Sending...',
        tableChatReactions: 'Reactions',
        tableChatSeatOnly: 'Only seated players can chat or send table reactions.',
        recentHands: 'Recent hands',
        noRecentHands: 'No settled hands yet.',
        viewReplay: 'Open replay',
        hideReplay: 'Hide replay',
        replayLoading: 'Loading hand replay...',
        replayFailed: 'Failed to load this hand replay.',
        replayDetailTitle: "Hold'em replay detail",
        replayDetailSubtitle:
          'Full hand replay, event timeline, and dispute metadata for the selected settled hand.',
        replayBackToTable: 'Back to table',
        copyDisputePayload: 'Copy dispute payload',
        exportHandEvidence: 'Export signed evidence bundle',
        replayArtifactCopied: 'Dispute payload copied.',
        replayArtifactExported: 'Signed evidence bundle exported.',
        replayArtifactFailed: 'Evidence bundle action failed.',
        replayBundleSummary: 'Signed bundle summary',
        replayBundleExportedAt: 'Exported',
        replayBundleKeyId: 'Key id',
        replayBundleDigest: 'Payload digest',
        replaySummary: 'Replay summary',
        replayTimeline: 'Event timeline',
        replayParticipants: 'Participants',
        replayStake: 'Stake',
        replayPayout: 'Payout',
        replayRake: 'Rake',
        replayStartedAt: 'Started',
        replaySettledAt: 'Settled',
        replayDispute: 'Dispute detail',
        replayRoundId: 'Round id',
        replayReferenceId: 'Reference id',
        replayEventCount: 'Events',
        replaySupportHint:
          'Use the round id, reference id, and fairness commit for audit or dispute review.',
        stagePreflop: 'Preflop',
        stageFlop: 'Flop',
        stageTurn: 'Turn',
        stageRiver: 'River',
        stageShowdown: 'Showdown',
        eventHandStarted: 'Hand started',
        eventCardsDealt: 'Hole cards dealt',
        eventSmallBlindPosted: 'Small blind posted',
        eventBigBlindPosted: 'Big blind posted',
        eventTurnStarted: 'Turn started',
        eventTurnTimedOut: 'Turn timed out',
        eventPlayerActed: 'Player acted',
        eventBoardRevealed: 'Board revealed',
        eventFairnessRevealed: 'Fairness revealed',
        eventShowdownResolved: 'Showdown resolved',
        eventHandWonByFold: 'Won by fold',
        eventHandSettled: 'Hand settled',
        openSeat: 'Open seat',
        you: 'You',
        dealer: 'Dealer',
        smallBlind: 'SB',
        bigBlind: 'BB',
        turn: 'Turn',
        fold: 'Fold',
        check: 'Check',
        call: 'Call',
        bet: 'Bet',
        raise: 'Raise',
        allIn: 'All-in',
        amountHint:
          'Bet and raise amounts use the total chips you want committed on this street.',
        waitingStatus: 'Waiting',
        sittingOutStatus: 'Sitting out',
        activeStatus: 'Active',
        realtimeConnecting: 'Connecting live table feed...',
        realtimeLive: 'Live table feed active.',
        realtimeReconnecting: 'Reconnecting live table feed...',
        realtimeResyncing: 'Reconnected. Syncing authoritative table state...',
      },
      blackjack: {
        routeTitle: 'Blackjack table',
        routeSubtitle:
          'Keep the dealer, live hand state, fairness, and recent results on one dedicated mobile table screen.',
        summaryBalance: 'Balance',
        summaryFairnessEpoch: 'Fairness epoch',
        summaryLoading: 'Loading',
        sectionTitle: 'Table stage',
        sectionSubtitle:
          'Open a hand, read the dealer board, and act from one focused play surface.',
        stakeLabel: 'Stake',
        payoutLabel: 'Payout',
        metaStakeRange: 'Stake range',
        metaNaturalPayout: 'Natural payout',
        metaDealer: 'Dealer',
        metaDouble: 'Double',
        metaSplitAces: 'Split aces',
        metaHitSplitAces: 'Hit split aces',
        metaResplit: 'Re-split',
        metaMaxSplitHands: 'Max split hands',
        metaTenValueSplit: '10-value split',
        dealerHitsSoft17: 'Hit soft 17',
        dealerStandAll17: 'Stand on all 17s',
        doubleEnabled: 'Enabled',
        doubleDisabled: 'Disabled',
        stakeAmount: 'Stake amount',
        stakeHint: (min: string, max: string) =>
          `Enter a stake between ${min} and ${max}, then open one active hand at a time.`,
        effectiveStakePreview: (stake: string) => `Total stake ${stake}`,
        startHand: 'Start hand',
        dealing: 'Dealing...',
        refreshHand: 'Refresh hand',
        refreshingHand: 'Refreshing...',
        noActiveHand: 'No active hand. The next start request will deal a fresh round.',
        tableTitle: 'Same-table seating',
        tableId: 'Table',
        seat: 'Seat',
        aiDealer: 'AI dealer',
        you: 'You',
        dealerHand: 'Dealer',
        playerHand: 'Player',
        visible: 'Visible',
        total: 'Total',
        settling: 'Settling...',
        hit: 'Hit',
        stand: 'Stand',
        double: 'Double',
        split: 'Split',
        hand: 'Hand',
        currentBet: 'Bet',
        activeHand: 'Active',
        waitingHand: 'Waiting',
        stoodHand: 'Standing',
        bustHand: 'Bust',
        winHand: 'Win',
        loseHand: 'Lose',
        pushHand: 'Push',
        recentHands: 'Recent hands',
        noRecentHands: 'No completed blackjack hands yet.',
        loadingState: 'Refreshing blackjack state...',
      },
    } satisfies Record<RouteScreenKey, Record<string, unknown>>,
  },
  'zh-CN': {
    labels: {
      home: '首页',
      account: '资料',
      wallet: '钱包',
      rewards: '奖励',
      community: '社区',
      security: '安全',
      notifications: '通知',
      gacha: '老虎机',
      quickEight: '快八',
      predictionMarket: '预测盘',
      holdem: '德州',
      blackjack: '二十一点',
      fairness: '公平性',
    } satisfies Record<MobileRouteKey, string>,
    homeTickerLabel: '最新',
    homeFeaturedLabel: '推荐玩法',
    homeMoreTitle: '更多路由',
    homeMoreSubtitle:
      '钱包、奖励、社区、安全、通知和公平验证都保持为各自独立页面。',
    homeSectionTitle: '快捷入口',
    homeSectionSubtitle:
      '先进入最常玩的模式，再从下面跳到应用里的其他独立页面。',
    currentRouteTitle: (label: string) => `当前路由：${label}`,
    currentRouteSubtitle: '当前能力在自己的独立页面里运行，不再塞回首页仪表盘。',
    currentRouteHint:
      '首页现在只是入口页，账户、钱包、奖励、安全，以及各个玩法都走各自页面。',
    cards: {
      account: {
        title: '资料',
        body:
          '验证状态、钱包入口、会话刷新和退出登录动作都放到独立资料页。',
        open: '打开资料页',
      },
      wallet: {
        title: '钱包',
        body:
          '把余额、送礼、商店库存和出款操作统一放进独立的钱包页。',
        open: '打开钱包页',
      },
      rewards: {
        title: '奖励',
        body:
          '签到连击、进行中的任务和可领取奖励都集中到了独立奖励看板里。',
        open: '打开奖励页',
      },
      community: {
        title: '社区',
        body:
          '浏览可见主题、发起讨论，并在独立移动端社区页里完成公开回复。',
        open: '打开社区页',
      },
      security: {
        title: '安全',
        body:
          '重置密码、查看活跃会话和撤销设备会话都拆到独立安全页。',
        open: '打开安全页',
      },
      notifications: {
        title: '通知中心',
        body:
          'KYC 审核、提现进度和预测市场结算统一进入专门的通知收件箱。',
        open: '打开通知中心',
      },
      gacha: {
        title: '老虎机',
        body:
          '三轴演出、保底进度和真实抽奖结算都拆到独立路由里，不再放在首页。',
        open: '打开老虎机页面',
      },
      quickEight: {
        title: '快八',
        body:
          '选满 8 个号码、设好下注金额，再看开奖号码逐个揭晓。',
        open: '打开快八页',
      },
      predictionMarket: {
        title: '预测盘',
        body:
          '浏览可下注和已结算的市场，查看各结果奖池、下注并统一回看自己的持仓状态。',
        open: '打开预测盘',
      },
      holdem: {
        title: '德州扑克',
        body:
          '创建或加入多人娱乐局或现金桌，选择人数后入桌，并按 preflop / flop / turn / river 依次推进。',
        open: '打开德州牌桌',
      },
      blackjack: {
        title: '二十一点',
        body:
          '支持分牌的经典庄闲二十一点，与共享 fairness 控制、钱包结算一起放到独立页面。',
        open: '打开二十一点页',
      },
      fairness: {
        title: '公平性验证器',
        body:
          'Reveal 已结束的 epoch，并在本地证明 `SHA-256(seed)` 与已公布的 commit 哈希一致。',
        open: '打开公平性验证页',
      },
    } satisfies Record<RouteCardKey, { title: string; body: string; open: string }>,
    heroes: {
      account: {
        kicker: '资料',
        title: '会话、身份和钱包入口的独立资料路由。',
        subtitle:
          '移动端把资料状态、钱包入口、会话刷新和退出登录动作拆到独立页面，不再放在入口页里。',
      },
      wallet: {
        kicker: '钱包',
        title: '金库与出款操作的独立钱包路由。',
        subtitle:
          '移动端给钱包单独一页，把资产查看、商店、送礼和 cashier 操作和玩法彻底分开。',
      },
      rewards: {
        kicker: '奖励',
        title: '奖励现在拥有自己的任务看板。',
        subtitle:
          '把签到连击、主推任务和可领取奖励都留在同一张独立页面里。',
      },
      community: {
        kicker: '社区',
        title: '公开讨论与回帖的独立社区路由。',
        subtitle:
          '移动端把可见主题、发帖动作和带审核策略的回复流程集中到独立社区页面。',
      },
      security: {
        kicker: '安全',
        title: '设备与密码操作的独立安全路由。',
        subtitle:
          '移动端把活跃会话审查、密码重置和会话撤销都放到专门的安全页里。',
      },
      notifications: {
        kicker: '通知',
        title: '账户与市场提醒的独立通知路由。',
        subtitle:
          '移动端把 KYC、提现和预测市场结算提醒集中到一个可读、可清空的通知页里。',
      },
      gacha: {
        kicker: 'Gacha',
        title: '独立的奖励胶囊抽取路由。',
        subtitle:
          '移动端把胶囊舞台、主推掉落和可验证公平的抽奖结算放在同一张独立页面里。',
      },
      quickEight: {
        kicker: '快八',
        title: '快八拥有自己的开奖票面。',
        subtitle:
          '选票、下注和逐步揭晓都留在同一张独立移动端页面里完成。',
      },
      predictionMarket: {
        kicker: '预测盘',
        title: '独立的预测市场路由。',
        subtitle:
          '移动端把开放中、封盘中和已结算的市场集中到一个独立页面里，支持浏览奖池、下注和查看持仓结果。',
      },
      holdem: {
        kicker: '德州',
        title: '独立的多人娱乐局与现金桌路由。',
        subtitle:
          '移动端把牌桌大厅、桌型、人数、买入和每条街的行动都放到独立页面里，继续轮询和 Web 相同的后端桌局状态。',
      },
      blackjack: {
        kicker: '二十一点',
        title: '独立的庄闲牌局路由。',
        subtitle:
          '移动端把二十一点单独放到一个页面里，继续复用与 Web 相同的 fairness、钱包结算和分牌流程。',
      },
      fairness: {
        kicker: '公平性',
        title: '独立的 commit-reveal 验证路由。',
        subtitle:
          '移动端把公平性验证从首页拆开，单独放到一个页面里，专门用来 reveal 已结束的 epoch 并做本地校验。',
      },
    } satisfies Record<RouteHeroKey, { kicker: string; title: string; subtitle: string }>,
    screens: {
      gacha: {
        routeTitle: '奖励胶囊',
        routeSubtitle: '在独立页面里开出实时奖励、查看主推掉落，并保留每一次抽取结果。',
        summaryBalance: '余额',
        summarySecondary: '主推掉落',
        summarySecondaryLoading: '加载中',
        summarySecondaryValue: (featuredCount: number) => `${featuredCount} 个在线`,
        sectionTitle: '抽奖舞台',
        sectionSubtitle:
          '选择玩法模式，直接开抽，并在同一屏查看最新结算结果。',
        metaCostPerPull: '单抽消耗',
        metaPity: '保底',
        metaFairness: '公平性',
        epochLabel: '轮次',
        costPillLabel: '1 抽 =',
        rewardLabel: '奖励',
        stockLabel: '库存',
        winCountSummary: (count: number) => `${count} 次命中`,
        pityBoostActive: '概率加成中',
        pityDisabled: '未启用',
        pityPullsToBoost: (draws: number) => `还差 ${draws} 抽触发加成`,
        slotRevealTitle: '奖励胶囊',
        slotToneSpinningBatch: (count: number) => `正在开抽 ${count} 次...`,
        slotToneSpinningSingle: '奖励胶囊开启中...',
        slotToneWin: '中奖胶囊已锁定。',
        slotToneBlocked: '结果被库存或赔付控制拦截。',
        slotToneSettled: '本轮已结算，可查看下方最新揭晓结果。',
        slotToneReady: '准备好揭晓第一颗胶囊。',
        slotLandingBannerLabel: '主推大奖',
        slotLandingMarquee: '大奖转轮',
        slotLandingTitle: '幸运转轮',
        slotLandingBody:
          '一个更独立的三转轮落地台，把单抽、批量开抽和稀有度掉落都收在同一张机台里。',
        slotLandingFeaturedLabel: '在线掉落',
        slotLandingBatchLabel: '批量',
        slotLandingModeLabel: '模式',
        slotHintAnimating: '胶囊舞台会随着实时结算逐列锁定。',
        slotHintSettled: '结算结束后，中线会停在本轮高亮结果上。',
        pullOnce: '立即开抽',
        pullMany: (count: number) => `开抽 ${count} 次`,
        pulling: '开抽中...',
        refreshBanner: '刷新奖池',
        disabledBySystem: '系统配置当前已关闭抽奖。',
        multiLocked: (max: number) =>
          `当前 \`draw_system.max_draw_per_request\` 为 ${max}，所以多次开抽仍被锁定。`,
        loadingBanner: '正在加载当前抽奖舞台...',
        loadingPlay: (count: number) =>
          count > 1 ? `正在结算 ${count} 次开抽...` : '正在结算本次开抽...',
        noActivePrizes: '当前还没有上线的主推掉落。',
        latestSinglePull: '最近一次开抽',
        latestBatchPull: (count: number) => `最近 ${count} 次开抽`,
        highlight: '最高奖励',
        revealKicker: '奖励揭晓',
        revealOutcomeLabel: '本轮结果',
        revealWinTitle: (rarity: string) => `${rarity} 奖励命中`,
        revealProtectedTitle: '结果已被保护拦截',
        revealMissTitle: '本轮没有主推命中',
        revealWinBody: (name: string) =>
          `${name} 是这次最新结算里命中的最高奖励。`,
        revealProtectedBody:
          '候选奖励被库存或赔付控制拦截，所以这一抽安全结算，但不会释放该奖励。',
        revealMissBody:
          '这一抽没有命中主推奖励，但保底进度和公平性记录仍然已经推进。',
        revealSettledCount: (count: number) =>
          count > 1 ? `已结算 ${count} 颗胶囊` : '已结算 1 颗胶囊',
        revealVerifyAction: '去验证公平性',
        revealReplaySingle: '再开一抽',
        revealReplayMany: (count: number) => `再开 ${count} 抽`,
        bigWinTitle: '大奖命中',
        bigWinBody: (name: string) =>
          `${name} 把这一轮胶囊抽取推成了一次更高等级的奖励时刻。`,
        bigWinRewardLabel: '本轮奖励',
        bigWinPrimaryAction: '查看钱包',
        bigWinSecondaryAction: '再来一抽',
        bigWinDismissAction: '关闭',
        noFeaturedReward: '没有主推奖励',
        noPullYet: '还没有开抽，点击上方按钮揭晓第一颗奖励胶囊。',
      },
      quickEight: {
        routeTitle: '快八',
        routeSubtitle: '选满 8 个号码，锁定下注，再看这一轮开奖按顺序揭晓。',
        summaryBalance: '余额',
        summarySelection: '选号进度',
        routeHint: (pickCount: number, boardSize: number, drawCount: number) =>
          `请从 1 到 ${boardSize} 中选满 ${pickCount} 个号码。票面锁定后会立即开出 ${drawCount} 个号码并完成结算。`,
        sectionTitle: '选号票面',
        sectionSubtitle: '这一页会同时保留选号、赔率阶梯和最近一轮开奖结果。',
        selectionTitle: '你的号码',
        selectionLocked: '号码已选满',
        selectionLeft: (remaining: number) => `还差 ${remaining} 个`,
        noSelection: '还没有选择任何号码。',
        numberBoardTitle: '选号盘',
        payoutTableTitle: '赔率阶梯',
        payoutRuleLabel: (hits: number) => `${hits} 个命中`,
        statusLabel: '本轮状态',
        multiplierLabel: '倍率',
        hitCountLabel: '命中数',
        clear: '清空',
        stakeAmount: '下注金额',
        stakeRange: (min: string, max: string) => `最小 ${min} / 最大 ${max}`,
        play: '开始快八',
        drawing: '开奖中...',
        loadingRequest: '正在结算这一张快八票面...',
        latestRound: '最近一期',
        payout: '派奖',
        drawnNumbers: (visible: number, total: number) => `开奖号码 ${visible}/${total}`,
        matchedNumbers: '命中号码',
        noMatches: '本轮没有命中号码。',
        noRoundYet: '当前还没有开奖记录。先把号码选满、设好金额，再开始开奖。',
        howToPlayTitle: '玩法说明',
        howToPlaySubtitle:
          '快速看懂如何填票、怎样读赔率阶梯，以及每一轮如何做公平性校验。',
        howToPlayStepOneTitle: '先填满 8 个号码',
        howToPlayStepOneBody:
          '请在 1 到 80 的选号盘里选出 8 个不重复号码。第 8 个号码填满后，票面就会锁定。',
        howToPlayStepTwoTitle: '设置下注并开局',
        howToPlayStepTwoBody:
          '在允许范围内输入下注金额，然后开始这一轮，系统会按顺序揭晓全部 20 个开奖号码。',
        howToPlayStepThreeTitle: '查看命中与派奖',
        howToPlayStepThreeBody:
          '派奖按下方赔率阶梯计算。命中 4 个开始派奖，命中 8 个会触发最高倍率。',
        howToPlayMaxWin: '最高倍率',
        howToPlayBoard: '选号范围',
        howToPlayDraws: '开奖号码数',
        howToPlayFairnessTitle: '可验证公平开奖',
        howToPlayFairnessBody:
          '每一轮快八都会附带 commit-reveal 公平性记录，开奖顺序和结果都能在结算后复核。',
      },
      predictionMarket: {
        routeTitle: '预测盘',
        routeSubtitle: '浏览实时市场、选择结果并跟踪每一场结算。',
        summaryBalance: '余额',
        summaryActiveMarket: '主推市场',
        summaryHoldings: '持仓票据',
        summaryLoading: '加载中',
        summaryEmpty: '暂无',
        sectionTitle: '实时市场',
        sectionSubtitle: '把主推市场、奖池分布和下注入口都收在同一张移动端页面里。',
        refreshMarkets: '刷新市场',
        refreshingMarkets: '刷新中...',
        marketListTitle: '主推市场',
        marketDetailTitle: '市场看板',
        myHoldingsTitle: '你的预测票据',
        myHoldingsSubtitle:
          '按市场分组查看未结算敞口、已结算派奖和退款，不用逐个点进市场。',
        exposureOnlyTitle: '仅展示敞口与历史',
        exposureOnlyDescription:
          '当前 pari-mutuel 版本只展示 stake 敞口、扣除抽水后的已结算 payout 和退款，不计算市场仍在开放时的实时盈亏。',
        refreshHistory: '刷新历史',
        loadingHistory: '加载历史中...',
        noMarkets: '当前还没有配置预测盘市场。',
        noMarketSelected: '先从上方选择一个市场，再查看奖池、时间和下注控件。',
        noDescription: '当前市场还没有补充说明。',
        marketStatus: '市场状态',
        positionStatus: '持仓状态',
        settlementStatus: '结算状态',
        totalPool: '总奖池',
        openPositions: '进行中持仓',
        yourPositions: '你的持仓',
        yourExposure: '你的敞口',
        winningOutcome: '胜出结果',
        mechanism: '机制',
        opensAt: '开盘时间',
        locksAt: '封盘时间',
        resolvesAt: '预计结算',
        resolvedAt: '实际结算',
        lastUpdated: '最近更新',
        selectOutcome: '选择结果',
        selectedOutcome: '当前选择',
        chooseOutcome: '请先选择一个下注结果。',
        stakeAmount: '下注金额',
        stakeHint: '输入大于 0 的金额。预测盘采用奖池分配并先扣抽水，最终派奖要等市场结算后才能确定。',
        placeBet: '立即预测',
        placingBet: '下注中...',
        marketClosed: '当前市场已停止接收新下注。',
        outcomePool: (stake: string, count: number, share: string) =>
          `奖池 ${stake} · ${count} 笔持仓 · 占比 ${share}`,
        winningPool: (stake: string) => `胜出奖池 ${stake}`,
        positionPlacedAt: '建仓时间',
        positionSettledAt: '结算时间',
        potentialPayout: '派奖',
        noPositions: '你在这个市场里还没有持仓。',
        noHoldings: '你还没有任何预测盘持仓。',
        noFilteredHoldings: '当前筛选条件下还没有对应的分组历史。',
        noOutcomePools: '当前还没有任何奖池流入。',
        marketCountLabel: '市场数',
        positionCountLabel: '仓位数',
        totalStake: '总下注',
        openExposure: '未结算敞口',
        settledPayout: '已结算派奖',
        refundedAmount: '退款金额',
        lastActivity: '最近活动',
        roundKey: '轮次',
        focusMarket: '打开市场',
        previousPage: '上一页',
        nextPage: '下一页',
        portfolioPageValue: (page: number) => `第 ${page} 页`,
        portfolioFilterLabels: {
          all: '全部',
          open: '未结算',
          resolved: '已结算',
          refunded: '已退款',
        },
        portfolioStatusLabels: {
          open: '未结算',
          resolved: '已结算',
          refunded: '已退款',
        },
        marketStatusLabels: {
          draft: '草稿',
          open: '开放中',
          locked: '已封盘',
          resolved: '已结算',
          cancelled: '已取消',
        },
        positionStatusLabels: {
          open: '进行中',
          won: '已中奖',
          lost: '未命中',
          sold: '已卖出',
          refunded: '已退款',
        },
        settlementPending: '待结算',
        settlementResolved: '已结算',
        settlementCancelled: '已取消',
        winningOutcomePending: '待公布',
        mechanismPariMutuel: '奖池分配',
        outcomeWinner: '胜出',
      },
      holdem: {
        routeTitle: '德州牌桌',
        routeSubtitle: '从大厅进入实时牌局、桌内聊天和回放查看，不用离开这一张移动端页面。',
        summaryBalance: '余额',
        summaryStatus: '桌面状态',
        summaryLoading: '加载中',
        sectionTitle: '牌桌舞台',
        sectionSubtitle:
          '开桌、入局、查看实时公共牌，并在同一屏完成逐街行动、公平性查看和回放复盘。',
        tableMode: '桌型模式',
        tableName: '桌名',
        seatCount: '人数',
        buyInAmount: '买入金额',
        tournamentStartingStack: '起始筹码',
        tournamentPayoutPlaces: '派奖名次',
        buyInRange: (min: string, max: string) => `最小 ${min} / 最大 ${max}`,
        effectiveBuyInPreview: (amount: string) => `实际买入 ${amount}`,
        casualTableHint: '娱乐局使用奖励余额买入，不抽水，且不要求 KYC。',
        cashTableHint: '现金桌使用可提现余额买入，并应用实时抽水策略。',
        tournamentTableHint:
          '锦标赛会把买入汇总进奖池，所有参赛者统一起始筹码，直到淘汰名次确定后才统一派奖。',
        tournamentPayoutPlacesHint:
          '最终派奖名次数会按实际报名人数收口，最多只发到前三名。',
        createTable: '创建牌桌',
        creatingTable: '正在开桌...',
        joinTable: '加入牌桌',
        joiningTable: '正在买入...',
        leaveTable: '离桌',
        leavingTable: '正在退桌...',
        sitOutTable: '暂离一手',
        sittingOutTable: '正在暂离...',
        sitInTable: '回到桌上',
        sittingInTable: '正在恢复入局...',
        startHand: '开始发牌',
        startingHand: '正在洗牌...',
        refreshTable: '刷新牌桌',
        refreshingTable: '刷新中...',
        noTables: '当前还没有开放的牌桌。',
        noSelection: '先从大厅选择一张牌桌，再查看当前牌局。',
        board: '公共牌',
        actionClock: '行动时限',
        currentBet: '当前下注',
        toCall: '跟注到',
        minRaiseTo: '最小加到',
        actionAmount: '行动金额',
        blinds: '盲注',
        tableType: '桌型',
        cashTable: '现金桌',
        casualTable: '娱乐局',
        tournamentTable: '锦标赛',
        rakePolicy: '抽水',
        rakeCap: '封顶',
        rakeNone: '不抽水',
        rakeNoFlopNoDrop: '未发翻牌不抽水',
        fairness: '公平性',
        timeBank: '时间银行',
        stack: '筹码',
        streetCommitted: '本街',
        totalCommitted: '总投入',
        mainPot: '主池',
        sidePot: '边池',
        winners: '赢家',
        hand: '手牌',
        tableChat: '桌内聊天',
        tableChatEmpty: '桌上还没人发消息。先入座再打破沉默。',
        tableChatPlaceholder: '输入桌内消息',
        tableChatSend: '发送',
        tableChatSending: '发送中...',
        tableChatReactions: '快捷表情',
        tableChatSeatOnly: '只有已入座玩家可以发送桌内聊天和表情。',
        recentHands: '最近牌局',
        noRecentHands: '还没有已结算牌局。',
        viewReplay: '打开回放',
        hideReplay: '收起回放',
        replayLoading: '正在加载牌局回放...',
        replayFailed: '加载这手牌回放失败。',
        replayDetailTitle: '德州回放详情',
        replayDetailSubtitle: '查看完整牌局回放、事件时间线，以及争议排查所需的元数据。',
        replayBackToTable: '返回牌桌',
        copyDisputePayload: '复制争议载荷',
        exportHandEvidence: '导出签名证据包',
        replayArtifactCopied: '争议载荷已复制。',
        replayArtifactExported: '签名证据包已导出。',
        replayArtifactFailed: '证据包操作失败。',
        replayBundleSummary: '签名证据摘要',
        replayBundleExportedAt: '导出时间',
        replayBundleKeyId: '签名键标识',
        replayBundleDigest: '载荷摘要',
        replaySummary: '回放摘要',
        replayTimeline: '事件时间线',
        replayParticipants: '参与者',
        replayStake: '投入',
        replayPayout: '结算',
        replayRake: '抽水',
        replayStartedAt: '开始时间',
        replaySettledAt: '结算时间',
        replayDispute: '争议详情',
        replayRoundId: '回合编号',
        replayReferenceId: '牌局记录号',
        replayEventCount: '事件数',
        replaySupportHint: '审计或争议排查时，请使用回合编号、记录号和公平性提交值。',
        stagePreflop: '翻牌前',
        stageFlop: '翻牌',
        stageTurn: '转牌',
        stageRiver: '河牌',
        stageShowdown: '摊牌',
        eventHandStarted: '牌局开始',
        eventCardsDealt: '发出底牌',
        eventSmallBlindPosted: '小盲已下',
        eventBigBlindPosted: '大盲已下',
        eventTurnStarted: '轮到行动',
        eventTurnTimedOut: '行动超时',
        eventPlayerActed: '玩家行动',
        eventBoardRevealed: '翻开公共牌',
        eventFairnessRevealed: '公开公平性种子',
        eventShowdownResolved: '摊牌结算',
        eventHandWonByFold: '弃牌获胜',
        eventHandSettled: '牌局完成结算',
        openSeat: '空位',
        you: '你',
        dealer: '庄位',
        smallBlind: '小盲',
        bigBlind: '大盲',
        turn: '行动中',
        fold: '弃牌',
        check: '过牌',
        call: '跟注',
        bet: '下注',
        raise: '加注',
        allIn: '全下',
        amountHint: '下注和加注输入的是本街你希望累计投入的总额，而不是增量。',
        waitingStatus: '等待中',
        sittingOutStatus: '暂离',
        activeStatus: '进行中',
        realtimeConnecting: '正在连接牌桌实时通道...',
        realtimeLive: '牌桌实时通道已连接。',
        realtimeReconnecting: '牌桌实时通道重连中...',
        realtimeResyncing: '已重新连接，正在同步权威桌面状态...',
      },
      blackjack: {
        routeTitle: '二十一点牌桌',
        routeSubtitle: '把荷官、实时手牌、公平性和最近结果收在同一张独立移动端牌桌里。',
        summaryBalance: '余额',
        summaryFairnessEpoch: '公平性 Epoch',
        summaryLoading: '加载中',
        sectionTitle: '牌桌舞台',
        sectionSubtitle:
          '开局、看牌、查看荷官规则，并在同一屏完成操作和结算确认。',
        stakeLabel: '下注',
        payoutLabel: '结算',
        metaStakeRange: '下注范围',
        metaNaturalPayout: '天生二十一点赔付',
        metaDealer: '庄家规则',
        metaDouble: '加倍',
        metaSplitAces: '拆 A',
        metaHitSplitAces: '拆 A 后要牌',
        metaResplit: '重复分牌',
        metaMaxSplitHands: '最大分牌手数',
        metaTenValueSplit: '10-value 等价分牌',
        dealerHitsSoft17: '软 17 要牌',
        dealerStandAll17: '所有 17 点停牌',
        doubleEnabled: '已启用',
        doubleDisabled: '未启用',
        stakeAmount: '下注金额',
        stakeHint: (min: string, max: string) =>
          `请输入 ${min} 到 ${max} 之间的下注金额，然后每次只开一手牌。`,
        effectiveStakePreview: (stake: string) => `总下注 ${stake}`,
        startHand: '开始发牌',
        dealing: '发牌中...',
        refreshHand: '刷新牌局',
        refreshingHand: '刷新中...',
        noActiveHand: '当前没有进行中的牌局，下一次开始会发出新的一手牌。',
        tableTitle: '同桌席位',
        tableId: '桌号',
        seat: '座位',
        aiDealer: 'AI 智能荷官',
        you: '你',
        dealerHand: '庄家',
        playerHand: '玩家',
        visible: '可见点数',
        total: '总点数',
        settling: '结算中...',
        hit: '要牌',
        stand: '停牌',
        double: '加倍',
        split: '分牌',
        hand: '手牌',
        currentBet: '当前下注',
        activeHand: '当前手',
        waitingHand: '待处理',
        stoodHand: '已停牌',
        bustHand: '爆牌',
        winHand: '获胜',
        loseHand: '输牌',
        pushHand: '平局',
        recentHands: '最近牌局',
        noRecentHands: '当前还没有已结算的二十一点牌局。',
        loadingState: '正在刷新二十一点状态...',
      },
    } satisfies Record<RouteScreenKey, Record<string, unknown>>,
  },
} as const;

export type MobileRouteCopy = (typeof routeCopy)[keyof typeof routeCopy];
export type MobileRouteLabels = MobileRouteCopy['labels'];
export type MobileRouteCards = MobileRouteCopy['cards'];
export type MobileRouteHeroes = MobileRouteCopy['heroes'];
export type MobileRouteScreens = MobileRouteCopy['screens'];

export function getMobileRouteCopy(locale: MobileFairnessLocale) {
  return routeCopy[locale];
}
