import type { Locale } from '@/lib/i18n/messages';

export const userDashboardCopy = {
  en: {
    accountTitle: 'Account readiness',
    accountDescription:
      'Unlock draw, payouts, and security self-service from one place.',
    emailVerified: 'Email verified',
    emailPending: 'Email verification required',
    phoneVerified: 'Phone verified',
    phonePending: 'Phone verification required',
    drawUnlocked: 'Draw enabled',
    drawLocked: 'Verify your email before running the draw flow.',
    routesTitle: 'Game routes',
    routesDescription:
      'Gameplay moved off the dashboard. Launch each mode from its own route and keep the account center focused on wallet, rewards, and security.',
    accountRoutesTitle: 'Account routes',
    accountRoutesDescription:
      'Move funding, payouts, rewards, and session controls onto their own route containers instead of stacking every workflow into one page.',
    routeLockedHint:
      'You can open the page now, but email verification is still required before placing a draw or bet.',
    gachaTitle: 'Slot Machine',
    gachaDescription:
      'Three-reel spin, pity progress, and fairness proof now live on `/app/slot`.',
    gachaOpen: 'Open slot machine',
    quickEightTitle: 'Quick Eight',
    quickEightDescription:
      'Pick 8 numbers and settle against the shared prize pool on `/app/quick-eight`.',
    quickEightOpen: 'Open Quick Eight',
    blackjackTitle: 'Blackjack',
    blackjackDescription:
      'Classic player-vs-dealer blackjack now runs on its own route at `/app/blackjack`.',
    blackjackOpen: 'Open blackjack',
    fairnessTitle: 'Fairness verifier',
    fairnessDescription:
      'Open a standalone commit-reveal verifier on `/app/fairness` and prove locally that `SHA-256(seed)` matches the published commit.',
    fairnessOpen: 'Open fairness verifier',
    fairnessStatus: 'Public proof',
    rewardsRouteTitle: 'Reward center',
    rewardsRouteDescription:
      'Review missions, claim bonuses, and keep progression separate from wallet and payout operations.',
    rewardsRouteOpen: 'Open reward center',
    rewardsRouteStatus: 'Mission hub',
    walletRouteTitle: 'Wallet operations',
    walletRouteDescription:
      'Handle fiat top-ups, crypto deposit claims, and ledger review from a dedicated wallet container.',
    walletRouteOpen: 'Open wallet operations',
    walletRouteStatus: 'Ledger live',
    paymentsRouteTitle: 'Payout operations',
    paymentsRouteDescription:
      'Manage payout cards, crypto destinations, and withdrawal requests on a dedicated payments route.',
    paymentsRouteOpen: 'Open payout operations',
    paymentsRouteStatus: 'Payout tools',
    securityRouteTitle: 'Security center',
    securityRouteDescription:
      'Keep email and phone verification plus session revocation on a separate security route.',
    securityRouteOpen: 'Open security center',
    securityRouteStatus: 'Access control',
    financeUnlocked: 'Payout tools enabled',
    financeLocked:
      'Bank cards and withdrawals unlock after both email and phone verification.',
    sendEmail: 'Send verification email',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+61 4xx xxx xxx',
    codeLabel: 'SMS code',
    codePlaceholder: '6-digit code',
    sendCode: 'Send code',
    confirmPhone: 'Confirm phone',
    verificationEmailSent:
      'Verification email requested. Check the inbox on file if the account still needs verification.',
    phoneCodeSent: 'Verification code sent. Enter the SMS code to finish setup.',
    phoneVerifiedNotice: 'Phone verified. Withdrawal tools are now available.',
    walletTitle: 'Wallet and top-ups',
    walletDescription:
      'Balance visibility, pending deposits, and the notes users need before funding.',
    currentBalance: 'Current balance',
    topUpAmount: 'Top-up amount',
    referenceId: 'Reference ID',
    referencePlaceholder: 'Optional remittance or payment reference',
    createTopUp: 'Create top-up request',
    topUpCreated:
      'Top-up request submitted. The order will move through provider settlement before crediting the wallet.',
    recentTopUps: 'Recent top-ups',
    noTopUps: 'No top-up requests yet.',
    cryptoDepositTitle: 'Crypto deposit channels',
    cryptoDepositDescription:
      'Use the configured wallet address, then submit the transfer hash for manual review.',
    depositChannel: 'Deposit channel',
    depositChannelPlaceholder: 'Select a crypto channel',
    depositTxHash: 'Transaction hash',
    depositFromAddress: 'From address',
    submitCryptoDeposit: 'Submit crypto deposit claim',
    cryptoDepositCreated:
      'Crypto deposit claim submitted. Finance will verify the chain transfer before crediting the wallet.',
    noCryptoChannels: 'No crypto deposit channels are active yet.',
    recentCryptoDeposits: 'Recent crypto deposits',
    noCryptoDeposits: 'No crypto deposit claims yet.',
    paymentsTitle: 'Bank cards and withdrawals',
    paymentsDescription:
      'Bind payout cards, set a default destination, and request withdrawals.',
    addCard: 'Add bank card',
    cardholderName: 'Cardholder name',
    bankName: 'Bank name',
    cardBrand: 'Card brand',
    last4: 'Last 4 digits',
    saveCard: 'Save bank card',
    cardSaved: 'Bank card saved.',
    noCards: 'No bank cards saved yet.',
    defaultCard: 'Default',
    setDefault: 'Set default',
    defaultCardUpdated: 'Default bank card updated.',
    withdrawalAmount: 'Withdrawal amount',
    payoutCard: 'Payout card',
    payoutCardPlaceholder: 'Select a saved card',
    requestWithdrawal: 'Request withdrawal',
    withdrawalCreated:
      'Withdrawal request submitted. Funds are reserved while approval and payout progress.',
    recentWithdrawals: 'Recent withdrawals',
    noWithdrawals: 'No withdrawals yet.',
    cryptoAddressTitle: 'Crypto payout addresses',
    cryptoAddressDescription:
      'Save wallet destinations per chain and token before requesting a crypto payout.',
    cryptoChain: 'Chain',
    cryptoNetwork: 'Network',
    cryptoToken: 'Token',
    cryptoAddress: 'Wallet address',
    cryptoLabel: 'Address label',
    saveCryptoAddress: 'Save crypto address',
    cryptoAddressSaved: 'Crypto payout address saved.',
    noCryptoAddresses: 'No crypto payout addresses saved yet.',
    setDefaultAddress: 'Set default address',
    defaultCryptoAddressUpdated: 'Default crypto payout address updated.',
    cryptoWithdrawalAmount: 'Crypto withdrawal amount',
    cryptoWithdrawalAddress: 'Crypto payout address',
    cryptoWithdrawalAddressPlaceholder: 'Select a saved crypto address',
    requestCryptoWithdrawal: 'Request crypto withdrawal',
    cryptoWithdrawalCreated:
      'Crypto withdrawal request submitted. Funds stay locked until the chain transfer is confirmed.',
    recentCryptoWithdrawals: 'Recent crypto withdrawals',
    noCryptoWithdrawals: 'No crypto withdrawals yet.',
    transactionsTitle: 'Ledger activity',
    transactionsDescription:
      'Immutable balance movements from draws, deposits, and payout operations.',
    noTransactions: 'No ledger entries yet.',
    sessionsTitle: 'Active sessions',
    sessionsDescription: 'Review active devices and revoke access if needed.',
    noSessions: 'No active sessions found.',
    refresh: 'Refresh',
    revoke: 'Revoke',
    signOutThisDevice: 'Sign out this device',
    signOutEverywhere: 'Sign out everywhere',
    currentDevice: 'Current device',
    activeSession: 'Active session',
    thisDeviceRevoked: 'This device was signed out. Redirecting to login.',
    sessionRevoked: 'Session revoked.',
    allSessionsRevoked: 'All active sessions were revoked. Redirecting to login.',
    createdAt: 'Created',
    status: 'Status',
    amount: 'Amount',
    type: 'Type',
    before: 'Before',
    after: 'After',
    reference: 'Reference',
    device: 'Device',
    expires: 'Expires',
    unknown: 'Unknown',
    noSelection: 'No default card selected.',
    submitMissing: 'Complete the required fields before submitting.',
    loadFailed: 'Failed to load dashboard data.',
    retry: 'Retry',
    rewardClaimed: 'Reward claimed. Mission progress and bonus balance refreshed.',
    verificationBanner:
      'Email verification unlocks draws. Phone verification unlocks bank cards and withdrawals.',
    verified: 'Verified',
    pending: 'Pending',
    topUpSectionLabel:
      'Top-ups move through requested, provider pending, settled, and credited states before the wallet changes.',
    withdrawalSectionLabel:
      'Withdrawals reserve funds first, then move through approval, paying, and paid or reversal states.',
  },
  'zh-CN': {
    accountTitle: '账户可用状态',
    accountDescription: '把抽奖、出款和安全自助入口收进一个用户中心里。',
    emailVerified: '邮箱已验证',
    emailPending: '需要完成邮箱验证',
    phoneVerified: '手机号已验证',
    phonePending: '需要完成手机号验证',
    drawUnlocked: '抽奖已解锁',
    drawLocked: '请先完成邮箱验证，再执行抽奖流程。',
    routesTitle: '玩法入口',
    routesDescription:
      '玩法已经从首页拆出去。账户首页只保留钱包、奖励和安全能力，具体玩法走各自独立路由。',
    accountRoutesTitle: '账户路由',
    accountRoutesDescription:
      '把充值、提现、奖励和会话控制拆成独立 route container，不再继续堆在一个页面里。',
    routeLockedHint: '你现在可以先打开页面，但在邮箱验证完成前，抽卡和下注仍然会被拦截。',
    gachaTitle: '老虎机',
    gachaDescription:
      '三轴演出、保底进度和公平性证明统一放到 `/app/slot`。',
    gachaOpen: '打开老虎机页面',
    quickEightTitle: '快八',
    quickEightDescription: '8 选号码、即时开奖和派奖流程统一放到 `/app/quick-eight`。',
    quickEightOpen: '打开快八页面',
    blackjackTitle: '二十一点',
    blackjackDescription: '经典庄闲二十一点已拆到独立页面 `/app/blackjack`。',
    blackjackOpen: '打开二十一点页面',
    fairnessTitle: '公平性验证器',
    fairnessDescription:
      '把 commit-reveal 独立拆到 `/app/fairness`，可单独 reveal 已结束 epoch，并在本地验证 `SHA-256(seed)` 是否匹配已公布 commit。',
    fairnessOpen: '打开公平性验证页',
    fairnessStatus: '公开证明',
    rewardsRouteTitle: '奖励中心',
    rewardsRouteDescription:
      '把任务进度和奖励领取独立成页，不再和钱包、提现流程混在一起。',
    rewardsRouteOpen: '打开奖励中心',
    rewardsRouteStatus: '任务中心',
    walletRouteTitle: '钱包操作',
    walletRouteDescription:
      '把法币充值、加密充值认领和账本流水放到独立的钱包容器页。',
    walletRouteOpen: '打开钱包操作',
    walletRouteStatus: '账本在线',
    paymentsRouteTitle: '出款操作',
    paymentsRouteDescription:
      '把银行卡、加密收款地址和提现申请放到独立的支付路由。',
    paymentsRouteOpen: '打开出款操作',
    paymentsRouteStatus: '出款工具',
    securityRouteTitle: '安全中心',
    securityRouteDescription:
      '把邮箱/手机号验证和会话撤销拆到单独安全页。',
    securityRouteOpen: '打开安全中心',
    securityRouteStatus: '访问控制',
    financeUnlocked: '出款工具已解锁',
    financeLocked: '银行卡和提现都需要邮箱、手机号双验证后才能使用。',
    sendEmail: '发送验证邮件',
    phoneLabel: '手机号',
    phonePlaceholder: '+86 13800138000',
    codeLabel: '短信验证码',
    codePlaceholder: '6 位验证码',
    sendCode: '发送验证码',
    confirmPhone: '确认手机号',
    verificationEmailSent: '验证邮件已重新发起。如果账号还未验证，请检查当前绑定邮箱。',
    phoneCodeSent: '验证码已发送，请输入短信中的 6 位验证码完成绑定。',
    phoneVerifiedNotice: '手机号验证完成，提现工具已可用。',
    walletTitle: '钱包与充值',
    walletDescription: '展示当前余额、充值申请，以及用户需要知道的账本说明。',
    currentBalance: '当前余额',
    topUpAmount: '充值金额',
    referenceId: '参考单号',
    referencePlaceholder: '可选，填写转账流水或支付参考号',
    createTopUp: '创建充值申请',
    topUpCreated: '充值申请已提交。该笔单据会先经过渠道与结算状态，再在入账后更新余额。',
    recentTopUps: '最近充值申请',
    noTopUps: '还没有充值申请。',
    cryptoDepositTitle: '加密货币充值通道',
    cryptoDepositDescription:
      '先按页面展示的钱包地址转账，再提交 txHash 进入人工审核。',
    depositChannel: '充值通道',
    depositChannelPlaceholder: '请选择加密充值通道',
    depositTxHash: '交易哈希',
    depositFromAddress: '付款地址',
    submitCryptoDeposit: '提交加密充值认领',
    cryptoDepositCreated:
      '加密充值认领已提交。财务会先核对链上转账，再把余额记入钱包。',
    noCryptoChannels: '当前还没有启用中的加密充值通道。',
    recentCryptoDeposits: '最近加密充值',
    noCryptoDeposits: '还没有加密充值认领。',
    paymentsTitle: '银行卡与提现',
    paymentsDescription: '绑定出款银行卡、设置默认卡，并提交提现申请。',
    addCard: '新增银行卡',
    cardholderName: '持卡人姓名',
    bankName: '银行名称',
    cardBrand: '卡组织/类型',
    last4: '卡号后四位',
    saveCard: '保存银行卡',
    cardSaved: '银行卡已保存。',
    noCards: '还没有保存任何银行卡。',
    defaultCard: '默认卡',
    setDefault: '设为默认',
    defaultCardUpdated: '默认银行卡已更新。',
    withdrawalAmount: '提现金额',
    payoutCard: '出款银行卡',
    payoutCardPlaceholder: '请选择已保存的银行卡',
    requestWithdrawal: '提交提现申请',
    withdrawalCreated: '提现申请已提交。对应金额会先保留，再进入审核与打款状态。',
    recentWithdrawals: '最近提现申请',
    noWithdrawals: '还没有提现申请。',
    cryptoAddressTitle: '加密提现地址',
    cryptoAddressDescription:
      '按链和币种保存收款地址，再发起加密提现申请。',
    cryptoChain: '链',
    cryptoNetwork: '网络',
    cryptoToken: '币种',
    cryptoAddress: '钱包地址',
    cryptoLabel: '地址备注',
    saveCryptoAddress: '保存加密地址',
    cryptoAddressSaved: '加密提现地址已保存。',
    noCryptoAddresses: '还没有保存任何加密提现地址。',
    setDefaultAddress: '设为默认地址',
    defaultCryptoAddressUpdated: '默认加密提现地址已更新。',
    cryptoWithdrawalAmount: '加密提现金额',
    cryptoWithdrawalAddress: '加密收款地址',
    cryptoWithdrawalAddressPlaceholder: '请选择已保存的加密地址',
    requestCryptoWithdrawal: '提交加密提现申请',
    cryptoWithdrawalCreated:
      '加密提现申请已提交。对应金额会先锁定，待链上转账确认后再完成。',
    recentCryptoWithdrawals: '最近加密提现',
    noCryptoWithdrawals: '还没有加密提现申请。',
    transactionsTitle: '账本流水',
    transactionsDescription: '展示抽奖、充值和提现相关的不可变余额流水。',
    noTransactions: '还没有账本流水。',
    sessionsTitle: '活跃会话',
    sessionsDescription: '查看当前活跃设备，并在需要时撤销访问。',
    noSessions: '没有查询到活跃会话。',
    refresh: '刷新',
    revoke: '撤销',
    signOutThisDevice: '退出当前设备',
    signOutEverywhere: '全部设备退出',
    currentDevice: '当前设备',
    activeSession: '活跃会话',
    thisDeviceRevoked: '当前设备已退出，正在跳转登录页。',
    sessionRevoked: '会话已撤销。',
    allSessionsRevoked: '所有活跃会话都已撤销，正在跳转登录页。',
    createdAt: '创建时间',
    status: '状态',
    amount: '金额',
    type: '类型',
    before: '变更前',
    after: '变更后',
    reference: '关联单据',
    device: '设备',
    expires: '过期时间',
    unknown: '未知',
    noSelection: '还没有默认出款卡。',
    submitMissing: '请先补全必填字段。',
    loadFailed: '加载用户中心数据失败。',
    retry: '重试',
    rewardClaimed: '奖励已领取，任务进度和奖励余额已刷新。',
    verificationBanner: '邮箱验证会解锁抽奖，手机号验证会解锁银行卡和提现。',
    verified: '已验证',
    pending: '待处理',
    topUpSectionLabel: '充值会按 requested、provider pending、settled、credited 的顺序推进，真正入账前不会改余额。',
    withdrawalSectionLabel: '提现会先保留金额，再进入 approved、paying、paid 或 reversed 等状态。',
  },
} satisfies Record<Locale, Record<string, string>>;

export type UserDashboardCopy =
  (typeof userDashboardCopy)[keyof typeof userDashboardCopy];
