import type { Locale } from '@/lib/i18n/messages';

export const userDashboardCopy = {
  en: {
    accountTitle: 'Account readiness',
    accountDescription:
      'Unlock draw, economy visibility, and security self-service from one place.',
    emailVerified: 'Email verified',
    emailPending: 'Email verification required',
    phoneVerified: 'Phone verified',
    phonePending: 'Phone verification required',
    drawUnlocked: 'Draw enabled',
    drawLocked: 'Verify your email before running the draw flow.',
    overviewHeroEyebrow: 'Active event',
    overviewHeroTitle: 'Neon Nights is live across tables, rewards, and prediction rounds.',
    overviewHeroDescription:
      'Use the lobby as the jump point for fast tables, reward draws, and live market positions. Keep fairness, wallet, and missions close while you play.',
    overviewHeroPrimary: 'Open prediction markets',
    overviewHeroSecondary: 'Open reward center',
    overviewRewardsEyebrow: 'Reward spotlight',
    overviewRewardsTitle: 'Lucky Streak weekend is pushing pack drops, bonus spins, and mission payouts.',
    overviewRewardsDescription:
      'Stay close to the reward loop, rotate into draw routes, and clear mission tracks before the event timer rolls over.',
    overviewRewardsPrimary: 'Open reward center',
    overviewRewardsSecondary: 'Open slot machine',
    overviewCommunityEyebrow: 'Club bulletin',
    overviewCommunityTitle: 'Community picks, fairness proofs, and hot threads are moving together this round.',
    overviewCommunityDescription:
      'Track the conversation around live tables, review published fairness proof, and pivot into the routes players are talking about.',
    overviewCommunityPrimary: 'Open community',
    overviewCommunitySecondary: 'Open fairness verifier',
    overviewPulseTitle: 'Player pulse',
    overviewPulseDescription:
      'Track which routes feel active before you jump in.',
    overviewQueueTitle: 'Activity queue',
    overviewQueueDescription: 'Rotate through live campaign cards and jump into the route behind each spotlight.',
    overviewSignalsTitle: 'Live signals',
    overviewSignalsDescription: 'Snapshot the current activity lane before you move into markets, tables, or rewards.',
    profileWalletEyebrow: 'My wallet',
    profileWalletDescription:
      'Keep credits, reward balance, payout tools, and recent ledger activity inside one player wallet hub.',
    profileTotalBalanceLabel: 'Total balance',
    profileLockedBalanceLabel: 'Locked balance',
    profileQuickActionsTitle: 'Quick actions',
    profileRecentActivityTitle: 'Ledger',
    profileRecentActivityDescription:
      'Latest balance movement across rewards, tables, and markets.',
    profileNoRecentActivity: 'No recent wallet activity yet.',
    profileAccountEyebrow: 'Account',
    profileAccountDescription:
      'Keep verification, security, and payout readiness grouped inside one personal center.',
    profileVerificationSummaryTitle: 'Verification',
    profileSecuritySummaryTitle: 'Security',
    profilePayoutSummaryTitle: 'Rewards & withdrawal',
    profileCurrentDeviceTitle: 'Current device',
    profileTierLabel: 'Trust tier',
    lobbyTitle: 'Featured tables',
    lobbyDescription:
      'Dedicated routes for table play, quick rounds, reward draws, and market positions.',
    routePlayersLabel: 'Active players',
    routeRewardRangeLabel: 'Reward range',
    routeRiskLabel: 'Risk level',
    riskLow: 'Low risk',
    riskMedium: 'Medium risk',
    riskHigh: 'High risk',
    routesTitle: 'Game routes',
    routesDescription:
      'Gameplay moved off the dashboard. Launch each mode from its own route and keep the account center focused on wallet, rewards, and security.',
    accountRoutesTitle: 'Account routes',
    accountRoutesDescription:
      'Move economy, rewards, and session controls onto their own route containers instead of stacking every workflow into one page.',
    routeLockedHint:
      'You can open the page now, but email verification is still required before placing a draw or bet.',
    gachaTitle: 'Slot Machine',
    gachaDescription:
      'Three-reel spin, pity progress, and fairness proof now live on `/app/slot`.',
    gachaOpen: 'Open slot machine',
    quickEightTitle: 'Quick Eight',
    quickEightDescription:
      'Pick 8 numbers and settle against the shared prize pool on `/app/quick-eight`.',
    quickEightOpen: 'Open Quick Eight',
    holdemTitle: "Texas Hold'em",
    holdemDescription:
      'Create or join multiplayer casual or cash tables, choose the seat count, and play streets on `/app/holdem`.',
    holdemOpen: "Open Hold'em",
    blackjackTitle: 'Blackjack',
    blackjackDescription:
      'Blackjack with an AI dealer seated at the same table now runs on its own route at `/app/blackjack`.',
    blackjackOpen: 'Open blackjack',
    marketsTitle: 'Prediction Markets',
    marketsDescription:
      'Open live positions, track momentum, and rotate into headline events from `/app/markets`.',
    marketsOpen: 'Open prediction markets',
    marketsStatus: 'Market live',
    fairnessTitle: 'Fairness verifier',
    fairnessDescription:
      'Open a standalone commit-reveal verifier on `/app/fairness` and prove locally that `SHA-256(seed)` matches the published commit.',
    fairnessOpen: 'Open fairness verifier',
    fairnessStatus: 'Public proof',
    rewardsRouteTitle: 'Reward center',
    rewardsRouteDescription:
      'Review missions, claim bonuses, and keep progression separate from the economy wallet and security controls.',
    rewardsRouteOpen: 'Open reward center',
    rewardsRouteStatus: 'Mission hub',
    walletRouteTitle: 'Economy wallet',
    walletRouteDescription:
      'Review asset balances, gifting activity, and the read-only gift pack catalog from a dedicated wallet container.',
    walletRouteOpen: 'Open economy wallet',
    walletRouteStatus: 'Economy live',
    paymentsRouteTitle: 'Payout operations',
    paymentsRouteDescription:
      'Manage payout cards, crypto destinations, and withdrawal requests on a dedicated payments route.',
    paymentsRouteOpen: 'Open payout operations',
    paymentsRouteStatus: 'Payout tools',
    securityRouteTitle: 'Security center',
    securityRouteDescription:
      'Keep email and phone verification plus session revocation on a separate security route.',
    securityRouteOpen: 'Open security center',
    securityRouteStatus: 'Access control',
    verificationRouteTitle: 'KYC verification',
    verificationRouteDescription:
      'Upload identity documents, track review state, and see which tier unlocks gameplay or withdrawals.',
    verificationRouteOpen: 'Open KYC verification',
    verificationRouteStatus: 'Identity tier',
    financeUnlocked: 'Higher-trust actions enabled',
    financeLocked:
      'Phone verification is required before higher-trust account actions.',
    securityHeroEyebrow: 'Security center',
    securityHeroTitle: 'Lock the account before high-trust play begins.',
    securityHeroDescription:
      'Keep email, phone, sessions, and identity review in one guarded route so wallet actions feel protected instead of buried in settings.',
    securitySummaryLevel: 'Security tier',
    securitySummaryChecks: 'Checks live',
    securitySummarySessions: 'Active sessions',
    securitySummaryAccess: 'Draw access',
    securityTierPending: 'Entry tier',
    securityTierActive: 'Verified tier',
    securityTierAdvanced: 'Shielded tier',
    securityIdentityTitle: 'Identity and trust',
    securityIdentityDescription:
      'Complete lightweight checks here first, then move into KYC only when withdrawals or restricted events require a higher trust level.',
    securityEmailStepTitle: 'Email checkpoint',
    securityEmailStepDescription:
      'Confirm the inbox on file so draws, reward claims, and recovery links stay tied to your player account.',
    securityPhoneStepTitle: 'Phone checkpoint',
    securityPhoneStepDescription:
      'Add a verified phone before higher-trust actions like withdrawals, payout edits, or account recovery.',
    securityVerificationRouteDescription:
      'Open the identity review route when you need higher withdrawal or event access.',
    securityDefenseTitle: 'Account defense',
    securityDefenseDescription:
      'See which protection layers are live right now and when the current device expires.',
    securityDefenseEmail: 'Email lock',
    securityDefensePhone: 'Phone lock',
    securityDefenseSessions: 'Session watch',
    securityDefenseExpires: 'Current device expires',
    securityGuardTitle: 'Protection stack',
    securityGuardDescription:
      'Treat each layer as a gate. Lightweight checks unlock routine play, while stronger identity proof protects wallet actions and recovery.',
    securityGuardEmail:
      'Email verification keeps reward claims, draws, and reset links bound to the account.',
    securityGuardPhone:
      'Phone verification unlocks higher-trust wallet actions and adds a second recovery checkpoint.',
    securityGuardSessions:
      'Session review lets you kill stale devices before they turn into payout or settings risk.',
    securityRiskTitle: 'Risk disclosure',
    securityRiskDescription:
      'If a device, browser, or network looks unfamiliar, revoke it first and refresh the current session. Only move into full KYC when the product explicitly asks for a higher-trust identity tier.',
    sendEmail: 'Send verification email',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+61 4xx xxx xxx',
    codeLabel: 'SMS code',
    codePlaceholder: '6-digit code',
    sendCode: 'Send code',
    confirmPhone: 'Confirm phone',
    verificationEmailSent:
      'Verification email requested. Check the inbox on file if the account still needs verification.',
    phoneCodeSent: 'Verification code sent. Enter the SMS code to finish setup.',
    phoneVerifiedNotice:
      'Phone verified. Higher-trust account actions are now available.',
    walletTitle: 'Treasury',
    walletDescription:
      'Manage game credits, protected reserves, gifting tools, and wallet activity from one route.',
    currentBalance: 'Available B luck',
    topUpAmount: 'Top-up amount',
    referenceId: 'Reference ID',
    referencePlaceholder: 'Optional remittance or payment reference',
    createTopUp: 'Create top-up request',
    topUpCreated:
      'Top-up request submitted. The order will move through provider settlement before crediting the wallet.',
    recentTopUps: 'Recent top-ups',
    noTopUps: 'No top-up requests yet.',
    cryptoDepositTitle: 'Crypto deposit channels',
    cryptoDepositDescription:
      'Use the configured wallet address, then submit the transfer hash for manual review.',
    depositChannel: 'Deposit channel',
    depositChannelPlaceholder: 'Select a crypto channel',
    depositTxHash: 'Transaction hash',
    depositFromAddress: 'From address',
    submitCryptoDeposit: 'Submit crypto deposit claim',
    cryptoDepositCreated:
      'Crypto deposit claim submitted. Finance will verify the chain transfer before crediting the wallet.',
    noCryptoChannels: 'No crypto deposit channels are active yet.',
    recentCryptoDeposits: 'Recent crypto deposits',
    noCryptoDeposits: 'No crypto deposit claims yet.',
    paymentsTitle: 'Bank cards and withdrawals',
    paymentsDescription:
      'Bind payout cards, set a default destination, and request withdrawals.',
    addCard: 'Add bank card',
    cardholderName: 'Cardholder name',
    bankName: 'Bank name',
    cardBrand: 'Card brand',
    last4: 'Last 4 digits',
    saveCard: 'Save bank card',
    cardSaved: 'Bank card saved.',
    noCards: 'No bank cards saved yet.',
    defaultCard: 'Default',
    setDefault: 'Set default',
    defaultCardUpdated: 'Default bank card updated.',
    withdrawalAmount: 'Withdrawal amount',
    payoutCard: 'Payout card',
    payoutCardPlaceholder: 'Select a saved card',
    requestWithdrawal: 'Request withdrawal',
    withdrawalCreated:
      'Withdrawal request submitted. Funds are reserved while approval and payout progress.',
    recentWithdrawals: 'Recent withdrawals',
    noWithdrawals: 'No withdrawals yet.',
    cryptoAddressTitle: 'Crypto payout addresses',
    cryptoAddressDescription:
      'Save wallet destinations per chain and token before requesting a crypto payout.',
    cryptoChain: 'Chain',
    cryptoNetwork: 'Network',
    cryptoToken: 'Token',
    cryptoAddress: 'Wallet address',
    cryptoLabel: 'Address label',
    saveCryptoAddress: 'Save crypto address',
    cryptoAddressSaved: 'Crypto payout address saved.',
    noCryptoAddresses: 'No crypto payout addresses saved yet.',
    setDefaultAddress: 'Set default address',
    defaultCryptoAddressUpdated: 'Default crypto payout address updated.',
    cryptoWithdrawalAmount: 'Crypto withdrawal amount',
    cryptoWithdrawalAddress: 'Crypto payout address',
    cryptoWithdrawalAddressPlaceholder: 'Select a saved crypto address',
    requestCryptoWithdrawal: 'Request crypto withdrawal',
    cryptoWithdrawalCreated:
      'Crypto withdrawal request submitted. Funds stay locked until the chain transfer is confirmed.',
    recentCryptoWithdrawals: 'Recent crypto withdrawals',
    noCryptoWithdrawals: 'No crypto withdrawals yet.',
    transactionsTitle: 'Ledger activity',
    transactionsDescription:
      'Recent B luck balance movements across rewards, markets, and protected wallet actions.',
    noTransactions: 'No ledger entries yet.',
    sessionsTitle: 'Active sessions',
    sessionsDescription: 'Review active devices and revoke access if needed.',
    noSessions: 'No active sessions found.',
    refresh: 'Refresh',
    revoke: 'Revoke',
    signOutThisDevice: 'Sign out this device',
    signOutEverywhere: 'Sign out everywhere',
    currentDevice: 'Current device',
    activeSession: 'Active session',
    thisDeviceRevoked: 'This device was signed out. Redirecting to login.',
    sessionRevoked: 'Session revoked.',
    allSessionsRevoked: 'All active sessions were revoked. Redirecting to login.',
    createdAt: 'Created',
    status: 'Status',
    amount: 'Amount',
    type: 'Type',
    before: 'Before',
    after: 'After',
    reference: 'Reference',
    device: 'Device',
    expires: 'Expires',
    unknown: 'Unknown',
    noSelection: 'No default card selected.',
    submitMissing: 'Complete the required fields before submitting.',
    loadFailed: 'Failed to load dashboard data.',
    retry: 'Retry',
    rewardClaimed: 'Reward claimed. Mission progress and bonus balance refreshed.',
    verificationBanner:
      'Email verification unlocks draws. Phone verification protects higher-trust account actions.',
    verified: 'Verified',
    pending: 'Pending',
    topUpSectionLabel:
      'Top-ups move through requested, provider pending, settled, and credited states before the wallet changes.',
    withdrawalSectionLabel:
      'Withdrawals reserve funds first, then move through approval, paying, and paid or reversal states.',
  },
  'zh-CN': {
    accountTitle: '账户可用状态',
    accountDescription: '把抽奖、经济资产可见性和安全自助入口收进一个用户中心里。',
    emailVerified: '邮箱已验证',
    emailPending: '需要完成邮箱验证',
    phoneVerified: '手机号已验证',
    phonePending: '需要完成手机号验证',
    drawUnlocked: '抽奖已解锁',
    drawLocked: '请先完成邮箱验证，再执行抽奖流程。',
    overviewHeroEyebrow: '活动进行中',
    overviewHeroTitle: 'Neon Nights 已在牌桌、奖励和预测玩法中开启。',
    overviewHeroDescription:
      '把大厅当作统一跳板，在快节奏牌桌、奖励抽取和实时市场头寸之间切换，同时保持公平性、钱包和任务始终可见。',
    overviewHeroPrimary: '打开预测市场',
    overviewHeroSecondary: '打开奖励中心',
    overviewRewardsEyebrow: '奖励活动',
    overviewRewardsTitle: 'Lucky Streak 周末正在推动奖励包掉落、额外转轴和任务派奖。',
    overviewRewardsDescription:
      '把视线留在奖励循环里，在活动计时结束前切进抽奖玩法并清掉当前任务轨道。',
    overviewRewardsPrimary: '打开奖励中心',
    overviewRewardsSecondary: '打开老虎机页面',
    overviewCommunityEyebrow: '俱乐部公告',
    overviewCommunityTitle: '社区热帖、公平性证明和热门讨论正在同一轮里同步升温。',
    overviewCommunityDescription:
      '一边看玩家在聊什么，一边检查已发布的公平性证明，再切进当前被讨论最多的玩法路由。',
    overviewCommunityPrimary: '打开社区',
    overviewCommunitySecondary: '打开公平性验证页',
    overviewPulseTitle: '玩家热度',
    overviewPulseDescription:
      '先看清哪条路线最活跃，再决定进入哪一局。',
    overviewQueueTitle: '活动队列',
    overviewQueueDescription: '左右切换当前活动栏目，再直接跳进对应的玩法或功能路由。',
    overviewSignalsTitle: '实时信号',
    overviewSignalsDescription: '在进入市场、牌桌或奖励前，先看一眼当前活动对应的状态快照。',
    profileWalletEyebrow: '我的钱包',
    profileWalletDescription:
      '把点券余额、奖励储备、出款工具和最近账本变动集中在一个钱包总览里。',
    profileTotalBalanceLabel: '总余额',
    profileLockedBalanceLabel: '锁定余额',
    profileQuickActionsTitle: '快捷入口',
    profileRecentActivityTitle: '账本',
    profileRecentActivityDescription: '展示奖励、牌桌和市场带来的最近余额变动。',
    profileNoRecentActivity: '还没有最近的余额变动。',
    profileAccountEyebrow: '账户',
    profileAccountDescription:
      '把验证、安全和出款准备度收进一个个人中心里。',
    profileVerificationSummaryTitle: '验证状态',
    profileSecuritySummaryTitle: '安全',
    profilePayoutSummaryTitle: '奖励与出款',
    profileCurrentDeviceTitle: '当前设备',
    profileTierLabel: '信任等级',
    lobbyTitle: '精选牌桌',
    lobbyDescription:
      '独立玩法页覆盖桌游、快节奏回合、奖励抽取和市场头寸。',
    routePlayersLabel: '活跃玩家',
    routeRewardRangeLabel: '奖励区间',
    routeRiskLabel: '风险等级',
    riskLow: '低风险',
    riskMedium: '中风险',
    riskHigh: '高风险',
    routesTitle: '玩法入口',
    routesDescription:
      '玩法已经从首页拆出去。账户首页只保留钱包、奖励和安全能力，具体玩法走各自独立路由。',
    accountRoutesTitle: '账户路由',
    accountRoutesDescription:
      '把经济钱包、奖励和会话控制拆成独立 route container，不再继续堆在一个页面里。',
    routeLockedHint: '你现在可以先打开页面，但在邮箱验证完成前，抽卡和下注仍然会被拦截。',
    gachaTitle: '老虎机',
    gachaDescription:
      '三轴演出、保底进度和公平性证明统一放到 `/app/slot`。',
    gachaOpen: '打开老虎机页面',
    quickEightTitle: '快八',
    quickEightDescription: '8 选号码、即时开奖和派奖流程统一放到 `/app/quick-eight`。',
    quickEightOpen: '打开快八页面',
    holdemTitle: '德州扑克',
    holdemDescription:
      '在 `/app/holdem` 创建或加入多人娱乐局或现金桌，自选人数后按 preflop / flop / turn / river 顺序推进。',
    holdemOpen: '打开德州牌桌',
    blackjackTitle: '二十一点',
    blackjackDescription: '接入同桌 AI 智能荷官的二十一点已拆到独立页面 `/app/blackjack`。',
    blackjackOpen: '打开二十一点页面',
    marketsTitle: '预测市场',
    marketsDescription:
      '在 `/app/markets` 打开实时头寸、跟踪热度事件并参与市场结算。',
    marketsOpen: '打开预测市场',
    marketsStatus: '市场在线',
    fairnessTitle: '公平性验证器',
    fairnessDescription:
      '把 commit-reveal 独立拆到 `/app/fairness`，可单独 reveal 已结束 epoch，并在本地验证 `SHA-256(seed)` 是否匹配已公布 commit。',
    fairnessOpen: '打开公平性验证页',
    fairnessStatus: '公开证明',
    rewardsRouteTitle: '奖励中心',
    rewardsRouteDescription:
      '把任务进度和奖励领取独立成页，不再和经济钱包或安全控制混在一起。',
    rewardsRouteOpen: '打开奖励中心',
    rewardsRouteStatus: '任务中心',
    walletRouteTitle: '经济钱包',
    walletRouteDescription:
      '把资产余额、送礼活动和只读礼物包目录放到独立的钱包容器页。',
    walletRouteOpen: '打开经济钱包',
    walletRouteStatus: '经济体系在线',
    paymentsRouteTitle: '出款操作',
    paymentsRouteDescription:
      '把银行卡、加密收款地址和提现申请放到独立的支付路由。',
    paymentsRouteOpen: '打开出款操作',
    paymentsRouteStatus: '出款工具',
    securityRouteTitle: '安全中心',
    securityRouteDescription:
      '把邮箱/手机号验证和会话撤销拆到单独安全页。',
    securityRouteOpen: '打开安全中心',
    securityRouteStatus: '访问控制',
    verificationRouteTitle: 'KYC 认证',
    verificationRouteDescription:
      '上传实名材料、跟踪审核状态，并查看当前等级解锁了哪些玩法与提现能力。',
    verificationRouteOpen: '打开 KYC 页面',
    verificationRouteStatus: '身份等级',
    financeUnlocked: '高信任操作已解锁',
    financeLocked: '更高信任级别的账户操作需要先完成手机号验证。',
    securityHeroEyebrow: '安全中心',
    securityHeroTitle: '在进入高信任玩法前，先把账户锁稳。',
    securityHeroDescription:
      '把邮箱、手机号、会话和身份审核收进同一条受保护路由，让钱包相关动作看起来像金库防线，而不是埋在设置里的表单。',
    securitySummaryLevel: '安全等级',
    securitySummaryChecks: '已启用校验',
    securitySummarySessions: '活跃会话',
    securitySummaryAccess: '抽奖权限',
    securityTierPending: '基础等级',
    securityTierActive: '已验证等级',
    securityTierAdvanced: '防护等级',
    securityIdentityTitle: '身份与信任',
    securityIdentityDescription:
      '先在这里完成轻量校验；只有当提现或受限活动要求更高信任级别时，再进入完整 KYC。',
    securityEmailStepTitle: '邮箱关卡',
    securityEmailStepDescription:
      '确认当前绑定邮箱，让抽奖、奖励领取和找回链接都稳定绑定到你的玩家账户。',
    securityPhoneStepTitle: '手机号关卡',
    securityPhoneStepDescription:
      '在提现、出款信息修改或账户找回前，先补齐已验证手机号。',
    securityVerificationRouteDescription:
      '当你需要更高提现额度或活动权限时，再进入身份审核路由。',
    securityDefenseTitle: '账户防线',
    securityDefenseDescription:
      '集中查看当前已生效的防护层，以及这台设备什么时候失效。',
    securityDefenseEmail: '邮箱锁',
    securityDefensePhone: '手机锁',
    securityDefenseSessions: '会话监控',
    securityDefenseExpires: '当前设备过期时间',
    securityGuardTitle: '防护栈',
    securityGuardDescription:
      '把每一层都当成闸门。轻量校验先解锁日常玩法，更强的身份证明再保护钱包动作和账户找回。',
    securityGuardEmail:
      '邮箱验证会把奖励领取、抽奖流程和重置链接牢牢绑定到账户本身。',
    securityGuardPhone:
      '手机号验证会解锁更高信任级别的钱包动作，并为账户恢复提供第二重校验。',
    securityGuardSessions:
      '会话审查让你能在旧设备演变成出款或设置风险之前先把它踢掉。',
    securityRiskTitle: '风险提示',
    securityRiskDescription:
      '只要设备、浏览器或网络看起来不熟悉，就先撤销它，再刷新当前会话。只有在产品明确要求更高身份等级时，才进入完整 KYC。',
    sendEmail: '发送验证邮件',
    phoneLabel: '手机号',
    phonePlaceholder: '+86 13800138000',
    codeLabel: '短信验证码',
    codePlaceholder: '6 位验证码',
    sendCode: '发送验证码',
    confirmPhone: '确认手机号',
    verificationEmailSent: '验证邮件已重新发起。如果账号还未验证，请检查当前绑定邮箱。',
    phoneCodeSent: '验证码已发送，请输入短信中的 6 位验证码完成绑定。',
    phoneVerifiedNotice: '手机号验证完成，更高信任级别的账户操作现已可用。',
    walletTitle: '金库',
    walletDescription: '在一个页面里管理游戏点券、保护余额、送礼工具和钱包活动流水。',
    currentBalance: '当前 B luck',
    topUpAmount: '充值金额',
    referenceId: '参考单号',
    referencePlaceholder: '可选，填写转账流水或支付参考号',
    createTopUp: '创建充值申请',
    topUpCreated: '充值申请已提交。该笔单据会先经过渠道与结算状态，再在入账后更新余额。',
    recentTopUps: '最近充值申请',
    noTopUps: '还没有充值申请。',
    cryptoDepositTitle: '加密货币充值通道',
    cryptoDepositDescription:
      '先按页面展示的钱包地址转账，再提交 txHash 进入人工审核。',
    depositChannel: '充值通道',
    depositChannelPlaceholder: '请选择加密充值通道',
    depositTxHash: '交易哈希',
    depositFromAddress: '付款地址',
    submitCryptoDeposit: '提交加密充值认领',
    cryptoDepositCreated:
      '加密充值认领已提交。财务会先核对链上转账，再把余额记入钱包。',
    noCryptoChannels: '当前还没有启用中的加密充值通道。',
    recentCryptoDeposits: '最近加密充值',
    noCryptoDeposits: '还没有加密充值认领。',
    paymentsTitle: '银行卡与提现',
    paymentsDescription: '绑定出款银行卡、设置默认卡，并提交提现申请。',
    addCard: '新增银行卡',
    cardholderName: '持卡人姓名',
    bankName: '银行名称',
    cardBrand: '卡组织/类型',
    last4: '卡号后四位',
    saveCard: '保存银行卡',
    cardSaved: '银行卡已保存。',
    noCards: '还没有保存任何银行卡。',
    defaultCard: '默认卡',
    setDefault: '设为默认',
    defaultCardUpdated: '默认银行卡已更新。',
    withdrawalAmount: '提现金额',
    payoutCard: '出款银行卡',
    payoutCardPlaceholder: '请选择已保存的银行卡',
    requestWithdrawal: '提交提现申请',
    withdrawalCreated: '提现申请已提交。对应金额会先保留，再进入审核与打款状态。',
    recentWithdrawals: '最近提现申请',
    noWithdrawals: '还没有提现申请。',
    cryptoAddressTitle: '加密提现地址',
    cryptoAddressDescription:
      '按链和币种保存收款地址，再发起加密提现申请。',
    cryptoChain: '链',
    cryptoNetwork: '网络',
    cryptoToken: '币种',
    cryptoAddress: '钱包地址',
    cryptoLabel: '地址备注',
    saveCryptoAddress: '保存加密地址',
    cryptoAddressSaved: '加密提现地址已保存。',
    noCryptoAddresses: '还没有保存任何加密提现地址。',
    setDefaultAddress: '设为默认地址',
    defaultCryptoAddressUpdated: '默认加密提现地址已更新。',
    cryptoWithdrawalAmount: '加密提现金额',
    cryptoWithdrawalAddress: '加密收款地址',
    cryptoWithdrawalAddressPlaceholder: '请选择已保存的加密地址',
    requestCryptoWithdrawal: '提交加密提现申请',
    cryptoWithdrawalCreated:
      '加密提现申请已提交。对应金额会先锁定，待链上转账确认后再完成。',
    recentCryptoWithdrawals: '最近加密提现',
    noCryptoWithdrawals: '还没有加密提现申请。',
    transactionsTitle: '账本流水',
    transactionsDescription: '展示奖励、市场结算和受保护钱包动作带来的最近 B luck 余额变化。',
    noTransactions: '还没有账本流水。',
    sessionsTitle: '活跃会话',
    sessionsDescription: '查看当前活跃设备，并在需要时撤销访问。',
    noSessions: '没有查询到活跃会话。',
    refresh: '刷新',
    revoke: '撤销',
    signOutThisDevice: '退出当前设备',
    signOutEverywhere: '全部设备退出',
    currentDevice: '当前设备',
    activeSession: '活跃会话',
    thisDeviceRevoked: '当前设备已退出，正在跳转登录页。',
    sessionRevoked: '会话已撤销。',
    allSessionsRevoked: '所有活跃会话都已撤销，正在跳转登录页。',
    createdAt: '创建时间',
    status: '状态',
    amount: '金额',
    type: '类型',
    before: '变更前',
    after: '变更后',
    reference: '关联单据',
    device: '设备',
    expires: '过期时间',
    unknown: '未知',
    noSelection: '还没有默认出款卡。',
    submitMissing: '请先补全必填字段。',
    loadFailed: '加载用户中心数据失败。',
    retry: '重试',
    rewardClaimed: '奖励已领取，任务进度和奖励余额已刷新。',
    verificationBanner: '邮箱验证会解锁抽奖；手机号验证会保护更高信任级别的账户操作。',
    verified: '已验证',
    pending: '待处理',
    topUpSectionLabel: '充值会按 requested、provider pending、settled、credited 的顺序推进，真正入账前不会改余额。',
    withdrawalSectionLabel: '提现会先保留金额，再进入 approved、paying、paid 或 reversed 等状态。',
  },
} satisfies Record<Locale, Record<string, string>>;

export type UserDashboardCopy =
  (typeof userDashboardCopy)[keyof typeof userDashboardCopy];
