import { StyleSheet } from "react-native";

import {
  mobileChromeTheme,
  mobileGameTheme,
  mobileLayoutTheme,
  mobileOverlayTheme,
  mobilePalette as palette,
  mobileRadii,
  mobileSpacing,
  mobileSurfaceTheme,
  mobileTypography,
  mobileTypeScale,
} from "../theme";

export const gachaRouteScreenStyles = StyleSheet.create({
  bigWinOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: mobileSpacing["4xl"],
  },
  bigWinBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: mobileOverlayTheme.backdrop,
  },
  bigWinCard: {
    position: "relative",
    width: "100%",
    maxWidth: 388,
    gap: mobileSpacing.lg,
    overflow: "hidden",
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingVertical: mobileLayoutTheme.cardPaddingLg,
    ...mobileChromeTheme.cardShadow,
  },
  bigWinBurst: {
    position: "absolute",
    top: -72,
    left: "50%",
    width: 260,
    height: 260,
    marginLeft: -130,
    borderRadius: 130,
    opacity: 0.16,
  },
  bigWinBurstEcho: {
    position: "absolute",
    top: -92,
    left: "50%",
    width: 300,
    height: 300,
    marginLeft: -150,
    borderRadius: 150,
    borderWidth: 12,
    opacity: 0.55,
  },
  bigWinHeader: {
    alignItems: "center",
    gap: mobileSpacing.md,
  },
  bigWinRarityBadge: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 6,
    ...mobileChromeTheme.cardShadowSm,
  },
  bigWinRarityBadgeText: {
    color: "#241605",
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  bigWinTitle: {
    color: palette.accent,
    fontSize: mobileTypeScale.fontSize.hero + 8,
    lineHeight: mobileTypeScale.lineHeight.hero + 8,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "uppercase",
  },
  bigWinBody: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
    textAlign: "center",
  },
  bigWinRewardPanel: {
    alignItems: "center",
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileOverlayTheme.warmTint,
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingVertical: mobileLayoutTheme.cardPadding,
    ...mobileChromeTheme.cardShadowSm,
  },
  bigWinRewardLabel: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  bigWinRewardValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.metric,
    lineHeight: mobileTypeScale.fontSize.metric,
    fontWeight: "800",
  },
  bigWinRewardMeta: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
    textAlign: "center",
  },
  bigWinActionStack: {
    gap: mobileSpacing.md,
  },
  streakBanner: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: mobileSpacing.lg,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: "#261d0d",
    padding: mobileLayoutTheme.cardPadding,
    ...mobileChromeTheme.cardShadow,
  },
  streakCopy: {
    flex: 1,
    gap: mobileSpacing.xs,
  },
  streakLabel: {
    color: palette.accent,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  streakValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.metric,
    lineHeight: mobileTypeScale.fontSize.metric + 4,
    fontWeight: "800",
  },
  streakMeta: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    lineHeight: mobileTypeScale.lineHeight.label,
  },
  streakRewardCard: {
    maxWidth: 156,
    justifyContent: "center",
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  streakRewardText: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
    fontWeight: "800",
  },
  slotLandingShell: {
    gap: mobileSpacing.lg,
  },
  slotLandingBanner: {
    position: "relative",
    gap: mobileSpacing["2xs"],
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: "#261d0d",
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingVertical: mobileLayoutTheme.cardPadding,
    ...mobileChromeTheme.cardShadow,
  },
  slotLandingBannerLabel: {
    color: palette.accent,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    textTransform: "uppercase",
  },
  slotLandingBannerValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.metric - 2,
    lineHeight: mobileTypeScale.fontSize.metric + 2,
    fontWeight: "800",
  },
  slotLandingBannerBadge: {
    position: "absolute",
    right: mobileSpacing.xl,
    top: mobileSpacing.lg,
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileGameTheme.quickEight.selected.backgroundColor,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.sm,
    ...mobileChromeTheme.cardShadowSm,
  },
  slotLandingBannerBadgeText: {
    color: "#241605",
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  slotLandingCabinet: {
    alignItems: "center",
    gap: mobileSpacing.lg,
    borderRadius: mobileRadii.xl + 10,
    borderWidth: 4,
    borderColor: palette.border,
    backgroundColor: "#46151f",
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingBottom: mobileLayoutTheme.cardPadding,
    paddingTop: mobileSpacing["6xl"],
    ...mobileChromeTheme.cardShadow,
  },
  slotLandingMarquee: {
    marginTop: -52,
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.accent,
    paddingHorizontal: mobileSpacing["5xl"],
    paddingVertical: mobileSpacing.md,
    ...mobileChromeTheme.cardShadowSm,
  },
  slotLandingMarqueeText: {
    color: "#241605",
    fontSize: mobileTypeScale.fontSize.titleSm,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    textTransform: "uppercase",
  },
  slotLandingTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.hero - 2,
    lineHeight: mobileTypeScale.lineHeight.hero,
    fontWeight: "800",
    textAlign: "center",
  },
  slotLandingBody: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
    textAlign: "center",
  },
  slotLandingReelRow: {
    flexDirection: "row",
    gap: 10,
    alignSelf: "stretch",
  },
  slotLandingReel: {
    flex: 1,
    alignItems: "center",
    gap: mobileSpacing.md,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileSurfaceTheme.reelPanel,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  slotLandingSymbolPlate: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
  },
  slotLandingSymbolGlyph: {
    fontSize: mobileTypeScale.fontSize.metric - 2,
    fontWeight: "800",
  },
  slotLandingSymbolLabel: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  slotLandingMetricRow: {
    flexDirection: "row",
    gap: 10,
    alignSelf: "stretch",
  },
  slotLandingMetricCard: {
    flex: 1,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.md,
    ...mobileChromeTheme.cardShadowSm,
  },
  slotLandingMetricCardPaper: {
    backgroundColor: palette.panelMuted,
  },
  slotLandingMetricCardGold: {
    backgroundColor: "#2d220f",
  },
  slotLandingMetricCardBlue: {
    backgroundColor: "#162840",
  },
  slotLandingMetricLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  slotLandingMetricValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  slotLandingModeCard: {
    alignSelf: "stretch",
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileSurfaceTheme.insetPanel,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  slotLandingModeLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    textTransform: "uppercase",
  },
  slotLandingModeValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  stageStatusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileSpacing.lg,
  },
  stageStatusCard: {
    flex: 1,
    minWidth: 100,
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: mobileSpacing.md,
    ...mobileChromeTheme.cardShadowSm,
  },
  stageStatusCardPaper: {
    backgroundColor: palette.panelMuted,
  },
  stageStatusCardGold: {
    backgroundColor: "#2d220f",
  },
  stageStatusCardBlue: {
    backgroundColor: "#162840",
  },
  stageStatusCardPeach: {
    backgroundColor: "#2d1719",
  },
  stageStatusLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  stageStatusValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  stageActionStack: {
    gap: mobileSpacing.md,
  },
  stageActionRow: {
    flexDirection: "row",
    gap: mobileSpacing.lg,
  },
  stageActionCell: {
    flex: 1,
  },
  stageHintCard: {
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileSurfaceTheme.insetPanel,
    paddingHorizontal: mobileSpacing.xl,
    paddingVertical: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  stageHintText: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.body,
    lineHeight: mobileTypeScale.lineHeight.body,
    textAlign: "center",
  },
  capsuleCard: {
    gap: mobileSpacing.lg,
    borderRadius: mobileRadii.xl + 8,
    borderWidth: mobileChromeTheme.borderWidth,
    padding: mobileLayoutTheme.cardPadding,
    ...mobileChromeTheme.cardShadow,
  },
  capsuleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  capsuleTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleSm,
    fontWeight: "800",
  },
  costPill: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.accent,
    paddingHorizontal: 14,
    paddingVertical: 8,
    ...mobileChromeTheme.cardShadowSm,
  },
  costPillText: {
    color: "#241605",
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
  },
  capsuleStage: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 280,
  },
  capsuleStageHalo: {
    width: 256,
    height: 256,
    borderRadius: 128,
    borderWidth: 8,
    borderColor: palette.border,
    backgroundColor: "#1d315f",
  },
  capsuleOrb: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
  },
  capsuleOrbLeft: {
    width: 92,
    height: 92,
    left: 72,
    top: 76,
  },
  capsuleOrbCenter: {
    width: 104,
    height: 104,
    top: 98,
  },
  capsuleOrbRight: {
    width: 92,
    height: 92,
    right: 72,
    top: 122,
  },
  capsuleOrbGlyph: {
    fontSize: 34,
    fontWeight: "800",
  },
  capsuleOrbGlyphCenter: {
    fontSize: 40,
    fontWeight: "800",
  },
  reelPreviewRow: {
    flexDirection: "row",
    gap: 10,
  },
  reelPreview: {
    flex: 1,
    gap: 8,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileSurfaceTheme.reelPanel,
    padding: 10,
  },
  reelPreviewLocked: {
    ...mobileGameTheme.slot.shadows.reelLocked,
  },
  reelCell: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 12,
    borderWidth: mobileChromeTheme.borderWidth,
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  reelCellCenter: {
    transform: [{ scale: 1.04 }],
    ...mobileChromeTheme.cardShadowSm,
  },
  reelCellSide: {
    opacity: 0.8,
  },
  reelCellGlyph: {
    fontSize: 22,
    fontWeight: "800",
  },
  reelCellLabel: {
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
  },
  metaGrid: {
    gap: mobileSpacing.md,
  },
  metaCard: {
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  metaCardWarm: {
    backgroundColor: "#32210f",
  },
  metaCardBlue: {
    backgroundColor: "#162840",
  },
  metaCardPaper: {
    backgroundColor: palette.panelMuted,
  },
  metaCardLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  metaCardValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  metaCardHash: {
    color: palette.accentMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontFamily: mobileTypography.mono,
  },
  featuredGrid: {
    gap: mobileSpacing.md,
  },
  featuredCard: {
    gap: mobileSpacing.md,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  featuredHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  rarityBadge: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#0d1420",
  },
  rarityBadgeText: {
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  featuredName: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  featuredReward: {
    color: palette.accentMuted,
    fontSize: mobileTypeScale.fontSize.body,
    fontWeight: "700",
  },
  featuredStock: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
  },
  resultsStack: {
    gap: mobileSpacing.lg,
  },
  latestSummaryGrid: {
    gap: mobileSpacing.md,
  },
  latestSummaryCard: {
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  latestSummaryCardGold: {
    backgroundColor: "#2d220f",
  },
  latestSummaryCardWarm: {
    backgroundColor: "#32210f",
  },
  latestSummaryCardBlue: {
    backgroundColor: "#162840",
  },
  latestSummaryLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "700",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  latestSummaryValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleBase,
    fontWeight: "800",
  },
  revealCard: {
    overflow: "hidden",
    borderRadius: mobileRadii.xl + 6,
    borderWidth: mobileChromeTheme.borderWidth,
    ...mobileChromeTheme.cardShadow,
  },
  revealHero: {
    position: "relative",
    alignItems: "center",
    gap: mobileSpacing.md,
    minHeight: 264,
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingVertical: mobileLayoutTheme.cardPaddingLg,
    borderBottomWidth: mobileChromeTheme.borderWidth,
    borderBottomColor: palette.border,
  },
  revealBurst: {
    position: "absolute",
    width: 216,
    height: 216,
    borderRadius: 108,
    opacity: 0.14,
  },
  revealBurstEcho: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 10,
    opacity: 0.55,
  },
  revealRarityBadge: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 6,
    ...mobileChromeTheme.cardShadowSm,
  },
  revealRarityBadgeText: {
    color: "#241605",
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  revealKicker: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.caps,
    textTransform: "uppercase",
  },
  revealTitle: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.hero + 2,
    lineHeight: mobileTypeScale.lineHeight.hero + 2,
    fontWeight: "800",
    textAlign: "center",
  },
  revealBody: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
    textAlign: "center",
  },
  revealRewardPanel: {
    minWidth: 184,
    alignItems: "center",
    gap: mobileSpacing.sm,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: mobileLayoutTheme.cardPadding,
    paddingVertical: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  revealRewardLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  revealRewardValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.hero,
    lineHeight: mobileTypeScale.lineHeight.hero,
    fontWeight: "800",
  },
  revealBodyPanel: {
    gap: mobileSpacing.lg,
    backgroundColor: palette.panel,
    padding: mobileLayoutTheme.cardPadding,
  },
  revealMetaGrid: {
    gap: mobileSpacing.md,
  },
  revealMetaCard: {
    gap: mobileSpacing.xs,
    borderRadius: mobileRadii.xl,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  revealMetaWarm: {
    backgroundColor: "#32210f",
  },
  revealMetaBlue: {
    backgroundColor: "#162840",
  },
  revealMetaPaper: {
    backgroundColor: palette.panelMuted,
  },
  revealMetaLabel: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    fontWeight: "800",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
    textTransform: "uppercase",
  },
  revealMetaValue: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.titleSm,
    lineHeight: mobileTypeScale.lineHeight.bodyRelaxed,
    fontWeight: "800",
  },
  revealMetaCaption: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    lineHeight: mobileTypeScale.lineHeight.label,
  },
  revealActionStack: {
    gap: mobileSpacing.md,
  },
  resultGrid: {
    gap: mobileSpacing.md,
  },
  resultCard: {
    gap: mobileSpacing["2xs"],
    borderRadius: mobileRadii.lg,
    borderWidth: mobileChromeTheme.borderWidth,
    padding: mobileSpacing.lg,
    ...mobileChromeTheme.cardShadowSm,
  },
  resultStatus: {
    color: palette.textMuted,
    fontSize: mobileTypeScale.fontSize.labelXs,
    textTransform: "uppercase",
    letterSpacing: mobileTypeScale.letterSpacing.subtle,
  },
  resultName: {
    color: palette.text,
    fontSize: mobileTypeScale.fontSize.bodyLg,
    fontWeight: "800",
  },
  resultReward: {
    color: palette.accentMuted,
    fontSize: mobileTypeScale.fontSize.labelSm,
    fontWeight: "700",
  },
});
