import { StyleSheet } from "react-native";

import { mobileFeedbackTheme, mobilePalette as palette } from "../theme";

export const holdemRouteScreenStyles = StyleSheet.create({
  actionButtonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  actionPanel: {
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
  },
  bestHandLabel: {
    color: mobileFeedbackTheme.success.accentColor,
    fontSize: 13,
    fontWeight: "600",
  },
  boardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  cardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  emptyStateLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  fieldStack: {
    gap: 14,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.input,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  choiceChipActive: {
    borderColor: palette.accent,
    backgroundColor: "#103246",
  },
  choiceChipDisabled: {
    opacity: 0.55,
  },
  choiceChipLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  choiceChipLabelActive: {
    color: palette.text,
  },
  realtimeBanner: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#38bdf833",
    backgroundColor: "#0c4a6e33",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  realtimeBannerLabel: {
    color: "#dbeafe",
    fontSize: 13,
    fontWeight: "600",
  },
  lobbyCard: {
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
  },
  lobbyCardActive: {
    borderColor: palette.accent,
    backgroundColor: "#103246",
  },
  lobbyCardBody: {
    flex: 1,
    gap: 4,
  },
  lobbyCardCount: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "700",
  },
  lobbyCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  lobbyCardMeta: {
    color: palette.textMuted,
    fontSize: 13,
  },
  lobbyCardTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  lobbyList: {
    gap: 10,
  },
  placeholderCard: {
    width: 64,
    height: 92,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: palette.border,
    backgroundColor: palette.input,
  },
  placeholderCardLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  playingCard: {
    width: 64,
    height: 92,
    justifyContent: "space-between",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#fffdf7",
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  playingCardBack: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textAlign: "center",
  },
  playingCardHidden: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.input,
  },
  playingCardLabel: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
  },
  playingCardLabelRed: {
    color: "#be123c",
  },
  playingCardSuit: {
    alignSelf: "flex-end",
    color: "#111827",
    fontSize: 20,
    fontWeight: "700",
  },
  potCard: {
    flex: 1,
    minWidth: 120,
    gap: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0f172a",
    padding: 12,
  },
  potCardWide: {
    flex: 1,
    gap: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0f172a",
    padding: 12,
  },
  potGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  potLabel: {
    color: palette.textMuted,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  potValue: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "800",
  },
  tableChatAuthor: {
    color: palette.text,
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  tableChatBody: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
  },
  tableChatBubble: {
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tableChatBubbleHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  tableChatCard: {
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
  },
  tableChatComposer: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  tableChatEmojiButton: {
    alignItems: "center",
    backgroundColor: palette.input,
    borderColor: palette.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minWidth: 44,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  tableChatEmojiButtonDisabled: {
    opacity: 0.45,
  },
  tableChatEmojiLabel: {
    fontSize: 20,
  },
  tableChatEmojiRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tableChatHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  tableChatHint: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  tableChatInput: {
    flex: 1,
    marginBottom: 0,
  },
  tableChatList: {
    gap: 10,
  },
  tableChatMeta: {
    color: palette.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  tableChatTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  recentHandCard: {
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
  },
  recentHandHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  recentHandHeaderActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  recentHandMeta: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  recentHandPot: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "700",
  },
  recentHandsList: {
    gap: 10,
  },
  recentHandsTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  recentHandTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "700",
  },
  replayBlock: {
    gap: 10,
  },
  replayCard: {
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#38bdf833",
    backgroundColor: "#082f491a",
    padding: 14,
  },
  replayErrorCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: mobileFeedbackTheme.dangerButton.borderColor,
    backgroundColor: mobileFeedbackTheme.dangerButton.backgroundColor,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  replayErrorLabel: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
  },
  replayEventCard: {
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
  },
  replayEventHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayEventHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayEventList: {
    gap: 10,
  },
  replayEventMeta: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  replayEventStamp: {
    alignItems: "flex-end",
    gap: 2,
  },
  replayEventStampText: {
    color: palette.textMuted,
    fontSize: 11,
  },
  replayEventTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayFairnessCard: {
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
  },
  replayFairnessValue: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
  },
  replayHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayMetaCard: {
    flex: 1,
    minWidth: 120,
    gap: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
  },
  replayMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  replayMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  replayMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayParticipantCard: {
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
  },
  replayParticipantHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayParticipantHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayParticipantList: {
    gap: 10,
  },
  replayParticipantMeta: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replayParticipantTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayParticipantWinner: {
    color: mobileFeedbackTheme.success.accentColor,
    fontSize: 12,
    fontWeight: "700",
  },
  replayPotCard: {
    flex: 1,
    minWidth: 120,
    gap: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
  },
  replayPotGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  replaySectionLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  replayStatusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  replayStatusLabel: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replaySubtitle: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replaySummaryRow: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  seatBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  seatCard: {
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
  },
  seatCardOpen: {
    borderStyle: "dashed",
  },
  seatCardTurn: {
    borderColor: mobileFeedbackTheme.warning.borderColor,
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  seatCardWinner: {
    borderColor: mobileFeedbackTheme.success.borderColor,
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
  },
  seatHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  seatHeaderBody: {
    flex: 1,
    gap: 8,
  },
  seatList: {
    gap: 12,
  },
  seatMetaCard: {
    flex: 1,
    minWidth: 90,
    gap: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0f172a",
    padding: 10,
  },
  seatMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  seatMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  seatMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  seatStateLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  seatTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "700",
  },
  statusChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.input,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusChipActive: {
    borderColor: palette.accent,
    backgroundColor: "#103246",
  },
  statusChipLabel: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  statusChipLabelActive: {
    color: palette.text,
  },
  tableHero: {
    gap: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#5d3412",
    backgroundColor: "#0f2d22",
    padding: 16,
  },
  tableHeroHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  tableHeroSubtitle: {
    color: "#cbd5e1",
    fontSize: 13,
  },
  tableHeroTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
  },
  tableMetaCard: {
    flex: 1,
    minWidth: 100,
    gap: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(2,6,23,0.42)",
    padding: 10,
  },
  tableMetaLabel: {
    color: "#94a3b8",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tableMetaValue: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
  },
});
