import { StyleSheet } from "react-native";

import {
  mobileChromeTheme,
  mobileFeedbackTheme,
  mobilePalette as palette,
} from "../theme";

export const holdemRouteScreenStyles = StyleSheet.create({
  actionButtonCell: {
    width: "30.5%",
  },
  actionButtonCellWide: {
    width: "47%",
  },
  actionButtonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  actionPanel: {
    gap: 18,
    borderRadius: 24,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 18,
    ...mobileChromeTheme.cardShadow,
  },
  actionAmountCard: {
    gap: 10,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  actionAmountLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  actionSummaryCard: {
    flex: 1,
    gap: 6,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  actionSummaryCardGold: {
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  actionSummaryLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  actionSummaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  actionSummaryValue: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "800",
  },
  actionSummaryValueGold: {
    color: mobileFeedbackTheme.warning.accentColor,
  },
  bestHandLabel: {
    color: mobileFeedbackTheme.success.accentColor,
    fontSize: 13,
    fontWeight: "700",
  },
  boardPlaceholderCard: {
    width: 64,
    height: 92,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderStyle: "dashed",
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
  },
  boardPlaceholderLabel: {
    color: palette.textMuted,
    fontSize: 24,
    fontWeight: "700",
  },
  boardRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  boardWrap: {
    gap: 10,
  },
  cardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...mobileChromeTheme.cardShadowSm,
  },
  choiceChipActive: {
    backgroundColor: mobileFeedbackTheme.active.backgroundColor,
  },
  choiceChipDisabled: {
    opacity: 0.55,
  },
  choiceChipLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  choiceChipLabelActive: {
    color: palette.text,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  emptyStateLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  fieldStack: {
    gap: 14,
  },
  lobbyActionMetaCard: {
    flex: 1,
    gap: 4,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  lobbyActionMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  lobbyActionMetaRow: {
    flexDirection: "row",
    gap: 10,
  },
  lobbyActionMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  lobbyActionStack: {
    gap: 12,
  },
  lobbyCard: {
    gap: 10,
    borderRadius: 20,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  lobbyCardActive: {
    backgroundColor: mobileFeedbackTheme.warningSoft.backgroundColor,
  },
  lobbyCardBody: {
    flex: 1,
    gap: 6,
  },
  lobbyCardCountBadge: {
    alignItems: "center",
    minWidth: 72,
    gap: 2,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 10,
    paddingVertical: 8,
    ...mobileChromeTheme.cardShadowSm,
  },
  lobbyCardCountLabel: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  lobbyCardCount: {
    color: palette.accentMuted,
    fontSize: 20,
    fontWeight: "800",
  },
  lobbyCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  lobbyCardMetaCard: {
    flex: 1,
    minWidth: 110,
    gap: 4,
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 10,
  },
  lobbyCardMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  lobbyCardMeta: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  lobbyCardMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  lobbyCardMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  lobbyCardTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  lobbyCardTitleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  lobbyList: {
    gap: 12,
  },
  lobbyStatusChip: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
    ...mobileChromeTheme.cardShadowSm,
  },
  lobbyStatusChipActive: {
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
  },
  lobbyStatusChipLabel: {
    color: palette.text,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  lobbyStatusChipWaiting: {
    backgroundColor: mobileFeedbackTheme.info.backgroundColor,
  },
  lobbySummaryCard: {
    flex: 1,
    gap: 6,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  lobbySummaryCardGold: {
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  lobbySummaryLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  lobbySummaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  lobbySummaryValue: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "800",
  },
  placeholderCard: {
    width: 64,
    height: 92,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderStyle: "dashed",
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
  },
  placeholderCardLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  playingCard: {
    width: 64,
    height: 92,
    justifyContent: "space-between",
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: "#fffdf7",
    paddingHorizontal: 10,
    paddingVertical: 9,
    ...mobileChromeTheme.cardShadowSm,
  },
  playingCardHero: {
    width: 94,
    height: 136,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    ...mobileChromeTheme.cardShadow,
  },
  playingCardCompact: {
    width: 50,
    height: 72,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  playingCardBack: {
    color: palette.accentMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textAlign: "center",
  },
  playingCardHidden: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2c1a12",
  },
  playingCardLabel: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
  },
  playingCardLabelHero: {
    fontSize: 22,
  },
  playingCardLabelRed: {
    color: "#be123c",
  },
  playingCardSuit: {
    alignSelf: "flex-end",
    color: "#111827",
    fontSize: 20,
    fontWeight: "700",
  },
  playingCardSuitHero: {
    fontSize: 32,
  },
  potCard: {
    flex: 1,
    minWidth: 120,
    gap: 6,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  potCardWide: {
    flex: 1,
    gap: 6,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  potGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  potLabel: {
    color: palette.textMuted,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  potValue: {
    color: palette.accentMuted,
    fontSize: 20,
    fontWeight: "800",
  },
  recentHandCard: {
    gap: 10,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  recentHandHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  recentHandHeaderActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  recentHandMeta: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  recentHandPot: {
    color: palette.accentMuted,
    fontSize: 15,
    fontWeight: "800",
  },
  recentHandsList: {
    gap: 12,
  },
  recentHandsTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  recentHandTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  realtimeBanner: {
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileFeedbackTheme.info.backgroundColor,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  realtimeBannerLabel: {
    color: mobileFeedbackTheme.info.accentColor,
    fontSize: 13,
    fontWeight: "700",
  },
  replayBlock: {
    gap: 10,
  },
  replayCard: {
    gap: 14,
    borderRadius: 20,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: "#201830",
    padding: 14,
    ...mobileChromeTheme.cardShadow,
  },
  replayErrorCard: {
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: mobileFeedbackTheme.danger.borderColor,
    backgroundColor: mobileFeedbackTheme.danger.backgroundColor,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayErrorLabel: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
  },
  replayEventCard: {
    gap: 10,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayEventHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayEventHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayEventList: {
    gap: 10,
  },
  replayEventMeta: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  replayEventStamp: {
    alignItems: "flex-end",
    gap: 2,
  },
  replayEventStampText: {
    color: palette.textMuted,
    fontSize: 11,
  },
  replayEventTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  replayFairnessCard: {
    gap: 8,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayFairnessValue: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
  },
  replayHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayMetaCard: {
    flex: 1,
    minWidth: 120,
    gap: 4,
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  replayMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  replayMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayParticipantCard: {
    gap: 10,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayParticipantHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  replayParticipantHeaderBody: {
    flex: 1,
    gap: 4,
  },
  replayParticipantList: {
    gap: 10,
  },
  replayParticipantMeta: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replayParticipantTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  replayParticipantWinner: {
    color: mobileFeedbackTheme.success.accentColor,
    fontSize: 12,
    fontWeight: "800",
  },
  replayPotCard: {
    flex: 1,
    minWidth: 120,
    gap: 6,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayPotGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  replaySectionLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  replayStatusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 16,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...mobileChromeTheme.cardShadowSm,
  },
  replayStatusLabel: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replaySubtitle: {
    color: palette.textMuted,
    fontSize: 13,
  },
  replaySummaryRow: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  replayTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  seatBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  seatCard: {
    gap: 12,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 14,
    ...mobileChromeTheme.cardShadowSm,
  },
  seatCardOpen: {
    borderStyle: "dashed",
    backgroundColor: palette.panelMuted,
  },
  seatCardTurn: {
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  seatCardWinner: {
    backgroundColor: mobileFeedbackTheme.success.backgroundColor,
  },
  seatHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  seatHeaderBody: {
    flex: 1,
    gap: 8,
  },
  seatList: {
    gap: 12,
  },
  seatMetaCard: {
    flex: 1,
    minWidth: 90,
    gap: 4,
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 10,
  },
  seatMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  seatMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  seatMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  seatStateLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  seatTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  stageChip: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...mobileChromeTheme.cardShadowSm,
  },
  stageChipFairness: {
    backgroundColor: palette.panelMuted,
  },
  stageChipGold: {
    backgroundColor: mobileFeedbackTheme.warning.backgroundColor,
  },
  stageChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stageChipText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
  },
  statusChip: {
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusChipActive: {
    backgroundColor: mobileFeedbackTheme.info.backgroundColor,
  },
  statusChipLabel: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statusChipLabelActive: {
    color: palette.text,
  },
  tableChatAuthor: {
    color: palette.text,
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  tableChatBody: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
  },
  tableChatBubble: {
    gap: 8,
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableChatBubbleHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  tableChatCard: {
    gap: 12,
    borderRadius: 20,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 14,
    ...mobileChromeTheme.cardShadow,
  },
  tableChatComposer: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  tableChatEmojiButton: {
    alignItems: "center",
    backgroundColor: palette.panel,
    borderColor: palette.border,
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    justifyContent: "center",
    minWidth: 44,
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableChatEmojiButtonDisabled: {
    opacity: 0.45,
  },
  tableChatEmojiLabel: {
    fontSize: 20,
  },
  tableChatEmojiRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tableChatHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  tableChatHint: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  tableChatInput: {
    flex: 1,
    marginBottom: 0,
  },
  tableChatList: {
    gap: 10,
  },
  tableChatMeta: {
    color: palette.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  tableChatTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  tableHero: {
    gap: 18,
    borderRadius: 24,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 18,
    ...mobileChromeTheme.cardShadow,
  },
  tableHeroHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  tableHeroJoinPrompt: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 96,
    borderRadius: 18,
    borderWidth: mobileChromeTheme.borderWidth,
    borderStyle: "dashed",
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tableHeroJoinPromptText: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  tableHeroSubtitle: {
    color: palette.textMuted,
    fontSize: 13,
  },
  tableHeroTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "800",
  },
  tableMetaCard: {
    flex: 1,
    minWidth: 100,
    gap: 4,
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    padding: 10,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableMetaLabel: {
    color: palette.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tableMetaValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  tablePotBadge: {
    alignSelf: "center",
    gap: 4,
    borderRadius: 22,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panelMuted,
    paddingHorizontal: 28,
    paddingVertical: 12,
    ...mobileChromeTheme.cardShadow,
  },
  tablePotLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textAlign: "center",
    textTransform: "uppercase",
  },
  tablePotValue: {
    color: palette.accentMuted,
    fontSize: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  tableSurface: {
    gap: 16,
    borderRadius: 42,
    borderWidth: 4,
    borderColor: palette.border,
    backgroundColor: "#173622",
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 18,
    minHeight: 540,
    ...mobileChromeTheme.cardShadow,
  },
  tableSurfaceFairnessBadge: {
    position: "absolute",
    top: -16,
    right: 12,
    gap: 2,
    borderRadius: 22,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceFairnessKicker: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  tableSurfaceFairnessValue: {
    color: mobileFeedbackTheme.info.accentColor,
    fontSize: 14,
    fontWeight: "800",
  },
  tableSurfaceHeroAvatar: {
    width: 88,
    height: 88,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 44,
    borderWidth: 4,
    borderColor: palette.border,
    backgroundColor: "#5a2b12",
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceHeroAvatarGlyph: {
    color: palette.accent,
    fontSize: 38,
    fontWeight: "800",
  },
  tableSurfaceHeroCards: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginBottom: 2,
  },
  tableSurfaceHeroLabel: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 18,
    paddingVertical: 8,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceHeroSeat: {
    gap: 10,
    marginTop: "auto",
    paddingTop: 12,
  },
  tableSurfaceHeroStatus: {
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: mobileFeedbackTheme.info.backgroundColor,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  tableSurfaceInner: {
    position: "absolute",
    top: 20,
    right: 20,
    bottom: 20,
    left: 20,
    borderRadius: 34,
    borderWidth: 3,
    borderColor: "#2b5a37",
  },
  tableSurfaceTopAvatar: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 36,
    borderWidth: 4,
    borderColor: palette.border,
    backgroundColor: "#1f6674",
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceTopAvatarLabel: {
    color: "#e9fbff",
    fontSize: 28,
    fontWeight: "800",
  },
  tableSurfaceTopCards: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 4,
  },
  tableSurfaceTopName: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 14,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 16,
    paddingVertical: 8,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceTopSeat: {
    alignItems: "center",
    gap: 10,
    paddingTop: 28,
  },
  tableSurfaceTopStack: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: mobileChromeTheme.borderWidth,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    paddingHorizontal: 16,
    paddingVertical: 6,
    ...mobileChromeTheme.cardShadowSm,
  },
  tableSurfaceTiltLeft: {
    marginRight: -14,
    transform: [{ rotate: "-6deg" }],
  },
  tableSurfaceTiltRight: {
    transform: [{ rotate: "6deg" }],
  },
  tableSurfaceHeroTiltLeft: {
    marginRight: -10,
    transform: [{ rotate: "-7deg" }],
  },
  tableSurfaceHeroTiltRight: {
    transform: [{ rotate: "7deg" }],
  },
  tableControlGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
});
