export const ADMIN_PERMISSION_KEYS = {
  ANALYTICS_READ: 'analytics.read',
  AUDIT_EXPORT: 'audit.export',
  AUDIT_READ: 'audit.read',
  AUDIT_RETRY_NOTIFICATION: 'audit.retry_notification',
  CONFIG_READ: 'config.read',
  CONFIG_RELEASE_BONUS: 'config.release_bonus',
  CONFIG_UPDATE: 'config.update',
  FINANCE_APPROVE_DEPOSIT: 'finance.approve_deposit',
  FINANCE_APPROVE_WITHDRAWAL: 'finance.approve_withdrawal',
  FINANCE_FAIL_DEPOSIT: 'finance.fail_deposit',
  FINANCE_PAY_WITHDRAWAL: 'finance.pay_withdrawal',
  FINANCE_READ: 'finance.read',
  FINANCE_RECONCILE: 'finance.reconcile',
  FINANCE_REJECT_WITHDRAWAL: 'finance.reject_withdrawal',
  PRIZES_CREATE: 'prizes.create',
  PRIZES_DELETE: 'prizes.delete',
  PRIZES_READ: 'prizes.read',
  PRIZES_TOGGLE: 'prizes.toggle',
  PRIZES_UPDATE: 'prizes.update',
  RISK_FREEZE_USER: 'risk.freeze_user',
  RISK_READ: 'risk.read',
  RISK_RELEASE_USER: 'risk.release_user',
} as const;

export type AdminPermissionKey =
  (typeof ADMIN_PERMISSION_KEYS)[keyof typeof ADMIN_PERMISSION_KEYS];

export const CONFIG_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.ANALYTICS_READ,
  ADMIN_PERMISSION_KEYS.CONFIG_READ,
  ADMIN_PERMISSION_KEYS.CONFIG_RELEASE_BONUS,
  ADMIN_PERMISSION_KEYS.CONFIG_UPDATE,
] as const satisfies readonly AdminPermissionKey[];

export const FINANCE_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.FINANCE_READ,
  ADMIN_PERMISSION_KEYS.FINANCE_APPROVE_DEPOSIT,
  ADMIN_PERMISSION_KEYS.FINANCE_FAIL_DEPOSIT,
  ADMIN_PERMISSION_KEYS.FINANCE_APPROVE_WITHDRAWAL,
  ADMIN_PERMISSION_KEYS.FINANCE_REJECT_WITHDRAWAL,
  ADMIN_PERMISSION_KEYS.FINANCE_PAY_WITHDRAWAL,
  ADMIN_PERMISSION_KEYS.FINANCE_RECONCILE,
] as const satisfies readonly AdminPermissionKey[];

export const PRIZES_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.ANALYTICS_READ,
  ADMIN_PERMISSION_KEYS.PRIZES_READ,
  ADMIN_PERMISSION_KEYS.PRIZES_CREATE,
  ADMIN_PERMISSION_KEYS.PRIZES_UPDATE,
  ADMIN_PERMISSION_KEYS.PRIZES_TOGGLE,
  ADMIN_PERMISSION_KEYS.PRIZES_DELETE,
] as const satisfies readonly AdminPermissionKey[];

export const SECURITY_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.AUDIT_READ,
  ADMIN_PERMISSION_KEYS.AUDIT_EXPORT,
  ADMIN_PERMISSION_KEYS.AUDIT_RETRY_NOTIFICATION,
  ADMIN_PERMISSION_KEYS.RISK_READ,
  ADMIN_PERMISSION_KEYS.RISK_FREEZE_USER,
  ADMIN_PERMISSION_KEYS.RISK_RELEASE_USER,
] as const satisfies readonly AdminPermissionKey[];

export const DEFAULT_ADMIN_PERMISSION_KEYS = [
  ...new Set<AdminPermissionKey>([
    ...PRIZES_ADMIN_PERMISSION_KEYS,
    ...FINANCE_ADMIN_PERMISSION_KEYS,
    ...SECURITY_ADMIN_PERMISSION_KEYS,
    ...CONFIG_ADMIN_PERMISSION_KEYS,
  ]),
] as const satisfies readonly AdminPermissionKey[];

const MFA_SENSITIVE_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.AUDIT_RETRY_NOTIFICATION,
  ADMIN_PERMISSION_KEYS.CONFIG_RELEASE_BONUS,
  ADMIN_PERMISSION_KEYS.CONFIG_UPDATE,
  ADMIN_PERMISSION_KEYS.FINANCE_APPROVE_DEPOSIT,
  ADMIN_PERMISSION_KEYS.FINANCE_APPROVE_WITHDRAWAL,
  ADMIN_PERMISSION_KEYS.FINANCE_FAIL_DEPOSIT,
  ADMIN_PERMISSION_KEYS.FINANCE_PAY_WITHDRAWAL,
  ADMIN_PERMISSION_KEYS.FINANCE_RECONCILE,
  ADMIN_PERMISSION_KEYS.FINANCE_REJECT_WITHDRAWAL,
] as const satisfies readonly AdminPermissionKey[];

const STEP_UP_ONLY_ADMIN_PERMISSION_KEYS = [
  ADMIN_PERMISSION_KEYS.RISK_FREEZE_USER,
  ADMIN_PERMISSION_KEYS.RISK_RELEASE_USER,
] as const satisfies readonly AdminPermissionKey[];

export const MFA_SENSITIVE_ADMIN_PERMISSIONS = new Set<AdminPermissionKey>(
  MFA_SENSITIVE_ADMIN_PERMISSION_KEYS
);

export const STEP_UP_ADMIN_PERMISSIONS = new Set<AdminPermissionKey>([
  ...MFA_SENSITIVE_ADMIN_PERMISSION_KEYS,
  ...STEP_UP_ONLY_ADMIN_PERMISSION_KEYS,
]);

export const hasAdminPermission = (
  permissionKeys: Iterable<string>,
  requiredPermission: AdminPermissionKey
) => new Set(permissionKeys).has(requiredPermission);

export const adminPermissionsRequireMfa = (permissionKeys: Iterable<string>) => {
  const grantedPermissions = new Set(permissionKeys);

  for (const permissionKey of MFA_SENSITIVE_ADMIN_PERMISSIONS) {
    if (grantedPermissions.has(permissionKey)) {
      return true;
    }
  }

  return false;
};
