import { z } from 'zod';

export const ApiErrorCodeSchema = z.string().trim().min(1);

export type ApiErrorCode = z.infer<typeof ApiErrorCodeSchema>;

export const normalizeApiErrorCode = (value: string): ApiErrorCode =>
  value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'DOMAIN_ERROR';

export const API_ERROR_CODES = {
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACTIVE_PAYMENT_PROVIDER_NOT_FOUND: 'ACTIVE_PAYMENT_PROVIDER_NOT_FOUND',
  ADMIN_AUTHENTICATION_REQUIRED: 'ADMIN_AUTHENTICATION_REQUIRED',
  ADMIN_MFA_ALREADY_ENABLED: 'ADMIN_MFA_ALREADY_ENABLED',
  ADMIN_MFA_CODE_REQUIRED: 'ADMIN_MFA_CODE_REQUIRED',
  ADMIN_MFA_ENROLLMENT_TOKEN_MISMATCH: 'ADMIN_MFA_ENROLLMENT_TOKEN_MISMATCH',
  ADMIN_MFA_NOT_ENABLED: 'ADMIN_MFA_NOT_ENABLED',
  ADMIN_MFA_REQUIRED: 'ADMIN_MFA_REQUIRED',
  ADMIN_SESSION_NO_LONGER_ACTIVE: 'ADMIN_SESSION_NO_LONGER_ACTIVE',
  ADMIN_STEP_UP_INVALID: 'ADMIN_STEP_UP_INVALID',
  ADMIN_STEP_UP_REQUIRED: 'ADMIN_STEP_UP_REQUIRED',
  ADMIN_USER_NOT_FOUND_FOR_EMAIL: 'ADMIN_USER_NOT_FOUND_FOR_EMAIL',
  ANOTHER_REVIEW_PENDING: 'ANOTHER_REVIEW_PENDING',
  API_KEY_ALREADY_EXPIRED: 'API_KEY_ALREADY_EXPIRED',
  API_KEY_ALREADY_REVOKED: 'API_KEY_ALREADY_REVOKED',
  API_KEY_ALREADY_ROTATED: 'API_KEY_ALREADY_ROTATED',
  API_KEY_EXPIRY_MUST_BE_IN_FUTURE: 'API_KEY_EXPIRY_MUST_BE_IN_FUTURE',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_ROTATION_FINALIZATION_FAILED: 'API_KEY_ROTATION_FINALIZATION_FAILED',
  API_KEY_SCOPE_FORBIDDEN: 'API_KEY_SCOPE_FORBIDDEN',
  AUTO_RELEASE_ENABLED: 'AUTO_RELEASE_ENABLED',
  BACKEND_REQUEST_FAILED: 'BACKEND_REQUEST_FAILED',
  BILLING_ACCOUNT_NOT_CONFIGURED: 'BILLING_ACCOUNT_NOT_CONFIGURED',
  BILLING_PERIOD_END_MUST_BE_AFTER_START: 'BILLING_PERIOD_END_MUST_BE_AFTER_START',
  BILLING_RUN_MANUAL_SEND_NOT_ALLOWED: 'BILLING_RUN_MANUAL_SEND_NOT_ALLOWED',
  BILLING_RUN_NOT_FOUND: 'BILLING_RUN_NOT_FOUND',
  BILLING_TOP_UP_NOT_FOUND: 'BILLING_TOP_UP_NOT_FOUND',
  BLACKJACK_MAX_SPLIT_HANDS_INVALID: 'BLACKJACK_MAX_SPLIT_HANDS_INVALID',
  BLACKJACK_MAX_STAKE_BELOW_MIN: 'BLACKJACK_MAX_STAKE_BELOW_MIN',
  BLACKJACK_MIN_STAKE_INVALID: 'BLACKJACK_MIN_STAKE_INVALID',
  BLACKJACK_NATURAL_PAYOUT_MULTIPLIER_INVALID:
    'BLACKJACK_NATURAL_PAYOUT_MULTIPLIER_INVALID',
  BLACKJACK_PUSH_PAYOUT_MULTIPLIER_INVALID:
    'BLACKJACK_PUSH_PAYOUT_MULTIPLIER_INVALID',
  BLACKJACK_RESPLIT_REQUIRES_HIGHER_MAX_HANDS:
    'BLACKJACK_RESPLIT_REQUIRES_HIGHER_MAX_HANDS',
  BLACKJACK_WIN_PAYOUT_MULTIPLIER_INVALID:
    'BLACKJACK_WIN_PAYOUT_MULTIPLIER_INVALID',
  CONFIG_CHANGE_REQUEST_FINALIZED: 'CONFIG_CHANGE_REQUEST_FINALIZED',
  CONFIG_CHANGE_REQUEST_NOT_FOUND: 'CONFIG_CHANGE_REQUEST_NOT_FOUND',
  CONFIG_CHANGE_SELF_APPROVAL_FORBIDDEN: 'CONFIG_CHANGE_SELF_APPROVAL_FORBIDDEN',
  DAILY_WITHDRAWAL_LIMIT_EXCEEDED: 'DAILY_WITHDRAWAL_LIMIT_EXCEEDED',
  DEPOSIT_NOT_FOUND: 'DEPOSIT_NOT_FOUND',
  DIFFERENT_REVIEWER_REQUIRED: 'DIFFERENT_REVIEWER_REQUIRED',
  DIRECT_CONFIG_UPDATES_DISABLED: 'DIRECT_CONFIG_UPDATES_DISABLED',
  DRAW_COOLDOWN_ACTIVE: 'DRAW_COOLDOWN_ACTIVE',
  DRAW_COST_NEGATIVE: 'DRAW_COST_NEGATIVE',
  DRAW_DAILY_LIMIT_REACHED: 'DRAW_DAILY_LIMIT_REACHED',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  FAILED_TO_ACCEPT_INVITATION: 'FAILED_TO_ACCEPT_INVITATION',
  FAILED_TO_CREATE_BILLING_RUN: 'FAILED_TO_CREATE_BILLING_RUN',
  FAILED_TO_CREATE_BILLING_TOP_UP: 'FAILED_TO_CREATE_BILLING_TOP_UP',
  FAILED_TO_CREATE_FAIRNESS_SEED: 'FAILED_TO_CREATE_FAIRNESS_SEED',
  FAILED_TO_INITIALIZE_PROJECT_PLAYER: 'FAILED_TO_INITIALIZE_PROJECT_PLAYER',
  FAILED_TO_SAVE_BILLING_ACCOUNT: 'FAILED_TO_SAVE_BILLING_ACCOUNT',
  FAILED_TO_UPDATE_PROJECT_PLAYER: 'FAILED_TO_UPDATE_PROJECT_PLAYER',
  FAIRNESS_REVEAL_NOT_AVAILABLE: 'FAIRNESS_REVEAL_NOT_AVAILABLE',
  FAIRNESS_REVEAL_NOT_FOUND: 'FAIRNESS_REVEAL_NOT_FOUND',
  FIELD_INVALID: 'FIELD_INVALID',
  FIELD_MUST_BE_NON_NEGATIVE_INTEGER: 'FIELD_MUST_BE_NON_NEGATIVE_INTEGER',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_TOO_LONG: 'FIELD_TOO_LONG',
  FREEZE_RECORD_NOT_FOUND: 'FREEZE_RECORD_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_WITHDRAWABLE_BALANCE: 'INSUFFICIENT_WITHDRAWABLE_BALANCE',
  INVALID_ADMIN_CREDENTIALS: 'INVALID_ADMIN_CREDENTIALS',
  INVALID_ADMIN_MFA_CODE: 'INVALID_ADMIN_MFA_CODE',
  INVALID_API_KEY: 'INVALID_API_KEY',
  INVALID_API_KEY_EXPIRY: 'INVALID_API_KEY_EXPIRY',
  INVALID_BILLING_PERIOD: 'INVALID_BILLING_PERIOD',
  INVALID_BILLING_RUN_ID: 'INVALID_BILLING_RUN_ID',
  INVALID_CONFIG_CHANGE_REQUEST_ID: 'INVALID_CONFIG_CHANGE_REQUEST_ID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_CURSOR: 'INVALID_CURSOR',
  INVALID_DEPOSIT_ID: 'INVALID_DEPOSIT_ID',
  INVALID_NOTIFICATION_DELIVERY_ID: 'INVALID_NOTIFICATION_DELIVERY_ID',
  INVALID_OR_EXPIRED_VERIFICATION_CODE: 'INVALID_OR_EXPIRED_VERIFICATION_CODE',
  INVALID_OR_EXPIRED_VERIFICATION_TOKEN: 'INVALID_OR_EXPIRED_VERIFICATION_TOKEN',
  INVALID_PAYMENT_PROVIDER_ID: 'INVALID_PAYMENT_PROVIDER_ID',
  INVALID_PRIZE_ID: 'INVALID_PRIZE_ID',
  INVALID_PROJECT_ID: 'INVALID_PROJECT_ID',
  INVALID_PROJECT_OR_KEY_ID: 'INVALID_PROJECT_OR_KEY_ID',
  INVALID_PROJECT_OR_PRIZE_ID: 'INVALID_PROJECT_OR_PRIZE_ID',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_SLUG: 'INVALID_SLUG',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',
  INVALID_TENANT_LINK_ID: 'INVALID_TENANT_LINK_ID',
  INVALID_TENANT_OR_INVITE_ID: 'INVALID_TENANT_OR_INVITE_ID',
  INVALID_TENANT_OR_MEMBERSHIP_ID: 'INVALID_TENANT_OR_MEMBERSHIP_ID',
  INVALID_TOP_UP_ID: 'INVALID_TOP_UP_ID',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_WITHDRAWAL_ID: 'INVALID_WITHDRAWAL_ID',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED',
  LOGIN_DISABLED: 'LOGIN_DISABLED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  MISSING_EMAIL_OR_PASSWORD: 'MISSING_EMAIL_OR_PASSWORD',
  MINIMUM_WAGER_REQUIREMENT_NOT_MET: 'MINIMUM_WAGER_REQUIREMENT_NOT_MET',
  NO_BILLING_ACCOUNT_VERSION_FOR_PERIOD: 'NO_BILLING_ACCOUNT_VERSION_FOR_PERIOD',
  NOT_FOUND: 'NOT_FOUND',
  NOTIFICATION_DELIVERY_NOT_FOUND: 'NOTIFICATION_DELIVERY_NOT_FOUND',
  NOTIFICATION_DELIVERY_RETRY_NOT_ALLOWED:
    'NOTIFICATION_DELIVERY_RETRY_NOT_ALLOWED',
  ONLY_APPROVED_REQUESTS_PUBLISHABLE: 'ONLY_APPROVED_REQUESTS_PUBLISHABLE',
  ONLY_DRAFT_REQUESTS_SUBMITTABLE: 'ONLY_DRAFT_REQUESTS_SUBMITTABLE',
  ONLY_PENDING_REQUESTS_APPROVABLE: 'ONLY_PENDING_REQUESTS_APPROVABLE',
  OPERATOR_NOTE_REQUIRED: 'OPERATOR_NOTE_REQUIRED',
  OUTBOUND_REQUEST_IDEMPOTENCY_CONFLICT_UNRESOLVED:
    'OUTBOUND_REQUEST_IDEMPOTENCY_CONFLICT_UNRESOLVED',
  OUTBOUND_REQUEST_PAYLOAD_MISMATCH: 'OUTBOUND_REQUEST_PAYLOAD_MISMATCH',
  PAYMENT_PROVIDER_NOT_FOUND: 'PAYMENT_PROVIDER_NOT_FOUND',
  PAYMENT_PROVIDER_PRIORITY_NEGATIVE: 'PAYMENT_PROVIDER_PRIORITY_NEGATIVE',
  PHONE_ALREADY_IN_USE: 'PHONE_ALREADY_IN_USE',
  PHONE_VERIFICATION_REQUIRED: 'PHONE_VERIFICATION_REQUIRED',
  POOL_BALANCE_NEGATIVE: 'POOL_BALANCE_NEGATIVE',
  PRIZE_NOT_FOUND: 'PRIZE_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_PLAYER_NOT_FOUND: 'PROJECT_PLAYER_NOT_FOUND',
  PROJECT_PRIZE_NOT_FOUND: 'PROJECT_PRIZE_NOT_FOUND',
  PROCESSING_CHANNEL_MISMATCH: 'PROCESSING_CHANNEL_MISMATCH',
  PROCESSING_CHANNEL_REQUIRED: 'PROCESSING_CHANNEL_REQUIRED',
  PRIZE_POOL_RESERVE_TOO_LOW_FOR_STAKE: 'PRIZE_POOL_RESERVE_TOO_LOW_FOR_STAKE',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  REGISTRATION_LIMIT_REACHED: 'REGISTRATION_LIMIT_REACHED',
  SAAS_STRIPE_DEPENDENCY_NOT_CONFIGURED:
    'SAAS_STRIPE_DEPENDENCY_NOT_CONFIGURED',
  SAAS_STRIPE_NOT_CONFIGURED: 'SAAS_STRIPE_NOT_CONFIGURED',
  SAAS_STRIPE_WEBHOOK_SECRET_NOT_CONFIGURED:
    'SAAS_STRIPE_WEBHOOK_SECRET_NOT_CONFIGURED',
  SAAS_TENANT_ACCESS_FORBIDDEN: 'SAAS_TENANT_ACCESS_FORBIDDEN',
  SAAS_TENANT_ROLE_FORBIDDEN: 'SAAS_TENANT_ROLE_FORBIDDEN',
  SAAS_WEBHOOK_PAYLOAD_INVALID: 'SAAS_WEBHOOK_PAYLOAD_INVALID',
  SECOND_CONFIRMATION_REQUIRED: 'SECOND_CONFIRMATION_REQUIRED',
  SETTLEMENT_REFERENCE_MISMATCH: 'SETTLEMENT_REFERENCE_MISMATCH',
  SETTLEMENT_REFERENCE_REQUIRED: 'SETTLEMENT_REFERENCE_REQUIRED',
  STAKE_AMOUNT_OUT_OF_RANGE: 'STAKE_AMOUNT_OUT_OF_RANGE',
  STRIPE_CUSTOMER_NOT_CONFIGURED: 'STRIPE_CUSTOMER_NOT_CONFIGURED',
  STRIPE_INVOICE_NOT_CREATED_FOR_BILLING_RUN:
    'STRIPE_INVOICE_NOT_CREATED_FOR_BILLING_RUN',
  STRIPE_SETUP_SESSION_REDIRECT_URL_MISSING:
    'STRIPE_SETUP_SESSION_REDIRECT_URL_MISSING',
  TENANT_CANNOT_LINK_TO_ITSELF: 'TENANT_CANNOT_LINK_TO_ITSELF',
  TENANT_INVITE_NOT_FOUND: 'TENANT_INVITE_NOT_FOUND',
  TENANT_LINK_NOT_FOUND: 'TENANT_LINK_NOT_FOUND',
  TENANT_MEMBERSHIP_NOT_FOUND: 'TENANT_MEMBERSHIP_NOT_FOUND',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_OWNER_REQUIRED: 'TENANT_OWNER_REQUIRED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNSUPPORTED_LOCALE: 'UNSUPPORTED_LOCALE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WEBHOOK_EVENT_DEDUPE_CONFLICT_UNRESOLVED:
    'WEBHOOK_EVENT_DEDUPE_CONFLICT_UNRESOLVED',
  WEBHOOK_PAYLOAD_INVALID_JSON: 'WEBHOOK_PAYLOAD_INVALID_JSON',
  WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',
} as const satisfies Record<string, ApiErrorCode>;

export type KnownApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const ApiErrorSchema = z.object({
  message: z.string(),
  code: ApiErrorCodeSchema.optional(),
  details: z.array(z.string()).optional(),
});

export type ApiError = z.infer<typeof ApiErrorSchema>;

export type ApiSuccess<T> = {
  ok: true;
  data: T;
  requestId?: string;
  traceId?: string;
  status?: number;
};

export type ApiFailure = {
  ok: false;
  error: ApiError;
  requestId?: string;
  traceId?: string;
  status?: number;
};

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

export const ApiSuccessSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.object({
    ok: z.literal(true),
    data: dataSchema,
    requestId: z.string().optional(),
    traceId: z.string().optional(),
    status: z.number().int().optional(),
  });

export const ApiFailureSchema = z.object({
  ok: z.literal(false),
  error: ApiErrorSchema,
  requestId: z.string().optional(),
  traceId: z.string().optional(),
  status: z.number().int().optional(),
});

export const ApiEnvelopeSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.union([ApiSuccessSchema(dataSchema), ApiFailureSchema]);
